### ISSUE TITLE
Can't type ";" on one of my machines

### ISSUE THREAD

**Issue by codemonkeychris** [Microsoft/TypeScript-Sublime-Plugin#102]
Using Sublime Text v3 - 3083 in "portable configuration", I cloned the repo into the Sublime data\packages directory (Windows 10)... I have a second machine that this appears to work.

**Comment by billti** [comment]
Is this with the latest bits?  #93 fixed a very similar issue.

**Comment by steveluc** [comment]
OK Chris, that sounds like an install issue in which the TypeScript Server process does not successfully start.  We find node using the path environment variable + /usr/local/bin.  See the Tips part of the README.md for how to set the node_path setting to find the node executable.   Open the Sublime console (ctrl + `) to see whether there are messages indicating the server has not started and whether node was found.

**Comment by steveluc** [comment]
I have updated the plug-in so that it pays attention to node_path on Windows.  I did a portable install of Sublime and verified it works.  However, I don't know @codemonkeychris if this is your issue because I do not need to set node_path to make it work.

**Comment by codemonkeychris** [comment]
I think it was actually needing a system log out to pick up the env. variable from Node. Installing node puts the npm user directory on the path is the user env. vars, which get picked up with a console restart, but the path to node itself is in system vars... Anyway, a reboot and this patch, and everything seems golden.

**Comment by steveluc** [comment]
Added additional information to README.md on finding node on path env variable.  Added Requirements section to README.md to emphasize node requirement.

Commit 749959b
