### ISSUE TITLE
ST3 is slow to shut down when lots of TS files are open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/TypeScript-Sublime-Plugin#104]
This seems to be recent - when I close Sublime and I have lots of TS files open (20 +), it takes 10 or 15 seconds before the process is gone from Task Manager. If I try to open ST again during that time, nothing happens. When I only have lots of non-TS files open, it shuts down immediately.

**Comment by steveluc** [comment]
I have noticed this also.  What version of Sublime are you running?  I have only noticed this behavior on new dev builds of Sublime.

**Comment by roblourens** [comment]
"Stable channel, build 3083"

**Comment by zhengbli** [comment]
It is slow because each time a file gets closed the plugin sends out a notice to the server. Fixed by batching up the process. Sent pull request #110

**Comment by steveluc** [comment]
:+1:   I like the approach of catching the window commands and avoiding open messages.

Great to see the analysis of the event order and the addition of logging.
