### ISSUE TITLE
Sublime ToggleComment/Block should be supported in TypeScript plugin

### ISSUE THREAD

**Issue by codemonkeychris** [Microsoft/TypeScript-Sublime-Plugin#106]
With the TypeScript plugin enabled you loose the comment block feature (default mapped to `Ctrl+/` and `Ctrl+Shift+/`, would be great to support this!

**Comment by billti** [comment]
Chris, I just added a file in a new `comments` branch (09e6b241d6c4c0b) which should fix this.  Can you give it a try before I merge to `master` and ensure this is good for you.

**Comment by billti** [comment]
This is in master now.  Reopen if you have any problems with it.
