### ISSUE TITLE
Default key in plugin ';' prevents me from typing said key in code

### ISSUE THREAD

**Issue by agmcleod** [Microsoft/TypeScript-Sublime-Plugin#113]
Rather bothersome for when trying to correct an error from leaving out a semicolon. It's the keymap for auto indenting.

**Comment by zhengbli** [comment]
Does this happen in a unsaved buffer? #93 and #102 look similar.

**Comment by steveluc** [comment]
In the other two cases, the semi-colon did not appear because the server had not come up.  @agmcleod could you check the console (ctrl + `) to see if there are messages about bringing up the server?  Where is node installed on that machine?  

I will change the plug-in so that it still lets you type a ';' in this situation.

**Comment by agmcleod** [comment]
@zhengbli unsaved or saved seems to have the issue. If i do a new tab even, set syntax to typescript the issue occurs.

@steveluc not seeing any errors. I opened up a simple .ts file. Able to make changes and save okay. Compiles out the .js file.

I think i installed node from the website's installer. Binary is: `/usr/local/bin/node`, using `v0.12.0`.

**Comment by steveluc** [comment]
Are you getting completions?

**Comment by steveluc** [comment]
In commit 04fe273, added exception handling for the case where the node executable isn't found.  This should make the ';' appear if that is the problem.  If that's not the problem, we may need to ask you to send us an excerpt of the console output for the plug-in.

**Comment by agmcleod** [comment]
@steveluc no completions. `;` does format on key i think though, not auto complete.

Did a git pull and restarted sublime, still cannot type `;` character. Here's what i see in the console after restarting:

    startup, version: 3083 osx x64 channel: stable
    executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
    working dir: /
    packages path: /Users/aaronmcleod/Library/Application Support/Sublime Text 3/Packages
    state path: /Users/aaronmcleod/Library/Application Support/Sublime Text 3/Local
    zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
    zip path: /Users/aaronmcleod/Library/Application Support/Sublime Text 3/Installed Packages
    ignored_packages: ["SublimeCodeIntel", "SublimePaster", "threejs", "Theme - Afterglow", "Better TypeScript", "Vintage"]
    pre session restore time: 0.58544
    using gpu buffer for window
    first paint time: 0.718588
    startup time: 0.791619
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.quick_panel
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.02-bz2
    reloading plugin AutoFileName.autofilename
    reloading plugin AutoFileName.getimageinfo
    reloading plugin Emmet.emmet-plugin
    reloading plugin FuzzyFilePath.command_goto_file
    reloading plugin FuzzyFilePath.command_rebuild_cache
    reloading plugin FuzzyFilePath.command_replace_region
    reloading plugin FuzzyFilePath.command_set_project_directory
    reloading plugin FuzzyFilePath.command_show_context
    reloading plugin FuzzyFilePath.command_show_current_settings
    reloading plugin FuzzyFilePath.command_show_info
    reloading plugin FuzzyFilePath.CurrentFileListener
    reloading plugin FuzzyFilePath.expression
    reloading plugin FuzzyFilePath.FuzzyFilePath
    reloading plugin FuzzyFilePath.ProjectListener
    reloading plugin FuzzyFilePath.QueryCompletionListener
    reloading plugin FuzzyFilePath.TestIntegration
    reloading plugin GitGutter.git_gutter
    reloading plugin GitGutter.git_gutter_change
    reloading plugin GitGutter.git_gutter_compare
    reloading plugin GitGutter.git_gutter_events
    reloading plugin GitGutter.git_gutter_handler
    reloading plugin GitGutter.git_helper
    reloading plugin GitGutter.view_collection
    reloading plugin Google Spell Check.google-spell-check
    reloading plugin Haxe.HaxeComplete
    hello
    Haxe : Reloading haxe module
    Haxe : Reloading haxelib module
    HAXE : haxelib list 
    HAXE : haxelib install 
    HAXE : haxelib search 
    HAXE : haxelib upgrade 
    reloading plugin Package Control.bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin Pretty JSON.PrettyJson
    [Errno 2] No such file or directory: 'jq'
    reloading plugin SCSS.scss_completions
    reloading plugin SublimeGit.SublimeGit
    reloading plugin SublimeOnSaveBuild.SublimeOnSaveBuild
    reloading plugin TrailingSpaces.trailing_spaces
    reloading plugin TypescriptCompletion.TSCompletion
    reloading plugin TypeScript.TypeScript
    2015-04-06 19:40:07,567: INFO: Logging configured to log to file: /Users/aaronmcleod/Library/Application Support/Sublime Text 3/Installed Packages/TS.log
    [2015-04-06 19:40:07,567 - INFO     - TS] Logging configured to log to file: /Users/aaronmcleod/Library/Application Support/Sublime Text 3/Installed Packages/TS.log
    2015-04-06 19:40:07,567: WARNING: TypeScript plugin initialized.
    [2015-04-06 19:40:07,567 - WARNING  - TS] TypeScript plugin initialized.
    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
        m = importlib.import_module(modulename)
      File "./importlib/__init__.py", line 90, in import_module
      File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 678, in load_module
        exec(compile(source, source_path, 'exec'), mod.__dict__)
      File "/Users/aaronmcleod/Library/Application Support/Sublime Text 3/Packages/TypeScript/TypeScript.py", line 38, in <module>
        from nodeclient import NodeCommClient
    ImportError: No module named 'nodeclient'
    plugins loaded
    Emmet: No need to update PyV8
    Package Control: Skipping automatic upgrade, last run at 2015-04-06 19:21:41, next run at 2015-04-06 20:21:41 or after

**Comment by uglycoyote** [comment]
I'm also running in to this issue.  Sublime 3 Build 3083 on Mac, latest version of Typescript plugin as of current time.  Semicolon does not work in Typescript buffer, but works fine in other buffers.  Also cannot paste with Cmd-V but pasting using the menu option works fine. 

I also have Sublime 2 (build 2221) on this machine, and it does not suffer from the same issue.

**Comment by billti** [comment]
Interesting.  We update the search path to put our module folder on it.  Could you please try the below to see what the result is.

1. Open the Sublime console ( View / Show Console )
2. In the console, first run "import sys", then run "sys.path"
3. You should see output such as `['/Users/bill/Library/Application Support/Sublime Text 3/Packages/TypeScript/libs', '/Applications/Sublime Text.app/Contents/MacOS', '/Applications/Sublime Text.app/Contents/MacOS/python3.3.zip', '/Users/bill/Library/Application Support/Sublime Text 3/Packages', '/Users/bill/Library/Application Support/Sublime Text 3/Packages/bz2/st3_osx_x64']`
4. Note how one of the paths has the `./libs` folder of the TypeScript plugin on it.  Does yours?
5. If so, can you confirm the `nodeclient.py` module is present in this folder.  Anything look odd about your paths or package locations compared to mine above?

One other question - is this a regular install or a portable install?

Sorry for the hassle.  Hopefully we can figure this out soon.

**Comment by uglycoyote** [comment]
Thank you, looking at sys.path did point me to the source of the trouble:

<pre>
'/Users/mike/Library/Application Support/Sublime Text 3/Installed Packages/TypeScript.sublime-package/libs'
</pre>

This was from a previously installed plugin called "TypeScript" which I think used to exist on package control but no longer does (not sure if that was an earlier version of your plugin, or a completely separate one).  Since your TypeScript plugin does not seem to exist on Package Control yet I followed the instructions to clone the repo into a TypeScript directory under my "/Application Support/Sublime Text 3/Packages/"  but the sys.path did not reference the newly created TypeScript directory, only this old "Typescript.sublime-package/libs".

Using Package Manager to remove all Typescript related plugins (I had a couple others, including BetterTypescript and TypeScriptCompletion) and then redoing the "git clone" solved my issue.  I don't think the BetterTypescript and TypeScriptCompletion plugins had anything to do with the problem, but they never did anything worthwhile for me that I was aware of, so I nuked them.

**Comment by agmcleod** [comment]
Yeah that seemed to be my issue too, the older TypeScript package.

**Comment by uglycoyote** [comment]
Probably a large number of potential users of this new Microsoft Typescript plugin will have also tried the old "TypeScript" plugin that caused the name conflict.  This might not be a problem once you guys get on package control, since it seems like the name is going to be "TypeScriptLang" according to the front page.  

But you might want to do one of the following things to help prevent this:
- Change the "git clone" unstructions to use a different directory name, not "TypeScript", or at least provide a warning that users should watch out for naming conflicts and remove any previous plugins named "TypeScript"
- Change your TypeScript plugin to validate the sys.path to check for this problem, provide clearer error if the sys.path does not contain the expected directory.

**Comment by billti** [comment]
I added the note about the conflict and changing the name to the readme once we identified the cause.  See 212464a0b1 .
