### ISSUE TITLE
Tsc version?

### ISSUE THREAD

**Issue by nojaf** [Microsoft/TypeScript-Sublime-Plugin#116]
This might be a stupid question but I seem to miss the minimum Typescript version needed for this plugin? Is the 1.5 Alpha required?

**Comment by billti** [comment]
The plugin is largely self-contained (the tsserver.js file under the plugin folder contains a copy of the compiler and language service).  If you are also building on the box, you'll likely want to keep your TypeScript version in sync with the plugin, and yes, it is based on the 1.5.0-alpha.
