### ISSUE TITLE
Instruction for manual package installation in Windows is missing

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript-Sublime-Plugin#118]
Please note that the mentioned path
```
~/Library/Application Support/Sublime Text 3
```
works only in iOS

For Windows users it should be 
```
%APPDATA%\Sublime Text 3
```

Source: http://docs.sublimetext.info/en/latest/basic_concepts.html#the-data-directory

Also: http://docs.sublimetext.info/en/latest/basic_concepts.html#the-user-package

**Comment by billti** [comment]
I updated the readme to include this info.  See aac22c8deee3bc
