### ISSUE TITLE
Plugin gets so laggy sometimes and losts error checking and auto complete.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript-Sublime-Plugin#119]
On both Mac and Windows, Sublime 2 and 3.

My workmate runs into this issue almost every time (on Mac), I met this issue once (on Windows).

**Comment by vilic** [comment]
These steps *might* trigger this issue:

1. Type "class" and tab to expand the snippet.
2. Delete class name to the start.
3. Delete everything.

**Comment by steveluc** [comment]
Lag and losing error checking and auto complete could be symptoms of the server crashing.  Could you look in the console output to see if you see "queue timeout" a lot of times.  

Will try your repro steps.

**Comment by vilic** [comment]
Not seeing queue timeout on my PC, but seeing a lot of it on the Mac of my workmate. (Actually it doesn't even need steps to reproduce, it just lags from the very beginning.)

**Comment by billti** [comment]
Actually, I just did a sync of the latest bits and opened them up with Sublime Text 2, and I'm seeing a lot of lag, broken features, and the below in the console:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/bill/src/TypeScript-Sublime-Plugin/libs/nodeclient.py", line 213, in __reader
    NodeCommClient.__readMsg(stream, msgq, eventq, asyncReq)
  File "/Users/bill/src/TypeScript-Sublime-Plugin/libs/nodeclient.py", line 200, in __readMsg
    callback(dict)
  File "/Users/bill/src/TypeScript-Sublime-Plugin/libs/serviceproxy.py", line 43, in onCompletedJson
    onCompleted(obj)
  File "./TypeScript.py", line 854, in handleCompletionInfo
  File "./TypeScript.py", line 55, in active_view
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

@steveluc, some of the lines reported above correspond with yesterday's checkin of 9a8377e1a6b for `async message correlation` (which would seem to correlate with the threading violation reported above).  Can you take a quick look and back out if the fix isn't obvious?  Thanks.

**Comment by MarlonFan** [comment]
Same @steveluc
```
Package Control: Installing 1 upgrades
request: {"type": "request", "command": "configure", "arguments": {"formatOptions": {"tabSize": 4, "indentSize": 4}, "hostInfo": "Sublime Text version 2221", "file": "/Users/marlon/code/type/first.ts"}, "seq": 31}
queue timeout
request: {"type": "request", "command": "configure", "arguments": {"formatOptions": {"tabSize": 4, "indentSize": 4}, "hostInfo": "Sublime Text version 2221", "file": "/Users/marlon/code/type/first.ts"}, "seq": 32}
queue timeout
ignored packages updated to: [Vintage, TypeScript]
found 1 files for base name Default.sublime-theme
request: {"type": "request", "command": "configure", "arguments": {"formatOptions": {"tabSize": 4, "indentSize": 4}, "hostInfo": "Sublime Text version 2221", "file": "/Users/marlon/code/type/first.ts"}, "seq": 33}
queue timeout
request: {"type": "request", "command": "configure", "arguments": {"formatOptions": {"tabSize": 4, "indentSize": 4}, "hostInfo": "Sublime Text version 2221", "file": "/Users/marlon/code/type/first.ts"}, "seq": 34}
```

**Comment by steveluc** [comment]
The console output shows that the server is not up.  This is different from the async completions issue that Bill is referencing.  That one looks like we'll need to use synchronous messaging for completions on ST2.
