### ISSUE TITLE
'quickInfo' request should return symbol display parts as completion does

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#12]
That would allow for a nice formatting in the UI and makes the overall API more consistence.

**Comment by billti** [comment]
Per above, the service/protocol is part of the TypeScript repo (specifically, see https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.d.ts#L477 ).  The Sublime plugin just surfaces the properties of the JSON it is given.  Please open an issue there if still desired.

**Comment by dbaeumer** [comment]
Copied to https://github.com/Microsoft/TypeScript/issues/2850
