### ISSUE TITLE
Format options (tabs instead of spaces)

### ISSUE THREAD

**Issue by lucasmciruzzi** [Microsoft/TypeScript-Sublime-Plugin#120]
It'll be nice if I could set the format options to use tabulations instead of spaces when pressing [^T, F].

**Comment by DanielRosenwasser** [comment]
This has to do with TypeScript's services API, not this plugin. See https://github.com/Microsoft/TypeScript/issues/2306 and feel free to voice your opinion there.

**Comment by lucasmciruzzi** [comment]
Thanks!
