### ISSUE TITLE
Completion popup appears and disappears instantly

### ISSUE THREAD

**Issue by uglycoyote** [Microsoft/TypeScript-Sublime-Plugin#121]
I'm running under Sublime 2 v 2221.   Typescript plugin is working but the completion popups are popping up only for a fleeting moment and then disappear again.  

I have pasted the "greeter" sample in, and typed "var x = greeter" on a new line, and then when I press "." after greeter I see the popup just for an instant and then it is gone.   I can keep pressing backspace and "." again and it will only every flash.  Sometimes I don't see it at all.

Same behaviour if I press Ctrl+Space (the hotkey for "show completions")

While testing this, If I open the ctrl+` console,   I'm seeing an abnormal amount of output from the typescript plugin (well, I don't have any basis for comparison of how much output is 'normal' for this plugin but it seems like a lot).  Maybe some of this output can tell you what's going wrong

<pre>

time for reload 0.001839
request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 740}
response: {"seq":0,"type":"response","command":"reload","request_seq":740,"success":true}

time for reload 0.002221
request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 741}
response: {"seq":0,"type":"response","command":"reload","request_seq":741,"success":true}

time for reload 0.001763
request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 742}
response: {"seq":0,"type":"response","command":"reload","request_seq":742,"success":true}

time for reload 0.001812
request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 743}
response: {"seq":0,"type":"response","command":"reload","request_seq":743,"success":true}

time for reload 0.001661
request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 744}
response: {"seq":0,"type":"response","command":"reload","request_seq":744,"success":true}

time for reload 0.001653
request: {"type": "request", "command": "geterr", "arguments": {"files": ["/Users/mike/TypeScript/Greeter/Greeter.ts"], "delay": 500}, "seq": 745}
event: {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/Users/mike/TypeScript/Greeter/Greeter.ts","diagnostics":[]}}

event: {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/Users/mike/TypeScript/Greeter/Greeter.ts","diagnostics":[]}}

request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 746}
response: {"seq":0,"type":"response","command":"reload","request_seq":746,"success":true}

time for reload 0.001562
request: {"type": "request", "command": "quickinfo", "arguments": {"line": 11, "file": "/Users/mike/TypeScript/Greeter/Greeter.ts", "offset": 16}, "seq": 747}
response: {"seq":0,"type":"response","command":"quickinfo","request_seq":747,"success":true,"body":{"kind":"var","kindModifiers":"","start":{"line":11,"offset":9},"end":{"line":11,"offset":16},"displayString":"var greeter: Greeter","documentation":""}}

request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 748}
response: {"seq":0,"type":"response","command":"reload","request_seq":748,"success":true}

time for reload 0.001565
request: {"type": "request", "command": "quickinfo", "arguments": {"line": 11, "file": "/Users/mike/TypeScript/Greeter/Greeter.ts", "offset": 16}, "seq": 749}
response: {"seq":0,"type":"response","command":"quickinfo","request_seq":749,"success":true,"body":{"kind":"var","kindModifiers":"","start":{"line":11,"offset":9},"end":{"line":11,"offset":16},"displayString":"var greeter: Greeter","documentation":""}}

request: {"type": "request", "command": "reload", "arguments": {"tmpfile": "/Users/mike/Library/Application Support/Sublime Text 2/Packages/TypeScript/.tmpbuf", "file": "/Users/mike/TypeScript/Greeter/Greeter.ts"}, "seq": 750}
response: {"seq":0,"type":"response","command":"reload","request_seq":750,"success":true}

time for reload 0.001830
request: {"type": "request", "command": "quickinfo", "arguments": {"line": 11, "file": "/Users/mike/TypeScript/Greeter/Greeter.ts", "offset": 16}, "seq": 751}
response: {"seq":0,"type":"response","command":"quickinfo","request_seq":751,"success":true,"body":{"kind":"var","kindModifiers":"","start":{"line":11,"offset":9},"end":{"line":11,"offset":16},"displayString":"var greeter: Greeter","documentation":""}}

</pre>

(I also have the latest Sublime 3, but cannot get TypeScript plugin working under Sublime 3 due to "no module named 'nodeclient'" failure mentioned in issue #113)

**Comment by uglycoyote** [comment]
More info: After getting plugin working under Sublime Text 3 I can confirm that the popups work fine under Sublime 3, and this is only a Sublime 2 issue.

**Comment by billti** [comment]
Yeah, I'm wondering if this might be the #119 issue impacting Sublime Text 2 with the recent check-in.  Could you try going into the TypeScript package folder and checking out a commit prior, i.e. `git checkout 49936f7c0538`.  If the async addition is the cause this should resolve it.  We'll get that address shortly.

**Comment by uglycoyote** [comment]
yeah going back to 49936f7c0538 totally makes the problem go away, and then going back to 'master' made the problem come back again.

More information about the problem: not only does it not show the completion popup, but also there's a long pause sometimes (1-2 seconds) after typing the '.' where Sublime doesn't respond to my typing any further characters.  So it's basically unusable as an editor in that state (though, only a problem in .ts buffers)

**Comment by steveluc** [comment]
I will change the async completions to work only under ST3

**Comment by steveluc** [comment]
Done.  Please try again with latest in master.

**Comment by DanielRosenwasser** [comment]
@uglycoyote, if the problem persists, let us know and we'll reopen this issue.

**Comment by uglycoyote** [comment]
sorry I didn't give feedback after the fix, but I just pulled the latest and tested in Sublime 2 and the problem is fixed.  Thanks!

**Comment by DanielRosenwasser** [comment]
Great! Keep us posted if you catch anything else.
