### ISSUE TITLE
add support ENV for "node_path" setting

### ISSUE THREAD

**Issue by tgfjt** [Microsoft/TypeScript-Sublime-Plugin#126]
Hi.

`"node_path": "/Users/tgfjt/bin/node"` works well.
But `"node_path": "$HOME/bin/node"` does not works.

If we can do it. It'll be useful.

**Comment by DanielRosenwasser** [comment]
Sorry, could you elaborate a bit more? Are you asking us to expand environment variables in your `node_path`?

**Comment by tgfjt** [comment]
Sorry! it's not enough words.

Yes, I want that expanding ENV variables in `node_path`, because I use a `Preferences.sublime-settings` between some machines.
