### ISSUE TITLE
wrong indentation when 'typescript_auto_format' is true

### ISSUE THREAD

**Issue by squeral** [Microsoft/TypeScript-Sublime-Plugin#129]
When using tabs for indentation with 'typescript_auto_format' set to true this happens:
![indentation](https://cloud.githubusercontent.com/assets/2511646/7047558/2ffc0910-de05-11e4-902d-6d20aa123041.gif)

**Comment by steveluc** [comment]
Fixed in commit 71aa8bd (in master; not yet up in PackageControl).  Please give this a try (by cloning master as TypeScript package) and give us feedback.

**Comment by squeral** [comment]
It's working great for me. Thank you!
