### ISSUE TITLE
Reference paths required?

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript-Sublime-Plugin#130]
I have a project which uses internal modules exclusively. I have a `tsconfig.json` in the root project directory which lists all the files to include. However, I still need to specify references paths in the modules in order for the plugin to "see" the definitions in the other files. Note that these reference paths are not required to compile the project cleanly, since all the files are included in the compiler invocation. Is there a way around this?

**Comment by mhegazy** [comment]
you can either add /// <reference> tags in one of your sources to the .d.ts files for the modules you are importing, or you can just list them in the "files" section of your tsconfig ([see tsconfig documentation for more details](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#details))

**Comment by sccolbert** [comment]
As I mentioned in the post, they are listed in the tsconfig "files" section. So, this may be a bug.

**Comment by mhegazy** [comment]
can you provide more details, my simple project (a.ts, b.d.ts, and tsconfig.json) does not seem to repro the issue.

**Comment by sccolbert** [comment]
Here's a project hierarchy which reproduces the problem:

```
sample
  |- src
      |- moda
          thinga.ts
          thingb.ts
      |- modb
          thingc.ts
          thingd.ts
  tsconfig.json
```

Contents of files:

`thinga.ts`
```typescript
module sample.moda {

export
class ThingA {
  a: number;
}

}
```

`thingb.ts`
```typescript
module sample.moda {

export
class ThingB extends ThingA {
  b: number;
}

}
```


`thingc.ts`
```typescript
module sample.modb {

import ThingA = moda.ThingA;

export
class ThingC extends ThingA {
  c: number;
}

}
```


`thingd.ts`
```typescript
module sample.modb {

import ThingB = moda.ThingB;

export
class ThingD extends ThingB {
  d: number;
}

}
```


`tsconfig.json`
```json
{
    "compilerOptions": {
        "noImplicitAny": true,
    },
    "files": [
        "src/moda/thinga.ts",
        "src/moda/thingb.ts",
        "src/modb/thingc.ts",
        "src/modb/thingd.ts"
    ]
}
```

They exhibit the following problems for me:
- `ThingA` is undefined in the extends clause of `thingb.ts`
- `moda` is undefined in the imports clause of `thingc.ts`
- `moda` is undefined in the imports clause of `thingd.ts`

This project compiles fine when all paths in "files" are passed to the `tsc` command.

**Comment by steveluc** [comment]
Problem is "," after true.

**Comment by steveluc** [comment]
I think we should look into handling the trailing "," 
Here is a thread on it:
http://stackoverflow.com/questions/201782/can-you-use-a-trailing-comma-in-a-json-object

**Comment by steveluc** [comment]
Problem is in JSON.parse itself, so not a simple fix:

> JSON.parse('{ "compilerOptions": { "noImplicitAny": true, } }')
SyntaxError: Unexpected token }
    at Object.parse (native)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:132:27)
> JSON.parse('{ "compilerOptions": { "noImplicitAny": true } }')
{ compilerOptions: { noImplicitAny: true } }
>

**Comment by sccolbert** [comment]
Confirmed that the culprit is the trailing comma (stupid mistake on my part). However, the JSON parse failure doesn't seem to be indicated in the console (or anywhere I can see). Is it possible to to indicate to the user when the JSON is malformed?

**Comment by steveluc** [comment]
Agree there should be a message.

**Comment by mhegazy** [comment]
We also have the same issue for the compiler, linking for future references: https://github.com/Microsoft/TypeScript/issues/2627

**Comment by sccolbert** [comment]
@steveluc following up on my last post: I was running into another error in the `tsconfig.json` due to a misspelled filename. The server was failing to load the config because it couldn't find the misspelled file. This error is usually silently ignored, but after digging through `tsserver.js` I was able to find the (undocumented?) `TSS_LOG` env var which enables the server logging. That log indicated the failure to open. It would be really helpful if these server logs could be redirected to the sublime console by default.

**Comment by billti** [comment]
Thanks @sccolbert .  In general we need to work on error communication and resiliency.  We are planning to improve here.  The Sublime console I'd reserve for more troubleshooting/diagnostics. Something like this, which is an error in the TypeScript project itself, we need to figure out a way to surface in a more user-friendly manner.  Thanks for the feedback.
