### ISSUE TITLE
Right-click -> Go To definition goes to wrong file

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript-Sublime-Plugin#131]
I have a `tsconfig.json` which lists all files in the project. Pressing F12 on a symbol goes to the correct definition. Right clicking and choosing Goto Definition finds the symbol in the build output directories, the files of which are *not* in the `tsconfig.json`.

**Comment by zhengbli** [comment]
I didn't see the menu item called "goto definition" on my machine. What build / version of sublime are you running? Does the "goto definition" exist if you open non-ts files too?

**Comment by sccolbert** [comment]
I'm running 3083. This seems to be a feature of Sublime. I'd never noticed it before, so thought it was provided by this plugin. Sorry for the noise.

**Comment by DanielRosenwasser** [comment]
We should still override the behavior if possible. I remember seeing the context menu in Windows.

**Comment by steveluc** [comment]
We try not to override any existing Sublime menus and key bindings.  That's why we left this one the way it is.  @sccolbert thanks for the post; we do not consider it noise.  It is helpful to know when there is possible confusion.  We'll put a note about the context menu in the tips.

**Comment by steveluc** [comment]
Done in commit 0c8719e

**Comment by DanielRosenwasser** [comment]
Not sure if I'm big on this since the implementation is so broken for TypeScript, but I understand the rationale.
