### ISSUE TITLE
Plug-in is screwing up tab setting

### ISSUE THREAD

**Issue by bunnycode** [Microsoft/TypeScript-Sublime-Plugin#133]
This plugin is not respecting my setting to use tabs instead of spaces. I believe have every possible setting I can find across both Sublime and the TypeScript plugin to force the editor to always use tabs in every situation. Yet after installing this plugin, whenever I create a new file, or even rename an existing one, it reverts that file back to "Indent with spaces".

**Comment by steveluc** [comment]
This is a known issue.  We are testing a fix.

**Comment by DanielRosenwasser** [comment]
Duplicate of #129.
