### ISSUE TITLE
Support for linting using tslint?

### ISSUE THREAD

**Issue by goldcaddy77** [Microsoft/TypeScript-Sublime-Plugin#134]
Any chance you're going to support linting via [tslint](https://www.npmjs.com/package/tslint)?  I have this running in my build tools, but it would be great to have errors show up in my editor.

**Comment by DanielRosenwasser** [comment]
Unfortunately I don't really think this is in scope for us. Perhaps look into [SublimeLinter-contrib-tslint](https://github.com/lavrton/SublimeLinter-contrib-tslint).

**Comment by goldcaddy77** [comment]
:+1:
