### ISSUE TITLE
Tokenizer returns variable references as block

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#136]
Take the following peace of code:    

    var nodeproto: typeof NodeJS._debugger = require('_debugger');
    var readline: NodeJS.ReadLine = require('readline');
    var path: NodeJS.Path = require('path');
    var fs: typeof NodeJS.fs = require('fs');

    var rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        terminal: false,
    });

readline . createInterface is all returned as block token types.

**Comment by steveluc** [comment]
Are you talking about lexical colorization here?  Or the TypeScript scanner?

**Comment by dbaeumer** [comment]
Talking about lexical colorization. The sublime text made grammer.

**Comment by steveluc** [comment]
This looks OK when I paste it into a .ts file.  Could you say more about what is happening?

**Comment by zhengbli** [comment]
I think he means the scope of ``createInterface`` is of the scope ``meta.block.ts``. Is that right @dbaeumer ? Does that affect ``ctrl + r`` or anything?

**Comment by zhengbli** [comment]
@dbaeumer can you try the latest version and elaborate a little more what scope is expected? Thanks!
