### ISSUE TITLE
We do not squiggle error on hasOwnProperty

### ISSUE THREAD

**Issue by fionafung** [Microsoft/TypeScript-Sublime-Plugin#141]
Try to type in the following in Sublime Text 3, there are no squiggles, but we do have an error that hasOwnProperty requires a string and we are passing in a number.

```typescript
function hashMapTester(){
    var hashMap = {};
    var x: Object;
    var input = [1, 5, -1, 9, 8, 2, 2, 1, 9, 10, -5, -5];
    // Our map should have the following
    // -5 2
    // -1 1
    // 1 2
    // 2 2
    // 5 1
    // 8 1
    // 9 2
    for (var i = 0; i < input.length; i++) {
        if (hashMap.hasOwnProperty(i))  {
            hashMap[i]++;
        }
        else {
            hashMap[i] = 1;
        }
    }
    // Now print out the items in the hashmap
    for (var key in hashMap) {
        console.log(key + hashMap[key]);
    }
}
```

**Comment by zhengbli** [comment]
![capture](https://cloud.githubusercontent.com/assets/1171301/7103249/d8236878-e052-11e4-91f1-6de44089027c.PNG)
Do you mean the red lines under "i"? Seems I'm getting it on my machine. 
Which build of sublime are you on?

**Comment by fionafung** [comment]
Odd, I'm on sublime text 3

**Comment by billti** [comment]
I just tried on Windows & ST3 with both latest `master` bits and the `0.1.3` tag (which is the Package Control bits) and all looks fine to me also.  I see the red squiggle, and when I click also the error in the status bar.

Do you see any errors in the console/log?  Do you only have one TypeScript plugin running (i.e. not a prior cloned version and a Package Control version installed)?  FYI:  I just put info on disabling either version and configuring the logging on a [Dev notes](https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Dev-notes) page on the wiki if needed.

**Comment by fionafung** [comment]
I had noticed some other odd behaviors like quick info not showing up, so I then rebooted sublime and now can no longer repro...will keep an eye on and re-activate if I see the issue again - thanks!
