### ISSUE TITLE
Incorrect syntax highlighting with multiple overload signatures and ; is left out

### ISSUE THREAD

**Issue by bunnycode** [Microsoft/TypeScript-Sublime-Plugin#149]
![screen shot 2015-04-16 at 9 49 49 am](https://cloud.githubusercontent.com/assets/2212259/7182232/f835aecc-e41d-11e4-8af8-dea0d7cb6246.png)

Things get even more weird when:

![screen shot 2015-04-16 at 9 51 20 am](https://cloud.githubusercontent.com/assets/2212259/7182268/3b3b1216-e41e-11e4-84ba-bc15eea03b62.png)

(I realize this is fairly low priority ... as I just realized today that putting a semi-colon between overload signatures is supported and actually "proper" ... it's worth noting anyways.)

**Comment by blakeembrey** [comment]
Was search for "semicolon" and almost overlooked this issue. I figured I'd note that this also affects the navigation of `super+r`.

![image](https://cloud.githubusercontent.com/assets/1088987/7188933/a6e91c6e-e451-11e4-9371-cfbbe0f76caf.png)

**Comment by zhengbli** [comment]
I understand that the syntax highlighting isn't working properly for function overloads, however I'm a little confused with the issue @blakeembrey mentioned though. Aren't you supposed to put semicolon at the end of the line if it is a property declaration in a interface/class?

**Comment by blakeembrey** [comment]
@zhengbli I don't normally use semicolons and haven't run into any issues with TypeScript. I assume it's optional, like in most of JavaScript.

**Comment by zhengbli** [comment]
Fixed in PR #155
