### ISSUE TITLE
Arguments popup jumps to my second monitor when the autocomplete dropdown is also open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/TypeScript-Sublime-Plugin#153]
![untitled](https://cloud.githubusercontent.com/assets/323878/7192477/eefeaf70-e44a-11e4-8a1d-4f0e3d0d014b.png)

In the picture, the green area is my second monitor on the right.
When the two popups are too wide to stay side by side, the popup with the function description jumps to the second monitor. Do we have control over this, or is this a Sublime issue? I would be happier with it running off one monitor and on to the second.

**Comment by billti** [comment]
Interesting.... this must be a Sublime issue.  I actually set the location to be below the opening paren on the line (when args are on one line - as you have here), but Sublime shifts the popup over when it also displays the auto-complete list (if you set the COOPERATE_WITH_AUTO_COMPLETE flag - which is the only popup flag currently).

I've raised this in the Sublime issue tracker (https://github.com/SublimeTextIssues/Core/issues/805) to see if they plan on doing something better here (the API is very new), else not sure what we can do to make this better.
