### ISSUE TITLE
Syntax highlighting busted for parameters following a union type

### ISSUE THREAD

**Issue by bunnycode** [Microsoft/TypeScript-Sublime-Plugin#156]
Provided that the final element of the union contains only non-alpha numeric characters:
![screen shot 2015-04-21 at 9 43 33 pm](https://cloud.githubusercontent.com/assets/2212259/7265921/cf1b0284-e86f-11e4-8399-4ce9bc889fa7.png)

(i.e. replace `string|{}` with `string|(() => void)` and it works)

**Comment by zhengbli** [comment]
Fix PR #155
