### ISSUE TITLE
Plugin Doesn't Support Tab Size: 2

### ISSUE THREAD

**Issue by btesser** [Microsoft/TypeScript-Sublime-Plugin#158]
Occasionally (for example when adding a missing closing curly brace) code is automatically reformatted to 4 spaces.  My Sublime Text settings are 2 spaces, I have a tsfmt.json, and a .editorconfig-- all included below.  This is a huge pain!!
```
// tsfmt.json
{
  "indentSize": 2,
  "tabSize": 2,
  "newLineCharacter": "\r\n",
  "convertTabsToSpaces": true,
  "insertSpaceAfterCommaDelimiter": true,
  "insertSpaceAfterSemicolonInForStatements": true,
  "insertSpaceBeforeAndAfterBinaryOperators": true,
  "insertSpaceAfterKeywordsInControlFlowStatements": true,
  "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
  "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
  "placeOpenBraceOnNewLineForFunctions": false,
  "placeOpenBraceOnNewLineForControlBlocks": false
}
```

```
// .editorconfig
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true


[*]

# Change these settings to your own preference
indent_style = space
indent_size = 2
tab_width = 2

# We recommend you to keep these unchanged
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by lucaswoj** [comment]
+1

**Comment by NekR** [comment]
And disabling typescript_auto_indent/format does not help. Should restart Sublime after that?

**Comment by zhengbli** [comment]
Recent changes should fix the indentation issues. @btesser @lucaswoj @NekR could you give it a try to see if it works? Thanks!

**Comment by NekR** [comment]
@zhengbli as I understand it's only here in a repo, not in Package Control, so test plugin it should be installed from here, right?

**Comment by zhengbli** [comment]
@NekR You are right, for now to test please clone the repo to your sublime packges folder, as instructed in the [wiki page](https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Dev-notes). If we are sure the recent issues are sorted out, we will release a new version to Package Control very soon.

**Comment by aicioara** [comment]
@zhengbli how often do you do releases? When should we expect this to be in the Package Control repo?

**Comment by zhengbli** [comment]
@aicioara this release is taking longer than usual, but it can be expected early this week. Thanks for trying it out!

**Comment by NekR** [comment]
@zhengbli

So, is it in Package Control yet? Still has the same problem.

**Comment by zhengbli** [comment]
Yes the 1.4 was out last week. Could you do "list package" in your sublime and see what version your plugin is?

**Comment by NekR** [comment]
Oh, it was still 1.3. By some reason I thought Package Control packages has auto-update. Just updated it, thanks! Hope all is good.

**Comment by zhengbli** [comment]
Great. Please let us know if it fixes your problem :)

**Comment by aicioara** [comment]
Package Control only updates if you reset Sublime. Had the same issue.

**Comment by NekR** [comment]
Hmm.. I am not this is the bug, but it still have this problem:
![2015-05-19-1210-42](https://cloud.githubusercontent.com/assets/1189265/7699556/652b749a-fe21-11e4-9222-1970be2ad29f.gif)

My config is:
```json
{
	"Seti_ClosedFolder_dots": true,
	"Seti_sb_small_padding": true,
	"Seti_sb_tree_miny": true,
	"Seti_tabs_small": true,
	"caret_extra_width": 2,
	"color_scheme": "Packages/Seti_UI/Scheme/Seti_orig.tmTheme",
	"draw_white_space": "all",
	"fade_fold_buttons": false,
	"font_size": 12.0,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_active"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 0,
	"minimap_scroll_to_clicked_text": false,
	"rulers":
	[
		80,
		100,
		120
	],
	"save_on_focus_lost": true,
	"shift_tab_unindent": true,
	"spell_check": true,
	"tab_size": 2,
	"theme": "Seti.sublime-theme",
	"translate_tabs_to_spaces": true,
	"typescript_auto_format": false,
	"typescript_auto_indent": false,
	"word_wrap": true
}
```

**Comment by aicioara** [comment]
I have the same. It is annoying. It's probably for another ticket though.

**Comment by zhengbli** [comment]
@NekR if I understand correctly, the problem is that if you set syntax to typescript, indentation will be inserted for the closing parenthesis? Also, it would be easier for tracking if you can open another issue with the description, thanks.

**Comment by NekR** [comment]
@aicioara yep, a lot of annoyance.

@zhengbli Sure, sorry for spaming here. It's now https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/199
