### ISSUE TITLE
Bad initial indentation config

### ISSUE THREAD

**Issue by lucasmciruzzi** [Microsoft/TypeScript-Sublime-Plugin#159]
Every time I open a .ts file, the indendation is set to spaces instead of keeping my config of tabs. In my settings I have...

    "tab_size": 4,
    "translate_tabs_to_spaces": false,
    "typescript_auto_format": false

... and in my .editorconfig I have ...

    [*]
    charset = utf-8
    end_of_line = lf
    indent_style = tab
    insert_final_newline = true
    trim_trailing_whitespace = true

So the problem comes from the TypeScript plugin.

How can I avoid this overwrite behavior the plugin has over my indentation settings?

**Comment by zhengbli** [comment]
This is a known issue, similar to #147. This happens because we need to constantly sync the buffer content with the content on server, and sublime doesn't report changes when buffer content changes when it applies its algorithm to backspace. We are working on a workaround.

**Comment by buu700** [comment]
+1, this is a blocker.

I wanted to switch from Arctic TypeScript for some of the nicer features in this plugin, but that isn't really an option when it mangles my code.

**Comment by zhengbli** [comment]
Recent changes should fix the indentation issues. @buu700 @lucasmciruzzi could you give it a try?

**Comment by buu700** [comment]
Seems to work for me. Thanks a lot!

**Comment by lucasmciruzzi** [comment]
Seems to be working for me too. Thanks!
