### ISSUE TITLE
Syntax highlighting incorrect for type literals

### ISSUE THREAD

**Issue by rcchen** [Microsoft/TypeScript-Sublime-Plugin#162]
```typescript
protected _normalizeDatasets<A, B>(fromX: boolean): {a: A; b: B}[] {
  return Stacked.prototype._normalizeDatasets.call(this, fromX);
}
```

The typed object literal for the return typing "{a: A; b: B}" wrecks syntax highlighting for the rest of the page. I have tried putting a semicolon after the B as well and the syntax highlighting is still incorrect. Is this an issue with my syntax, or is there a bug with the plugin?

![image](https://cloud.githubusercontent.com/assets/1175041/7358175/a6c49598-ece8-11e4-8ec4-8a3c2d46975c.png)

**Comment by zhengbli** [comment]
Recent updates of the syntax definition files seem to address this issue. On my machine (latest on the master branch) your code shows up correctly:
![capture](https://cloud.githubusercontent.com/assets/1171301/7359290/8e0d2e44-ecf1-11e4-9acb-1e8b298f4335.PNG)
