### ISSUE TITLE
Split language definitions from plugin

### ISSUE THREAD

**Issue by laktak** [Microsoft/TypeScript-Sublime-Plugin#164]
Would it be possible to split the typescript language definition (tmLanguage, etc.) from the rest of the plugin? So it's basically what is was before you took over the `typescript` package?

I like the syntax highlighting but I prefer the Sublime way of code completion (where it allows me to complete anything instead of *intelli-sense*).

**Comment by mhegazy** [comment]
We need an option to disable statement completion.

**Comment by laktak** [comment]
Anything that disables all *background* operations would make me happy.

**Comment by zhengbli** [comment]
Should be fixed by #406 
Now there is an `enable_typescript_language_service` option, by default it was set to `true`, the user can set it to `false` to turn off the language service.
