### ISSUE TITLE
The autocompletion is sometimes outdated when typing fast 

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript-Sublime-Plugin#170]
The auto completion is sometimes outdated, especially in Sublime text 2.

For example, the following code
```ts
interface test{
    m: string;
}
var t: test;
t.m.
```
If I type fast, the wrong completion list is shown as follows:
![untitled](https://cloud.githubusercontent.com/assets/1171301/7423697/aaba7094-ef4c-11e4-9359-9c61707959ac.png)

**Comment by steveluc** [comment]
This is happening for me even with slow typing.  The completion list is the one from the previous completion request.

**Comment by steveluc** [comment]
Fixed in PR #171
