### ISSUE TITLE
Do not see arguments popup (Sublime 3 build 3084)

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/TypeScript-Sublime-Plugin#172]
Hi,

First, thanks a *lot* for you efforts on this plugin. Even in its preview state, it's immensely usable.

I though that the feature from subject might not have been developed, but I can see it in Ander's Build 2015 demo working just fine.

For the most part, plugin works great. But in case of method arguments, I never see them pop-up.

Here's a relevant snippet from the Sublime console:

```
request: {"arguments": {"file": "C:\\Projects\\js\\ui\\ts\\gui\\ViewConverter.ts", "line": 132, "offset": 26}, "command": "quickinfo", "seq": 353, "type": "request"}
response: {"seq":0,"type":"response","command":"quickinfo","request_seq":353,"success":true,"body":{"kind":"method","kindModifiers":"private,static","start":{"line":132,"offset":17},"end":{"line":132,"offset":26},"displayString":"(method) ViewConverter.needsOhlc(cs: CurveStyle): boolean","documentation":""}}

insert_snippet
request: {"arguments": {"file": "C:\\Projects\\js\\ui\\ts\\gui\\ViewConverter.ts", "tmpfile": "C:\\Utilities\\Sublime3\\Data\\Packages\\TypeScript\\.tmpbuf"}, "command": "reload", "seq": 354, "type": "request"}
time for reload 0.007998
response: {"seq":0,"type":"response","command":"reload","request_seq":354,"success":true}

request: {"arguments": {"files": ["C:\\Projects\\js\\ui\\ts\\gui\\ViewConverter.ts"], "delay": 500}, "command": "geterr", "seq": 355, "type": "request"}
event: {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"C:/Projects/js/ui/ts/gui/ViewConverter.ts","diagnostics":[]}}

event: {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"C:/Projects/js/ui/ts/gui/ViewConverter.ts","diagnostics":[{"start":{"line":132,"offset":12},"end":{"line":132,"offset":28},"text":"Supplied parameters do not match any signature of call target."}]}}

```

I was about to call the static method called `needsOhlc` from another static method of the `ViewConverter` class.

The "quickinfo" giving back correct signature was at the moment of autocompleting the method name, the error happens as soon as I press opening "(". It's the same error all the time, regardless of method kind (static or not). I also tried removing a theme I use, even removing _all custom settings_ I have *and* switching to Sublime 2 - same thing.

I apologize if this is a known issue (I could not find a similar bug) but it's a major pain point which forced me to temporarily switch to  Visual Studio Code which is servicable, but suffers from same issues as Atom (it's built on Atom shell after all).

Please let me know if I can help debug this in any way.

Btw, do you plan a new release now that 1.5.0-beta is out?

Thanks again for you work on this plugin!

**Comment by ddotlic** [comment]
I found an issue which seems to be relevant, the screen shot accurately depicts a situation I'm in.

As soon as Ander's video goes online, I'll take a screen grab and post it here :smile:

**Comment by zhengbli** [comment]
Hi, thanks for the feedback! The tooltip feature that Anders used is in master branch, but not in the released version (the one in sublime package control). We will release a new version very soon, which will include the tooltip feature and some other features (navigate-to, better syntax highlighting etc.) The new release will also come with TS 1.5 beta.

Regarding your error, I'm not sure I follow what exactly is the problem. What is the exact error message?

**Comment by ddotlic** [comment]
Hey @zhengbli , thanks for a quick response!

There's no error apart from the fact that method signature "tooltips" don't show up, I simply tried as a fellow developer to provide you with some more context (thus console output which is of course hidden by default).

Looking forward to the new version... now that I've used Code for a few days, the only thing I might be missing going back to Sublime would be the "peek" (Alt+F12) functionality, but that's far from deal breaker.

I will definitely appreciate not having to press "Ctrl+F12" just because the damn shell (of Code) is built on Chrome and F12 opens up inspector :wink: 

Btw, what is the navigate-to feature you speak of? What's gonna be (briefly) better with the syntax highlighting? As-is, syntax highlight is already better than Code's, kudos.

**Comment by zhengbli** [comment]
The "peek" feature is kinda hard to implement given sublime's limited APIs for now. However sublime 3 is still under active development, so hopefully more APIs will be open later. The "Navigate to" feature is similar to sublime's own "go to symbol", but is cross files and based on semantic information instead of only syntactic information. For syntax highlighting we have received some bug reports after last release, so the new one will be more robust.

**Comment by ddotlic** [comment]
> The "peek" feature is kinda hard to implement given sublime's limited APIs for now.

Yeah, I'm not holding my breath for that one... luckily due to the way one can quickly navigate in Sublime it's not a big issue. It's cooler as a demo than it is practical.

Thanks for additional info and for closing the item.
