### ISSUE TITLE
'super' not highlighted

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#174]
![image](https://cloud.githubusercontent.com/assets/972891/7438370/0555d040-f018-11e4-91c4-1f3426523642.png)

In general a bunch of keywords are still not accounted for such as 'from', 'as', etc.'

**Comment by zhengbli** [comment]
Is there a good place that lists all the keywords in TS?

**Comment by DanielRosenwasser** [comment]
A ***good*** place? No, but I wrote a pretty offhand one  here: https://github.com/Microsoft/TypeScript/issues/2536#issuecomment-87194347

**Comment by zhengbli** [comment]
Thanks that looks pretty good to me. Will incorporate

**Comment by zhengbli** [comment]
Fixed in #173

**Comment by zspitz** [comment]
@zhengbli @DanielRosenwasser  Could you take a look at Microsoft/TypeScript-Handbook#344 and see if I've missed anything?
