### ISSUE TITLE
Autocompile options?

### ISSUE THREAD

**Issue by Eisenspalter** [Microsoft/TypeScript-Sublime-Plugin#175]
The plugin does not compile on the fly on my system, what I have expected. Is that right? So it would be great to have an autocompile option.

**Comment by mhegazy** [comment]
The plugin currentellu does not support compiling on save; You can run the compiler with --watch in a separate process to achieve the same effect. I would recommend using tsconfig.json to get a consistent experience in the plugin and on the command line.

**Comment by Eisenspalter** [comment]
Thanks that will work for me.
