### ISSUE TITLE
Can't type question mark in RegExp matching group

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript-Sublime-Plugin#177]
I'm running the latest version on `master` and found I can't press the question mark after opening a matching group in a regular expression. For example:

```ts
/(
```

Typing that should be enough to show that the next character won't accept a question mark. It's only directly after the bracket, I can type a question mark elsewhere.

**Comment by billti** [comment]
This is likely due to my code to treat this as a trigger for argument help.  I can take a look at fixing this.

**Comment by billti** [comment]
Fixed with 38f74ce14456448ff
