### ISSUE TITLE
mouse-over summary ?

### ISSUE THREAD

**Issue by aminroosta** [Microsoft/TypeScript-Sublime-Plugin#181]
Show **`QuickInfoDocumentation`** popup when mouse is over a function or variable.
Visual studio implements this feature.

I don't know if it's is **possible** or not, from what i have seen in sublime documentation 
that might not be supported (or at least not documented).

**Comment by steveluc** [comment]
Right now, Sublime does not support hover events or contextual mouse click events.

**Comment by billti** [comment]
Per @steveluc , this is a Sublime limitation, and not something we can change.
