### ISSUE TITLE
No highlighting for debugger statement

### ISSUE THREAD

**Issue by bunnycode** [Microsoft/TypeScript-Sublime-Plugin#184]
I don't feel like doing a PR for this so to make it easy:

TypeScript.tmLanguage:196
```
<string>\b(break|catch|continue|debugger|declare|do|else|finally|for|if|return|switch|throw|try|while|with|super)\b</string>
```

**Comment by billti** [comment]
Thanks @bunnycode .  Fixed with https://github.com/Microsoft/TypeScript-Sublime-Plugin/commit/5b5d6d1d016df4fab7daee6b734093d90a0e9b62
