### ISSUE TITLE
Changes to tsconfig.json are not picked up until I restart Sublime

### ISSUE THREAD

**Issue by billti** [Microsoft/TypeScript-Sublime-Plugin#193]
If I have an existing tsconfig.json and change a setting, I need to restart Sublime before that setting takes effect.

For example, if I have "target": "es3", and write a getter, I get an error that getters are only supported in es5 (as expected).  If I modify my tsconfig.json to be "target": "es5", then the error persists until I reopen the project.

We should detect changes to tsconfig.json and reload the project context.

**Comment by zhengbli** [comment]
Confirmed that this is a tsserver issue, there is no file watcher for the tsconfig.json. Will send a PR on their side to add this.

**Comment by zhengbli** [comment]
Should be fixed by changes in v1.6 tsserver
