### ISSUE TITLE
typescript_auto_format breaks editorconfig's tab preference

### ISSUE THREAD

**Issue by jamiecounsell** [Microsoft/TypeScript-Sublime-Plugin#195]
When `typescript_auto_format` is enabled, it appears that certain operations will cause indentation to be replaced with tabs, even when the .editorconfig file specifies the use of tabs. The easiest way to replicate it is to enter a new line that is indented by the auto-format, then paste a variable from the same file. This took me a while to figure out, I thought it was .editorconfig not working, but it only occurs with .ts files.

**Comment by zhengbli** [comment]
This was an known issue before v1.4 release, but now it should work with sublime text's tab settings. 

And I don't quite understand the repro procedure you mentioned. Do you mean the following:
![195](https://cloud.githubusercontent.com/assets/1171301/7806035/bb538268-0330-11e5-9aa0-078088943d01.gif)
(Here the ``typescript_auto_format`` is enabled, and the ``indent using spaces`` sublime view setting  is set to true).
