### ISSUE TITLE
'Goto Definition' should be 'Go To Definition'

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript-Sublime-Plugin#196]
![image](https://cloud.githubusercontent.com/assets/7121557/7620078/2b359756-f972-11e4-8905-a12ed3e83713.png)

Goto is not one word in this context.

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by danquirk** [comment]
Maybe this isn't ours? Can we exclude it somehow?

**Comment by zhengbli** [comment]
I couldn't find instructions on how to hide or remove the item. It resides in (Packages folder)/Default/Context.sublime-menu.
