### ISSUE TITLE
Definition popup does not change its position when typing numbers in object literal

### ISSUE THREAD

**Issue by NekR** [Microsoft/TypeScript-Sublime-Plugin#198]
See gif:

![2015-05-19-1236-03](https://cloud.githubusercontent.com/assets/1189265/7699946/064a2aa4-fe24-11e4-831a-b1dccda99e40.gif)

**Comment by billti** [comment]
Hmmm, looks like maybe https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/152 wasn't merged before we published the package.  Sorry about that.  Will take a look and get this fixed up.

**Comment by NekR** [comment]
Thanks!
