### ISSUE TITLE
Auto-completion of statement by pressing Tab is not aware of surrounding code

### ISSUE THREAD

**Issue by v95** [Microsoft/TypeScript-Sublime-Plugin#201]
If I am typing `console.l` and hit the `tab` button (once the auto-complete dropdown appears), instead of simply adding `og();`, the line becomes the following:

`console.console.log();`

I am using Sublime Text 2 on Win10. Please let me know if more information is required.

**Comment by zhengbli** [comment]
I don't seem to repro problem on Sublime Text 2 with v1.4 of the plugin (from package control):
![capture](https://cloud.githubusercontent.com/assets/1171301/7781197/099993c0-009f-11e5-957f-3f0f3c7451c8.gif)

Notice a recent refactor change (#197) broke the support for sublime text 2 (sorry about that). If you want to install from the git repo, please wait after the fix (#205) to merge.

**Comment by zhengbli** [comment]
The same with #211 
The problem is sometimes snippet is inserted instead of the completion information. Working on a fix.

**Comment by v95** [comment]
Thanks @zhengbli!
