### ISSUE TITLE
Autocomplete fills in complete text even if a part of it is already written.

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/TypeScript-Sublime-Plugin#211]
The autocomplete feature present in the TypeScript plugin automatically puts in the complete text that the user actually wants to write, even if a part of the text is already written, a small example is as follows

### Steps to Reproduce

```ts
export function addPin(userid: string, boardid: string, imageUri: string, link: string, caption: string, callback: (user: User) => void) {
    db.collection('images', function(error, images_collection) {
        if(error) { console.error(error); return; }
        images_collection.insert({
            user: userid,
            caption: caption,
            imageUri: imageUri,
            link: link,
            board: boardid,
            comments: []
        }, function(error, image) {
            console.log(image);
            db.collection('users', function(error, users) {
                if(error) { console.error(error); return; }
                users.update(
                    {_id: userid, "boards.title": boardid}, 
                    {"$push": {"boards.$.images": image[0]._id}},
                    function(error, user) {
                        callback(user);
                    }
                );
            })
        })
    })
}

```
1. Take the following code example
2. Try to add a `console.log()`
3. As soon as the user types the word `console.l` the <log()> appears in the dropdown autocomplete options. Hitting enter results in `console.console.log()` rather than `console.log()`
4. Simply using `log()` and hitting enter on the autocomplete options results in `console.log()`

### Expected Results

The part of the string that is already written shouldn't be repeated again in the auto completion option just like how it happens in autocomplete options for other languages like JavaScript where the above similar steps just result in `console.log()` than a `console.console.log()`

### Actual Results

`console.console.log()` instead of `console.log()`

**Comment by zhengbli** [comment]
Reproduced with sublime 2 on windows. Investigating

**Comment by zhengbli** [comment]
It looks like the inserted ``console.log`` is actually a snippet instead of the normal auto completion. But I have very inconsistent behavior on my machine, sometimes the snippet shows up in the completion list and sometimes not.
