### ISSUE TITLE
} clash with Vintageous

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript-Sublime-Plugin#212]
If you install both the Vintageous plugin and this one, go to normal mode in Vintangeous and type }, you should jump to the next paragraph. Instead, a } is inserted. 

I believe this is because you are assuming here https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/commands/format.py#L18 that you can safely insert the } key if the user types it. In the case of Vintageous, that's not true (unless Vintageous is in insert mode). 

The same thing is true with the ; key.

**Comment by zhengbli** [comment]
This is being fixed in PR #209.

**Comment by johnfn** [comment]
Awesome! Thanks for maintaining such a great plugin! :)

**Comment by zhengbli** [comment]
@johnfn this should be fixed in master. Can you give it a try?
