### ISSUE TITLE
Performance issues on Angular code base

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript-Sublime-Plugin#216]
I'm using Sublime Text 3, build 3083, on the Angular code base, with the TypeScript plugin installed via git at revision 2c19761, tried with node v0.10.38 and v0.12.4 with similar results.

At its worst, moving the cursor stalls the UI for multiple seconds and most TypeScript commands fail (go to symbol, rename, etc). I see "queue timeout" printed in the console. Restarting Sublime helps, but moving the cursor onto a symbol still stalls the UI for a noticeable amount of time; keeping the down arrow pressed and scrolling through the file shows it's very slow and janky.

Steps to reproduce:
* install Sublime Text 3 build 3083
* install TypeScript plugin at 2c19761
* Check out https://github.com/angular/angular (about 60k SLOC)
* open (e.g.) element_injector.ts, navigate around in the file

Apart from the general speed, all TypeScript operations appear to run synchronous on the UI thread, which might cause these issues.

**Comment by zhengbli** [comment]
Just to clarify, when you say "moving the cursor onto a symbol", do you mean just click on the symbol, or do you mean using the "navigate to symbol" command? 
Some commands are kept synchronous due to comparability consideration with sublime 2, which may indeed affect the performance.  However, the expensive ones like auto_completion and get_err are done asynchronous in Sublime 3 already.

**Comment by mprobst** [comment]
Just clicking on it or navigating by keyboard.

Zhengbo Li <notifications@github.com> schrieb am Fr., 5. Juni 2015 19:17:

**Comment by zhengbli** [comment]
Does the following recording seem to match your experience? I tried the procedure on my laptop:
![capture](https://cloud.githubusercontent.com/assets/1171301/8017889/b6ac6e4c-0bb8-11e5-8c92-93fce6fe043f.gif)
I did notice some lag, but no as bad. I wonder there might be something else going wrong. Could you help me with a log file? To get the log file:
1. go to the plugin folder and close sublime
2. open 'typescript/libs/global_vars', change ``LOG_FILE_LEVEL`` to ``logging.DEBUG``
3. open sublime and reproduce the problem.
4. find the 'TS.log' file in the 'typescript' folder, and post the content.

Thanks!

**Comment by mprobst** [comment]
It's hard to tell from the gif, but I think the lag is quite a bit more severe on my machine. Interestingly when using Visual Studio Code, there's no lag while navigating the file (I believe because it is async), but when triggering completions, they do take over a second to appear, sometimes three.

Here's a gist of the log: https://gist.github.com/mprobst/b88436cd0d808e45f64d

**Comment by zhengbli** [comment]
From the log I do see a lot of "quickinfo" request (which is to update the status line) taking up 200~300 ms. It would be better to change that to asynchronous, or provide an option to turn it off. I'll experiment a bit.

**Comment by zhengbli** [comment]
@mprobst can you give a shot of https://github.com/zhengbli/TypeScript-Sublime-Plugin/tree/asyncQuickInfo ?

**Comment by mprobst** [comment]
@zhengbli indeed, that's a huge improvement - no more blocking on navigation.

**Comment by zhengbli** [comment]
Awesome!
