### ISSUE TITLE
Request: Implement official plugin for Atom editor

### ISSUE THREAD

**Issue by muhasturk** [Microsoft/TypeScript-Sublime-Plugin#218]
There are some typescript pugins for Atom out there. Offical and fast plugin would be awesome.

**Comment by DanielRosenwasser** [comment]
What's wrong with [atom-typescript](https://github.com/TypeStrong/atom-typescript)? @basarat seems to be doing great things with it from what I see.

**Comment by muhasturk** [comment]
It increases Atom's opening time 
![](http://i.imgur.com/iqhqeWO.png)

**Comment by DanielRosenwasser** [comment]
That qualm doesn't warrant a dedication of resources to compete with an otherwise good project. Instead of duplicating effort, it would be better to contribute to atom-typescript.
