### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by kuon** [Microsoft/TypeScript-Sublime-Plugin#220]
When I use autoformat, the following block get the following indentation:

    toolsElement = h.div({ className: "row-tools" },
        h.button({
            className: "add-node",
            onClick: () => DataController.createNode(this.props.parentId)
        }, "Create new node")
        );

While I expect (Last line should be to the left):

    toolsElement = h.div({ className: "row-tools" },
        h.button({
            className: "add-node",
            onClick: () => DataController.createNode(this.props.parentId)
        }, "Create new node")
    );

Another example:

    return (
        h.div({
            className: "view-node-row",
            style: {
                width: width,
                height: rowHeight
            }
        },
            backgroundElement,
            centerElement,
            toolsElement,
            h.div({ className: "nodes" }, items)
            )
        );

While I expect:

    return (
        h.div({
            className: "view-node-row",
            style: {
                width: width,
                height: rowHeight
            }
        },
        backgroundElement,
        centerElement,
        toolsElement,
        h.div({ className: "nodes" }, items)
        )
    );

PS: I'm doing react without JSX because TypeScript > JSX, but proper indentation is really crucial to readability.

**Comment by zhengbli** [comment]
@mhegazy could you take a look at the formatting issue? Is that a known problem?

**Comment by mhegazy** [comment]
I have ported this to the TS repo.
