### ISSUE TITLE
Unresponsive plugin on_activated callback

### ISSUE THREAD

**Issue by sudheesh001** [Microsoft/TypeScript-Sublime-Plugin#223]
Leaving a typescript file open in SublimeText for a long time and then opening it up all of a sudden initially shows it like a text file with no syntax highlight, then throws the following error and then highlights itself.

![typescript slow response](https://cloud.githubusercontent.com/assets/4545925/8083394/d45d398e-0fa1-11e5-93b8-04510a66fea1.PNG)

**Comment by zhengbli** [comment]
That is a known issue, same as #13. As sublime text 2 loads everything during import time, we don't quite have a good solution yet. Just out of curiosity, is there any special reason why you don't use sublime text 3 and stick to 2?

**Comment by sudheesh001** [comment]
@zhengbli There's no specific reason, I never really found a reason to move from ST2 to ST3 because ST2 managed most of the functionality I needed, but now since you mention it, I think i'll make the jump. :smile:
