### ISSUE TITLE
Incorrect coloring if code is sytactically incorrect

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#225]
class Person {

interface I {

}

Observe: interface is not colored as a keyword

**Comment by zhengbli** [comment]
Yeah sublime's syntax coloring module is entirely based on regular expression, so incorrect syntax gives it incorrect scope, and there is mot much we can do about it. I consider the behavior as low impact.

**Comment by billti** [comment]
Note also that 'interface' is a valid member name inside a class declaration, so it shouldn't be colorized as a keyword in that location anyway.
