### ISSUE TITLE
Comment not colored correctly

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#226]
Some examples:
```
var x = new /*asdasd*/ String();

interface /*asdasd*/ A {
   a?:string;
}
```
From looking at the grammer I think there are more places where comments aren't colored correctly

**Comment by hoanhtien** [comment]
The colorization issue in `var x = new /*asdasd*/ String();` is fixed in https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/238.

**Comment by hoanhtien** [comment]
Updated #238 to fix `interface /*asdasd*/ A` as well.
