### ISSUE TITLE
Strings not colored corretly if they occur at syntactically incorrect positions

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#227]
```
var x 'Dirk';

class B {
 	"nnn"
}
```

**Comment by zhengbli** [comment]
This is similar to #225. Basically for now our priority is to correct syntax highlighting for syntactically correct content.

**Comment by billti** [comment]
Actually this should be a pretty easy fix and seems useful. Rules to recognize comments and string literals should be early in the syntax and always be highlighted as such in most cases.
