### ISSUE TITLE
Incorrect Predictions

### ISSUE THREAD

**Issue by lukeed** [Microsoft/TypeScript-Sublime-Plugin#230]
Using a basic example, the TS plugin doesn't given options based on the object. Instead, it seems to just adopt the default Sublime behavior of showing the longest strings on the page.

![screen shot 2015-06-12 at 12 50 31 pm](https://cloud.githubusercontent.com/assets/5855893/8138740/6d69a84a-1102-11e5-8e3a-c86508b0c345.png)

**Comment by zhengbli** [comment]
This is probably because the server is not up. What is the console output when you start sublime? Also, which version of the plugin are you using?

**Comment by lukeed** [comment]
@zhengbli Everything was up to date. Just discovered solution:

File wasn't saved / had no name... ergo the TS server wasn't doing anything with the file.

So, it's probably impossible mechanically, but a nice feature request would be to start evaluating ANY open TS files, not necessarily just the saved ones.

**Comment by zhengbli** [comment]
Yes the server wouldn't do anything if the file is not saved on disk. It is indeed possible to spin it up for an unsaved buffer although it may not be very high priority right now. I'll open a feature request for it for future revisit. Thanks!

**Comment by zhengbli** [comment]
Closing this one, as a new feature request #232 is opened.

**Comment by lukeed** [comment]
Thanks much
