### ISSUE TITLE
Cannot Paste (OSX)

### ISSUE THREAD

**Issue by lukeed** [Microsoft/TypeScript-Sublime-Plugin#231]
Attempted to paste in a small chunk of code (6 lines) via `command + V`

I'm aware the plugin listens in on this key command to run `Paste and Format` but after ~10 minutes, nothing occurs.

**Comment by zhengbli** [comment]
What version of your Sublime Text and what version is your plugin? Do you have any console output, especially exceptions?

**Comment by lukeed** [comment]
Closed -- was using unnamed file. See #230
