### ISSUE TITLE
lib.d.ts is out of date

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript-Sublime-Plugin#237]
Looks like the lib.d.ts in tsserver is out-of-date.  There are some updates like:

getContext(contextId: "2d"): CanvasRenderingContext2D; 
getContext(contextId: "experimental-webgl"): WebGLRenderingContext; 

Can we pull a fresh lib.d.ts?

**Comment by zhengbli** [comment]
Will be updated with the 1.5 release branch soon

**Comment by zhengbli** [comment]
Fixed in #247
