### ISSUE TITLE
No way to trigger signature help

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#240]
The "overloads panel" is a thing, and so is "quick info", but there doesn't appear to be a way to trigger signature help manually without adding a set of parens.

Signature help as it exists is way more helpful to me than the overloads panel, and there's also no way to get signature help when typing out a tagged template.

We may also consider subsuming the overloads panel with the signature help popover.

**Comment by zhengbli** [comment]
It is added in master at e1bcaaf0980d8e09aa2ec9b9ae073b343e97f520. Try search for the command: "TypeScript: SignatureInfo"
