### ISSUE TITLE
Cannot edit from beginning of NavigateTo input field

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#249]
![navigatetotyping](https://cloud.githubusercontent.com/assets/972891/8312755/78a75916-1993-11e5-8e4b-da3da3e9d00f.gif)

**Comment by hoanhtien** [comment]
Quick panel does not support dynamically reloading the item list. Here we did a hack by closing and re-opening quick panel whenever the input field is modified. I don't see a way to fix this bug for now.

**Comment by DanielRosenwasser** [comment]
Did we ever file a request with [SublimeTextIssues](https://github.com/SublimeTextIssues/) to see if that could be supported?

**Comment by zhengbli** [comment]
Filed https://github.com/SublimeTextIssues/Core/issues/908. Thanks for the suggestion!

**Comment by DanielRosenwasser** [comment]
Awesome, thanks @zhengbli.
