### ISSUE TITLE
Auto-formatting in version 1.5 breaks undo history

### ISSUE THREAD

**Issue by chbrown** [Microsoft/TypeScript-Sublime-Plugin#257]
The "Typescript Format On Key" action prevents undoing past the point at which the action was applied.

To replicate:

1. Ensure that you have the latest version of the TypeScript-Sublime-Plugin installed in Sublime Text
2. Create a new file and save as a file with a `.ts` extension so that the syntax gets set to TypeScript
3. Enter the following code: `function log(entry: {message: string`
4. Type `}`
5. Press Command + Z to undo
6. Nothing happens, because the action is re-applied as soon as it is undone.

I am running Sublime Text 3, Stable Channel, Build 3083.

**Comment by itajaja** [comment]
confirmed. Windows machine
