### ISSUE TITLE
Plugin crash from call to 'set_timeout'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#260]
Here's part of the debug info from my console:

```
SyntaxKind. includes a dot but not req mem
insert
indent
insert_snippet
insert_snippet
insert
insert_snippet
insert_snippet
Traceback (most recent call last):
  File "C:\Users\Daniel\AppData\Roaming\Sublime Text 3\Packages\TypeScript\typescript\libs\work_scheduler.py", line 151, in on_scheduled
    sublime.set_timeout(50, on_scheduled)
  File "C:\Program Files (x86)\Sublime Text 3\sublime.py", line 175, in set_timeout
    sublime_api.set_timeout(f, timeout_ms)
TypeError: an integer is required
```

**Comment by zhengbli** [comment]
Can you provide the context?

**Comment by DanielRosenwasser** [comment]
Unfortunately I don't know; I was just typing and by the time I realized quick info wasn't working, I wasn't able to recall any steps.

**Comment by DanielRosenwasser** [comment]
@zhengbli it looks like it's just a matter of the arguments being mixed up in `work_scheduler.py`:

Sublime's set_timeout is declared as

```Python
def set_timeout(f, timeout_ms = 0):
```

The way it's invoked is

```Python
sublime.set_timeout(50, on_scheduled)
```

**Comment by zhengbli** [comment]
Yeah I just realized that too. Will fix soon, thanks!

**Comment by zhengbli** [comment]
Fixed along with the other bug fix in commit 4fcf4f5aaaf8b80df7e664bd168f167da683b360

**Comment by DanielRosenwasser** [comment]
Awesome - in the future let's refer to pull requests (i.e. here we'd just say the fix is in #259), and also avoid conflating bug fixes, even if the changes are small.

**Comment by zhengbli** [comment]
Sure, thanks for the tip!

**Comment by hoanhtien** [comment]
:+1:
