### ISSUE TITLE
Something wrong with TypeScript syntax highlights

### ISSUE THREAD

**Issue by NekR** [Microsoft/TypeScript-Sublime-Plugin#262]
This is how it looks now, once (recently) I made upgrade to latest version in Package Control.

![ts](https://cloud.githubusercontent.com/assets/1189265/8380243/5cdd1a58-1c2d-11e5-939d-5f7001b69b3b.png)
![ts2](https://cloud.githubusercontent.com/assets/1189265/8380244/5cdd86c8-1c2d-11e5-9cef-f900015e04b1.png)
![ts3](https://cloud.githubusercontent.com/assets/1189265/8380245/5ce02f54-1c2d-11e5-813b-322b002c44f7.png)

**Comment by zhengbli** [comment]
Is the ``getLevelTiles`` rendered correctly in your theme? If so, can you show us what is the content of the function? I know template strings (backtick) may cause issues here

**Comment by hoanhtien** [comment]
Confirmed this repros when installing via Package Control.

**Comment by NekR** [comment]
> Is the getLevelTiles rendered correctly in your theme?

Nope. It seems that problem is in ```for``` loops, because problem always occurs after them. Here is 2 screenshots, one with my current theme and one with popular Monokai theme:
![ts](https://cloud.githubusercontent.com/assets/1189265/8387271/e4e8a160-1c5f-11e5-802d-90d3542b9538.png)
![ts2](https://cloud.githubusercontent.com/assets/1189265/8387272/e4eb3c2c-1c5f-11e5-9822-adefa57fdcf4.png)

**Comment by hoanhtien** [comment]
@NekR We just released v0.1.6 that includes the fix for this bug. Can you give it a try?

**Comment by NekR** [comment]
@hoanhtien of course :-)

Just tried, all seems good at a first glance :+1: Thanks for the update!
