### ISSUE TITLE
Consider regression testing for the tmLanguage file

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#263]
As certain issues keep coming up with the grammar file, there is no way to confirm a fix doesn't break other code apart from manual testing and hearing back from users. It would be helpful to take measures to prevent this.

**Comment by hoanhtien** [comment]
+1 for this feature.

Instructions on how to make a syntax test file can be found here: https://www.sublimetext.com/docs/3/syntax.html.

**Comment by zhengbli** [comment]
The link seems to only work for ``.sublime-syntax`` files, not for ``tmLanguage`` files, which is not compatible with Sublime 2. I can build a simple plugin for the testing, which outputs the scope of specified points in test case files. Then we check the baseline to validate.

**Comment by hoanhtien** [comment]
+1. 

I original thought a command (hidden from user) in our current plugin should do it. But making a separate plugin would benefit other Sublime developers who also need to test their tmLanguage.

**Comment by DanielRosenwasser** [comment]
There's http://blog.macromates.com/2010/grammar-test-mate/ as well. If we had a TextMate grammar engine, we could just dump the scopes and test baselines like in the compiler.

Pinging @steveluc on this.

**Comment by zhengbli** [comment]
I wrote a simple plugin for scope output: https://github.com/zhengbli/SyntaxTests, and I'm exploring the feasibility to make it as part of Travis CI. Currently I just put the issues that people have encountered in the test cases.

**Comment by zhengbli** [comment]
A test repo is already set up for regression testing. Close this issue.
