### ISSUE TITLE
Multiple else (or else if) statements disable colorization for the rest of the document

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/TypeScript-Sublime-Plugin#271]
Hi,

as title says, from what I can see this kind of code will essentially stop colorizing the rest of the document

```
if(...) {
}
else if(..) {
}
else { // or else if, doesn't matter
}
```

With only one `else` things are fine, for my project only two or more `else [if]` blocks will case the colorization to vanish for the lines following the closing brace of the last `else [if]`.

It's not a big deal, but it is a bit annoying :wink:

**Comment by ddotlic** [comment]
A bit more info, I've now modified one of the two files where I can observe this and the coloring started working... in the second file though it's still not working, so there might be something else at play besides from multiple `else [if]` statements, I'm trying to see what.

**Comment by hoanhtien** [comment]
@ddotlic Is there a less-than sign i.e. `<` in your code? Might be related to https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/265.

**Comment by hoanhtien** [comment]
@ddotlic We just release v0.1.6 that includes the fix for bug #265. Can you help giving it a try?

**Comment by ddotlic** [comment]
0.1.6 fixes this issue, thanks!

**Comment by arnaud97** [comment]
I have a similar issue.I'm trying to place some elseif statement in my ts code but it seems not working
