### ISSUE TITLE
indentation defaults to 4 spaces

### ISSUE THREAD

**Issue by itajaja** [Microsoft/TypeScript-Sublime-Plugin#272]
no matter how the indentaion is set in sublime text, ctrl-T-F always indents by 4 spaces. Is there an option to change that?

**Comment by itajaja** [comment]
I added `"indent_size": 2` to `Typescript.sublime-settings`, but it seems it doesn't change anything.,,

**Comment by hoanhtien** [comment]
@itajaja You can use the following settings:
```
"translate_tabs_to_spaces": true,
"tab_size": 4
```

**Comment by itajaja** [comment]
it still uses 4 spaces, both with `tab_size` and `indent_size` set to 2... I'm on a windows machine. This are my current settings

````js
{
    "auto_complete_triggers" : [ {"selector": "source.ts", "characters": "."} ],
    "use_tab_stops": false,
    "translate_tabs_to_spaces": true,
    "tab_size": 2,
    "indent_size": 2
}
````

**Comment by zhengbli** [comment]
Can you try put the settings in your "User setting", like shown below:
![untitled](https://cloud.githubusercontent.com/assets/1171301/8530009/3ac7837e-23d3-11e5-98e8-3d88986d6965.png)

Also, notice that Sublime gives each view its own setting, which could override your global setting. To check that see the left bottom of your editor, and you should see something like "Spaces: 4". Make sure to change that to "Spaces: 2" too.

**Comment by itajaja** [comment]
no wait. I was talking about the Typescript preferences, not the Sublime preferences. Sublime preferences are set all right, the number in the lower right corner shows 2.

![image](https://cloud.githubusercontent.com/assets/697647/8530119/4b45d7ae-241f-11e5-9788-c4b5e2db9b15.png)

**Comment by itajaja** [comment]
it solved, and I am not sure how. I restarted it a couple of times. I think the fact that I added `"indent_size": 2,` to the Sublime settings solved the issue. it's strange though, since all my other ST plugins worked with 2 spaces with no problem... Closing this, thanks for the support! :+1:
