### ISSUE TITLE
export keyword not colored consitently

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#274]
See image

![capture](https://cloud.githubusercontent.com/assets/1931590/8520498/efe651a2-23da-11e5-91c0-dbb5d59807a8.png)

**Comment by hoanhtien** [comment]
@dbaeumer This actually works fine on Sublime Text. Can you confirm it is not a problem of VSCode (looking at the screenshot I think you are using VSCode)?

**Comment by hoanhtien** [comment]
I am able to config VSCode to use the latest grammar. The colorization looks good now :grinning:

![image](https://cloud.githubusercontent.com/assets/1707813/8885571/d4920312-3215-11e5-9bf5-29605757ccbd.png)
