### ISSUE TITLE
Finishing a line with semicolon deletes letters from the next line

### ISSUE THREAD

**Issue by qbolec** [Microsoft/TypeScript-Sublime-Plugin#277]
I try hard to use 2 spaces indentation everywhere.
```
    "tab_size": 2,
    "translate_tabs_to_spaces": true,
    "use_tab_stops": true,
```
TypeScript plugin fights against it, and while this is a hussle, I am ok with that.
But recently I observed that from time to time (maybe it's a timing issue?) several letters from next line are eaten.
In the attached screenshot I've tried to type in a line between lines 127 and 129.
I put my cursor at the end of line 127, hit enter, typed in by hand `this.trigger('active');`.
As soon as I typed `;` at the end of line 128, the line 129 got reformated and mangled (you can see that original `this.debouncedInactiveTrigger()` become shifted four spaces to the right and that word `this` become `th`.
What's strange is that I can reproduce this almost every time, but the exact prefix of line 128 which is affected is sometimes different. Sometimes it becomes `thidebouncedInactiveTrigger();` for instance.
![tsbug](https://cloud.githubusercontent.com/assets/133093/8542653/91944132-2497-11e5-9a8c-ef3ba22e93f9.png)

I should add, that I also have T3S plugin installed, but I've disabled it, and the problem persists.

**Comment by hoanhtien** [comment]
@qbolec I am not able to repro this issue. Would you mind sending us a stripped-down version of your project?

**Comment by qbolec** [comment]
Well, if I strip it down, the problem manifests slightly different:/
For example if I have a folder with just a single file app.ts 
```
class A{
  alice(){
    this.charlie();
    this.charlie();
  }
  bob(){

  }
  charlie(){

  }
}
```
(with linux line endings and no trailing spaces) and try to add `this.bob();` between the two `this.charlie();` the only strange effect I observe is that the second `this.charlie();` gets indented by additional 2 spaces. The strangeness is in the non-determinism of this - sometimes the indentation does not change, sometimes it does. I've noticed that I have more luck when adding the line for the first time to a freshly opened unmodified file.

**Comment by hoanhtien** [comment]
@qbolec Thank you for the repro. This should be resolved by adding the following setting: `"indent_size":2` and restarting Sublime Text. Can you help check if this setting resolves your original issue (`this.debouncedInactiveTrigger();` gets wrongly formatted) too?

**Comment by qbolec** [comment]
It did not solve the problem neither in the original app nor in the repro :/
I put the `"indent_size":2,` into the Preferences.sublime-settings file (Preferences > Settings - Default). Is it the correct place to put it?

**Comment by hoanhtien** [comment]
Yes, it is the correct place. 

I think there is an out-of-sync problem between typescript server and Sublime buffer. I'll look into it.

**Comment by qbolec** [comment]
I've noticed that sometimes the line below the added line is not affected but there are 4 spaces added at the end of the inserted line.

**Comment by flatrocks** [comment]
I too am using a "tab size" of two spaces.  Setting "indent_size":2 has no effect.  
Example (Mac OS X, Sublime Text 2, this commit 0504a55.)  

Example, before:

``` typescript
  onManufacturerChange(id) {
    this.printerSeries = this.selectedPrinterSeriesId = null
    this.getPrinterSeriesByManufacturer(this.selectedManufacturerId)
  }
```

after cursor on line 2, Cmd+C, Cmd+V:
```
  onManufacturerChange(id) {
      this.printerSeries = this.selectedPrinterSeriesId = null
      this.printerSeries = this.selectedPrinterSeriesId = null
    this.getPrinterSeriesByManufacturer(this.selectedManufacturerId)
  }
```

I also have strange unexpected deleted characters and reformatting when I paste into a file.  Have not had time to figure out exactly when/how this happens.  I often only notice it when something that has been working starts to crash.  The final result is that using this plugin is only slightly helpful and requires reviewing the code all the time to see what the plugin has done to it.  It sure seems like this plugin is trying so hard to "help" me that it screws up my code.
