### ISSUE TITLE
Type completion for Javascript on Sublime Text 3

### ISSUE THREAD

**Issue by stereokai** [Microsoft/TypeScript-Sublime-Plugin#278]
i know you've provably read the title twice, so, yes - what do I need to do to get type completion for Javascript on Sublime Text 3?

I have installed `tsd` and type completion and declarations work for angular, jquery, etc. - however, not for plain JS.

I do know that there is the lib.es6.d.ts, it does cover ES2015.

So, what am I missing here? Thanks.

**Comment by zhengbli** [comment]
It is on our roadmap. We are doing some experimental work that lets ts and js files communicate about the type information, though for now it is not mature enough to release yet.

**Comment by stereokai** [comment]
I see. Is there an issue for it?

**Comment by albertosantini** [comment]
Any news? 
Is the work in progress in any branch?

**Comment by zhengbli** [comment]
Will push a release with JS support soon. The APIs are already in place, just need to make the client invoke it. Sorry for the delay.

**Comment by albertosantini** [comment]
@zhengbli Thanks for the effort https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/570.

I hope devs will merge that PR as soon as possible. :)

**Comment by DanielRosenwasser** [comment]
This should be fixed by #620 and will be in the next release.
