### ISSUE TITLE
popup_manager only works for builds 3070+

### ISSUE THREAD

**Issue by joneshf** [Microsoft/TypeScript-Sublime-Plugin#279]
This should be mentioned somewhere, as otherwise it's nigh impossible to figure out why it doesn't work.

Original discussion on [gitter](https://gitter.im/Microsoft/TypeScript-Sublime-Plugin?at=55966195fda0bd877e081016).

**Comment by zhengbli** [comment]
We did mention in the [readme](https://github.com/Microsoft/TypeScript-Sublime-Plugin#platform-support) that:
> the use of a Sublime Text 3 build >= 3070 is recommended, as this provides a popup API used for tool tips.

You should have intellisense (a.k.a auto completion) even if you are using an older version. Are you not getting that? Thanks.

**Comment by joneshf** [comment]
Oh. I missed that.

Could that feature get its own section [here](https://github.com/Microsoft/TypeScript-Sublime-Plugin#features) that explains how to use it as well? I think this feature is great. I wasn't even aware sublime added a popup feature until I installed this package.

And yes, completion works. It's just that the popup_manager does not work for any build older than 3070 (including st2).

**Comment by zhengbli** [comment]
Sure. The readme file is a bit out of date. Thanks for pointing out!

**Comment by hoanhtien** [comment]
Readme updated. Closing this thread.

**Comment by joneshf** [comment]
Awesome, thanks! I just have one suggestion. It'd be nice to see that information near the screenshot since the naming isn't uniform as to what it's called when searching text (intellisense, popup, completion, etc) so it might be hard to find out why it doesn't work when you need it to. Searching for the name was part of my problem originally.

I'll submit a PR with what I mean.
