### ISSUE TITLE
Goto symbol in project... (ctrl/cmd+shift+r)

### ISSUE THREAD

**Issue by kungfusheep** [Microsoft/TypeScript-Sublime-Plugin#280]
Currently it's not possible to navigate directly to a class using goto symbol in project. Are there plans to implement this for TypeScript ?

Currently performing this action will take you to the compiled javascript rather than the TypeScript file. 

Great work, by the way. Cheers.

**Comment by zhengbli** [comment]
Have you tried ``ctrl + alt + r`` (navigate to symbol)?

**Comment by kungfusheep** [comment]
Ah! Great! I didn't see that option in any of the menu's. 

In that case, are there any plans to consolidate the two?

**Comment by zhengbli** [comment]
The "goto symbol" is built-in with Sublime, so there is no way to change that. Though it should appear in the menu:
![untitled](https://cloud.githubusercontent.com/assets/1171301/8559892/2d83f932-24c7-11e5-99a3-4a55798a07eb.png)

**Comment by kungfusheep** [comment]
Ah yeah... I was naively looking here ->
![screen shot 2015-07-08 at 00 46 00](https://cloud.githubusercontent.com/assets/6867511/8560002/3317493c-250b-11e5-8744-1ad894de0cd7.png)

That's just brought my attention to alt+, also, hah. Cool. 

Okay thanks, consider the question closed from my perspective.

**Comment by zhengbli** [comment]
That's a fair point though, we should probably insert an menu item in the Goto menu too. Thanks for the feedback!
