### ISSUE TITLE
trouble in using this with Vintageous

### ISSUE THREAD

**Issue by kidddddd1984** [Microsoft/TypeScript-Sublime-Plugin#295]
> startup, version: 3083 osx x64 channel: stable
> executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
> working dir: /
> packages path: /Users/liuchang/Library/Application Support/Sublime Text 3/Packages
> state path: /Users/liuchang/Library/Application Support/Sublime Text 3/Local
> zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
> zip path: /Users/liuchang/Library/Application Support/Sublime Text 3/Installed Packages
> ignored_packages: ["Vintage"]
> pre session restore time: 0.298
> using gpu buffer for window
> first paint time: 0.369752
> using gpu buffer for window
> startup time: 0.442981
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_file_settings
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.quick_panel
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.02-bz2
> reloading plugin BracketHighlighter.bh_core
> reloading plugin BracketHighlighter.bh_logging
> reloading plugin BracketHighlighter.bh_plugin
> reloading plugin BracketHighlighter.bh_regions
> reloading plugin BracketHighlighter.bh_remove
> reloading plugin BracketHighlighter.bh_rules
> reloading plugin BracketHighlighter.bh_search
> reloading plugin BracketHighlighter.bh_swapping
> reloading plugin BracketHighlighter.bh_wrapping
> reloading plugin Color Highlighter.ColorHighlighter
> reloading plugin Color Highlighter.colors
> reloading plugin DashDoc.DashDoc
> reloading plugin DocBlockr.jsdocs
> reloading plugin Emmet.emmet-plugin
> reloading plugin GitGutter-Edge.git_gutter
> reloading plugin GitGutter-Edge.git_gutter_change
> reloading plugin GitGutter-Edge.git_gutter_compare
> reloading plugin GitGutter-Edge.git_gutter_events
> reloading plugin GitGutter-Edge.git_gutter_handler
> reloading plugin GitGutter-Edge.git_helper
> reloading plugin GitGutter-Edge.view_collection
> reloading plugin Gitignore.gitignore
> reloading plugin Package Control.bootstrap
> reloading plugin Package Control.Package Control
> reloading plugin Schemr.schemr
> reloading plugin SideBarEnhancements.SideBar
> reloading plugin SideBarEnhancements.SideBarAPI
> reloading plugin SideBarEnhancements.SideBarDefaultDisable
> reloading plugin Themr.themr
> reloading plugin Vintageous.__init__
> reloading plugin Vintageous.dev_cmds
> reloading plugin Vintageous.ex_commands
> reloading plugin Vintageous.ex_main
> reloading plugin Vintageous.ex_motions
> reloading plugin Vintageous.jump_list_cmds
> reloading plugin Vintageous.modelines
> reloading plugin Vintageous.state
> reloading plugin Vintageous.test_runner
> reloading plugin Vintageous.xactions
> reloading plugin Vintageous.xmotions
> reloading plugin Vintageous.xsupport
> reloading plugin Vintageous.xsupport_mouse
> reloading plugin ColorPicker.sublimecp
> reloading plugin ConvertToUTF8.ConvertToUTF8
> reloading plugin TypeScript.main
> 2015-07-16 19:42:33,199: 140735161475840: INFO: Logging configured to log to file: /Users/liuchang/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/TS.log
> INFO:TS:Logging configured to log to file: /Users/liuchang/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/TS.log
> 2015-07-16 19:42:33,228: 140735161475840: WARNING: TypeScript plugin initialized.
> WARNING:TS:TypeScript plugin initialized.
> plugins loaded
> DEBUG:TS:plugin_loaded started
> spawning node module: /Users/liuchang/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
> Found node executable at /Users/liuchang/n/bin/node
> DEBUG:TS:opening /Users/liuchang/n/bin/node /Users/liuchang/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
> DEBUG:TS:server proc <subprocess.Popen object at 0x10b81db10>
> DEBUG:TS:starting reader thread
> DEBUG:TS:Posting command: {"type": "request", "seq": 1, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": null}}
> ref view not found
> DEBUG:TS:plugin_loaded ended
> DEBUG:TS:on_text_command
> Packages/TypeScript/popup.html
> INFO:TS:Popup resource path: Packages/TypeScript/popup.html
> INFO:TS:Loaded tooltip template from Packages/TypeScript/popup.html
> DEBUG:TS:Posting command: {"type": "request", "seq": 2, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 3, "command": "open", "arguments": {"file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:on_text_command_with_info
> DEBUG:TS:on_text_command
> DEBUG:TS:on_text_command_with_info
> DEBUG:TS:on_post_text_command
> DEBUG:TS:Posting command: {"type": "request", "seq": 4, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 5, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 6, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 7, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 8, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 9, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:on_post_text_command
> DEBUG:TS:Posting command: {"type": "request", "seq": 10, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 11, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 12, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 13, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 14, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 15, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 16, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 17, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 18, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:on_activated
> DEBUG:TS:on_activated_with_info
> DEBUG:TS:Posting command: {"type": "request", "seq": 19, "command": "reload", "arguments": {"file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts", "tmpfile": "/Users/liuchang/Library/Application Support/Sublime Text 3/Packages/TypeScript/.tmpbuf0"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 20, "command": "geterr", "arguments": {"files": ["/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"], "delay": 200}}
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 1
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 2
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 4
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 5
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 6
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 7
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 8
> DEBUG:TS:Read body of length: 81
> DEBUG:TS:Body sequence#: 9
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 10
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 11
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 12
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 13
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 14
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 15
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 16
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 17
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 18
> DEBUG:TS:Posting command: {"type": "request", "seq": 21, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 22, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 23, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 24, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 25, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 26, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 27, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 28, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Posting command: {"type": "request", "seq": 29, "command": "configure", "arguments": {"hostInfo": "Sublime Text version 3083", "formatOptions": {"indentSize": 4, "convertTabsToSpaces": true, "tabSize": 4}, "file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"}}
> DEBUG:TS:Read body of length: 79
> DEBUG:TS:Body sequence#: 19
> Emmet: No need to update PyV8
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 21
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 22
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 23
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 24
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 25
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 26
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 27
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 28
> DEBUG:TS:Read body of length: 82
> DEBUG:TS:Body sequence#: 29
> DEBUG:TS:Posting command: {"type": "request", "seq": 30, "command": "reload", "arguments": {"file": "/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts", "tmpfile": "/Users/liuchang/Library/Application Support/Sublime Text 3/Packages/TypeScript/.tmpbuf0"}}
> DEBUG:TS:Read body of length: 143
> DEBUG:TS:Read body of length: 145
> DEBUG:TS:Read body of length: 79
> DEBUG:TS:Body sequence#: 30
> DEBUG:TS:call get_event from on_idle
> DEBUG:TS:asking for errors
> DEBUG:TS:Posting command: {"type": "request", "seq": 31, "command": "geterr", "arguments": {"files": ["/Users/liuchang/Source/nodejs/ts-angular/src/app/index.run.ts"], "delay": 500}}
> DEBUG:TS:Read body of length: 143
> DEBUG:TS:Read body of length: 145
> DEBUG:TS:on_window_command
> DEBUG:TS:on_activated
> DEBUG:TS:on_activated_special_view
> DEBUG:TS:call get_event from on_idle
> DEBUG:TS:asking for errors
> DEBUG:TS:call get_event from on_idle
> DEBUG:TS:asking for errors
> DEBUG:TS:call get_event from on_idle
> DEBUG:TS:asking for errors
> Package Control: Skipping automatic upgrade, last run at 2015-07-16 19:31:22, next run at 2015-07-16 20:31:22 or after

I have no idea about this :(
seems TSplugin is forced to run in debug mode.

**Comment by hoanhtien** [comment]
@kidddddd1984 Did you get the plug-in from GitHub or from PackageControl?

**Comment by hoanhtien** [comment]
@kidddddd1984 This problem no longer presents if I install Vintageous by cloning its GitHub master. I guess this commit fixes it: https://github.com/guillermooo/Vintageous/pull/975. I suggest you to do the same.

**Comment by kidddddd1984** [comment]
Yes, I installed from package control.

I will try to clone master branch and see it again.

**Comment by kidddddd1984** [comment]
@hoanhtien Yes! It's worked
