### ISSUE TITLE
sometime frozen when need a autocomplete

### ISSUE THREAD

**Issue by kidddddd1984** [Microsoft/TypeScript-Sublime-Plugin#298]
![untitled](https://cloud.githubusercontent.com/assets/6410921/8780880/dbb389da-2f46-11e5-8dfe-ecebcd950efa.gif)

As you see, like another autocomplete window covered this one. this will take 3 or 4 seconds and lead sublime text to frozen.

also got `queue timeout` from console

![default](https://cloud.githubusercontent.com/assets/6410921/8781088/2391d1fc-2f48-11e5-9eeb-e1b6da887a08.png)

**Comment by kidddddd1984** [comment]
I delete all other plugins and got the same. means something else also trade .ts file as itself.

ST version: 3083

**Comment by kidddddd1984** [comment]
Also tested on windows8.1 and Ubuntu14.04. both have the same problem but on windows the covering is even too faster than this on Ubuntu and Mac so there are no `queue timeout` errors in the console.

**Comment by hoanhtien** [comment]
@kidddddd1984 Could you send me a repro project?

**Comment by kidddddd1984** [comment]
@hoanhtien https://github.com/kidddddd1984/ts-test

maybe you can use this. I created this just want to test new import declarations in ts1.5 but got these problem.

**Comment by hoanhtien** [comment]
The plugin waits for response from tsserver and then updates the auto completion popup. In my machine, I can only see a slight delay ~0.1 second or so. I will try to repro this issue on a slower machine.

**Comment by hoanhtien** [comment]
I am not able to repro this issue on a virtual machine with Ubuntu 14.04.2 LTS, 4 CPUs and 4GB RAM.

**Comment by kidddddd1984** [comment]
@hoanhtien tried on a vm with Ubuntu 14.04.2 LTS. As you say, the delay is slightly like i did on windows8.1. So there should be something wrong with my dev environment on a unix-like system.

i will check it! thank you for you patient :+1:

**Comment by kidddddd1984** [comment]
@hoanhtien 
I think I found the point !

If you use a `tsconfig.json` file to configure project the complete speed will down and sometimes to frozen. It's only occurred on Mac and Ubuntu system.

You can repro this issue by create a new `f.ts` file in an opened tsconfiged project. You will see completion is faster when you typing something in new file, Then reopen the project, now the `f.ts` file been the same with other files which was created earlier.

Hope this can be useful

**Comment by kidddddd1984** [comment]
@hoanhtien tried on someone else's mbp, it worked perfectly!  Close this issue 

Thanks a lot
