### ISSUE TITLE
Build command different, when focus is in different .ts files

### ISSUE THREAD

**Issue by ghost23** [Microsoft/TypeScript-Sublime-Plugin#319]
Hi,

i have this little project:

![image](https://cloud.githubusercontent.com/assets/1169512/9026070/24ff442e-3921-11e5-8b74-4d12bde90690.png)

In the tsconfig, it says:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "rootDir": "src/",
        "outDir": "built/",
        "sourceMap": true
    }
}
```

If I have the focus in the main.ts, I can simply hit F7 and the build runs just fine. If I am in the index.ts however, first a little build parameters dialog comes up at the bottom of the screen, and if I just hit enter, it says "the module flag has not been provided", which sounds to me like the build tool has not seen the tsconfig.json file.

Is this a bug, or am I doing something wrong here?

**Comment by hoanhtien** [comment]
@ghost23 Are you still getting this error after restarting Sublime? After making changes to tsconfig.json, Sublime should be restarted for the changes to take effect.

I am seeing the same error when focus is on either file: 
```
C:/Users/tihoanh/Desktop/ts-test/src/index.ts(1,23): error TS2306: File 'C:/Users/tihoanh/Desktop/ts-test/src/main.ts' is not a module.
[Finished in 1.0s]
```

**Comment by ghost23** [comment]
huh,
I thought I did that, apparently not. It is working now on both files. I don't quite understand, why you are getting the error, though, because it compiles just fine on my end.

Thanks anyway :)
