### ISSUE TITLE
TypeScript not detecting new files

### ISSUE THREAD

**Issue by LennardF1989** [Microsoft/TypeScript-Sublime-Plugin#320]
I'm using Sublime build 3095 with the latest Package Control installed TypeScript support. The issue I have right now is that every time I rename a file or add a new one, I have to restart Sublime before the Intellisense updates, or can even hit Ctrl+B to compile the project (unless I switch to a file that already existed at the time I started Sublime).

I can live with it, but its rather annoying TypeScript doesn't pick up on changes in the project folder.

EDIT: I'm stupid, this issue is handled in the Wiki, sorry... (Point #3 to be exact, I don't have a files-definition in my tsconfig.json)

**Comment by LennardF1989** [comment]
Is it an idea that while we wait for Sublime to provide proper hooks, to have a shortcut to force a resync of the tsserver?

**Comment by hoanhtien** [comment]
@LennardF1989 The 'files' property in tsconfig.json can be skipped:

> If no  "files"  property is present in a  tsconfig.json , the compiler defaults to including all files in the containing directory and subdirectories. When a  "files"  property is specified, only those files are included.
(from https://github.com/Microsoft/TypeScript/wiki/tsconfig.json)

IMO, it is better not to include the 'files' property in tsconfig.json so you don't have to edit tsconfig.json every time your add or rename a file and restart Sublime for the changes to take effect.

**Comment by LennardF1989** [comment]
Well, I don't have a files property and still have to restart the editor all the time. But isn't that what point #3 in the FAQ covers?

**Comment by hoanhtien** [comment]
@LennardF1989 What this point wants to say is: Whenever you edit tsconfig.json, you have to restart tsconfig.json for the changes to take effect.
> The server does not yet have file watch support for tsconfig.json projects. This means that if your tsconfig.json file does not have a "files" property, and you add a new file to a directory configured by that tsconfig.json file, you will need to restart Sublime to get that file noticed. The same applies to changes in the options properties of the tsconfig.json file.

From what you describes, this is probably a bug. Could you send us a repo project and/or some screenshots to investigate?

**Comment by LennardF1989** [comment]
Where would you like screenshots of, I unfortunately can't share this project. I'm using Sublime build 3095 with the latest Package Control installed TypeScript support on Windows 7.

My tsconfig.json looks as follows:

    {
        "compilerOptions": {
            "out": "js/program.js",
            "sourceMap": true
        }
    }

The file resides in the root of the project where all typescript files are actually in a /typescript-folder (hence the output is all copied and combined into a single program.js in the /js-folder).

Whenever I add a new file to the typescript folder, the intellisense won't pick it up, nor will CTRL+B (for build) work as it will just give me a "enter a command-line"-toolbar on the bottom. whereas if I switch to a file that was already in the project at the time Sublime loaded, I can build just fine and it will also compile the new files.

**Comment by LennardF1989** [comment]
Ok! Did some more testing, it's related to using sub-namespaces! eg. My main namespace/module is SublimeTest, whenever I also have a SublimeTest.SubTest namepace (living in its own subfolder) in which I export classes, above behavior kicks in when I add files to it and try to compile them!

Here is the project-folder: https://dl.dropboxusercontent.com/u/4832900/SublimeTest.zip

When you add a file to the root of the typescript-folder, it works fine and you can immediately compile, whenver you do so in the SubTest folder, things fall over as you can't compile the new file using the shortcut nor will Intellisense pick it up.

**Comment by hoanhtien** [comment]
Thanks! I can repro now. This is indeed a bug.

**Comment by hoanhtien** [comment]
This is a TypeScript compiler/language service issue. Basically tsserver does not know when a new file is added. Two approaches that can be done:
1. Add a 'add' command to notify tsserver when a new file is added. Sublime does not provide a 'new file added' event; but it does provide 'new view' and 'view pre save' that may can be used to detect when a new file is added.
2. Add a directory watcher. Ideal, however seems to be difficult because node does not provide a native directory watcher. This is being discussed in https://github.com/Microsoft/TypeScript/issues/2375.

**Comment by zhengbli** [comment]
With the latest releases, this should be fixed. @LennardF1989 can you confirm? Thanks.

**Comment by LennardF1989** [comment]
Confirmed, my original project in which I encountered this issue is now working without problems!
