### ISSUE TITLE
TypeScript syntax highlighting problem when putting curly braces in new lines.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#322]
Copied from https://code.visualstudio.com/Issues/Detail/18184

There's a problem with TypeScript syntax highlighting when putting methods' curly braces in new lines. Keywords like public, this or even argument types are not being highlighted, they're just plain gray. The problem is not occuring when I put curly braces in the same lines as method declarations.
![screenshot from 2015-07-26 18_44_19](https://cloud.githubusercontent.com/assets/1931590/9033121/e9e88f36-39c4-11e5-95f1-dde1628b1067.png)

**Comment by dbaeumer** [comment]
Observe if you put the curly from line 11 to 10 then the function on line 16 is colored correctly.

**Comment by hoanhtien** [comment]
This is fixed in v0.1.7:

Before:
![image](https://cloud.githubusercontent.com/assets/1707813/9072181/9080ec6e-3aae-11e5-8fb0-6a492c4f33ef.png)

Now:
![image](https://cloud.githubusercontent.com/assets/1707813/9072189/97a676da-3aae-11e5-9148-33203cce7322.png)
