### ISSUE TITLE
There is no intellisence in TypeScriptReact syntax.

### ISSUE THREAD

**Issue by nikolaymatrosov** [Microsoft/TypeScript-Sublime-Plugin#323]
TSX files have only dumb type suggest based on words in the file. No Typechecking, Signature popup or other intelligent features.

**Comment by hoanhtien** [comment]
You can check out this pull request https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/290. The latest public release of TypeScript (v.1.5.3) has not included supports for TSX so we haven't merged this pull request to master.

**Comment by nikolaymatrosov** [comment]
Thanks. I'll watch for updates.
