### ISSUE TITLE
Offer completion on non-imported items.

### ISSUE THREAD

**Issue by kungfusheep** [Microsoft/TypeScript-Sublime-Plugin#327]
So essentially an 'auto import' feature for classes within modules/namespaces that are accessible in the current context. 

This would be a massive time saver.  I realize there are multiple ways to do `import`'s now, but the type of import could be inferred from the `module` type in tsconfig.

Cheers

**Comment by DanielRosenwasser** [comment]
Do you mean something like C#'s "add references"? Or do you mean like completion in the following scenario?

```TypeScript
import { } from /*cursor here*/
```

**Comment by kungfusheep** [comment]
Sorry, I could've been more specific. 

What I mean is, say I have this class in `MyClass.ts` 
```javascript
module my_module {
	export class MyClass {}
}
```

Then in `MyOtherClass.ts` I can begin writing this line...
```javascript
module my_other_module {
	export class MyOtherClass{
		public method() : void {
			var myClass = new MyCla /* Now show completions for MyClass - my_module */
		}
	}
}
```

Upon hitting enter, an import statement (based on the current module type) would be inserted to the top of the module like so...

```javascript 
module my_other_module {
	import MyClass = my_module.MyClass;
	export class MyOtherClass{
		public method() : void {
			var myClass = new MyClass();
		}
	}
}
```

It seems to me that sublime is all about speed and simplicity. Having to move to the top of the file during authoring breaks your flow, doesn't it, so something like this would be fantastic at helping you keep up the pace. 

Thanks!

**Comment by DanielRosenwasser** [comment]
Closing in favor of https://github.com/Microsoft/TypeScript/issues/4370. Thanks for the suggestion.

**Comment by kungfusheep** [comment]
Cheers
