### ISSUE TITLE
TypeScriptReact grammar produces endless loop in firstmate

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript-Sublime-Plugin#328]
We have started to use the TypeScriptReact grammar in VS Code. The textmate implementation in VSCode (firstmate) flags an error in the grammar:
![image](https://cloud.githubusercontent.com/assets/172399/9378343/01a51d56-4721-11e5-9548-f0d5d57dbc0c.png)

The issue can be reproduced with this snippet
```
import * as React from "react";

interface Props {
  foo: string;
}

class MyComponent extends React.Component<Props, {}> {
 constructor(props:Props) {
    super(props);
  }

  render() {
    return <span>{this.props.foo}</span>
  }
}

<MyComponent foo="bar" />; // ok
<MyComponent foo={0} />; // error

```

See also #229

**Comment by billti** [comment]
This should be fixed with https://github.com/Microsoft/TypeScript-Sublime-Plugin/commit/139d1483a583a6eb4a61447250ca5535739c5db3 . Thanks!
