### ISSUE TITLE
Include JS files for linting and type checking

### ISSUE THREAD

**Issue by alexpaluzzi** [Microsoft/TypeScript-Sublime-Plugin#331]
Hey guys-- I love that the TS compiler also lints JS files on Visual Studio Code.

I'm wondering if I can make the Sublime plugin do the same thing? I know that auto-completion with custom types (via d.ts?) are on the roadmap for JS files, but is it possible to just gain the out-of-the-box linting and intellisense that are inferred from the working file?

Since "all valid JavaScript is valid TypeScript," I didn't know if there was a switch or something I could flip. (Does this montra still hold true?)

Thanks

**Comment by DanielRosenwasser** [comment]
Hey @alexpaluzzi, we've been experimenting/toying with this option, but nothing in terms of what we could call "official" support.

That said, you can try configuring Sublime to associate the JavaScript files with the TypeScript filetype.

**Comment by billti** [comment]
TypeScript doesn't do any linting currently, I believe that is something VS Code does separately.

We are experimenting with options to allow TypeScript types to provide JavaScript intellisense, but that will be a feature of the TypeScript project, not specific to Sublime (i.e. the TypeScript sublime plugin should just get it for free if/when TypeScript adds it).

Per your title, we also won't do "type checking" in JavaScript files (we'll help you write it with intellisense support, but we won't give errors saying "this type is wrong". That's what TypeScript is for :-) ).

**Comment by alexpaluzzi** [comment]
@billti Are you sure about that? I was told by someone on the Code team that they were using the tsserver for the JS files just the same.

And, as per my original post, it does do some kind of native type checking, even in plan JS. I have seen it infer a number or a string type on a variable and then give me warning if I try to assign a different type. I see it all of the time, even in JS files.

Perhaps there is some miscommunication somewhere, but this is what I was told and it's also what I've personally observed.

**Comment by billti** [comment]
Right, not for linting, but VS Code does feed JavaScript files through the TypeScript language service to get intellisense via the same type inference that the TypeScript language uses. They do a bunch of manipulation of the JavaScript source text to get some other features to work in this setup also (i.e. Node module imports, etc...)

I assume when you say "they give me a warning if I try to assign a different type" that this is a linting warning too? In general, feedback from JavaScript devs has been strongly against giving type warnings/errors in the language service with JavaScript code - as the dynamic nature of a great deal of JavaScript makes this too noisy/onerous.

We have discussed ideas around linting in TypeScript, or about being able to dial these (i.e. so you could make TypeScript less strict, or JavaScript more strict), but again, that would be an issue for the TypeScript project (there may already be one), not the Sublime plugin. We don't plan to add compiler or language service features to the Sublime TypeScript plugin beyond those supported by TypeScript.

**Comment by alexpaluzzi** [comment]
Hey @billti, thanks for the response.

The intellisense is exactly what I'm talking about. I would love that feature somehow in Sublime. I apologize, perhaps "linting" wasn't the best word.

I also understand the whole dynamic nature and it causing too much noise for someone who doesn't care about types. It seems to be enabled by default in Code (the warnings) when working with JS, but I get that's not really something related to this plugin.

Really, it was just your first sentence there that is what I really wanted to see in Sublime. Sublime is my main tool after finally getting out of VIM. I really love the TypeScript plugin (you guys are awesome), and I'm envious of how great your TS language service works in Code. @DanielRosenwasser hit the nail on the head on his first response here, if I could just get it so somehow peek at JS files, maybe I could get it to get that intellisense via the type interface. :)

In any case, I appreciate your time and this plugin. I hope to be submitting some (unrelated) PRs shortly.
