### ISSUE TITLE
Support for filesGlob

### ISSUE THREAD

**Issue by vintem** [Microsoft/TypeScript-Sublime-Plugin#343]
It would be useful if the plugin had support for filesGlob attribute for the tsconfig.json file.
Like in Atom, we can have an filesGlob attribute like this:

```json
    "filesGlob": [
        "./src/*.ts",
        "./test/unit/*.ts",
        "./typings/tsd.d.ts"
    ],
```

and it will scan the directories and add the files to files section.

Thanks

**Comment by hoanhtien** [comment]
@mhegazy Can you comment on this?

**Comment by mhegazy** [comment]
The right thing is for the compiler to support it. then *all* editors will get it for free. that is better than having all editors to go support it independently.

We have a PR for this in https://github.com/Microsoft/TypeScript/pull/3232 that is incomplete, if some one is interested in picking that up, this will solve the underlying issue.

**Comment by zhengbli** [comment]
Since there is already another PR at TypeScript repo, closing this.
