### ISSUE TITLE
Typescript format-as-you-type ignores indentation size preference

### ISSUE THREAD

**Issue by zackzachariah** [Microsoft/TypeScript-Sublime-Plugin#345]
The Typescript format-as-you-type feature has the indentation style of four spaces hardcoded, ignoring user preferences for different-sized indentations or for tabs instead of spaces.

The bugs are at `tsserver/tsc.js` line 5386 and `tsserver/tsserver.js` line 5220, but I don't know enough about Sublime plugins to correct it myself. Those lines have `"    "` (four spaces, a prize to whomever tells me how to write four spaces in markdown) hardcoded as the indentation style to use. If I switch it to `"  "` (two spaces, the same as in my preferences) the plugin now conforms to my preferred indentation style.

The value to insert per level of indentation should be dynamic.

**Comment by hoanhtien** [comment]
I am not able to reproduce this issue, at least with 2-space tab.

Have you tried using the following settings with the latest plugin version?
```
"tab_size": 2,
"indent_size": 2,
```

![2spacetab](https://cloud.githubusercontent.com/assets/1707813/9691015/a42fcc40-52f4-11e5-9e21-adf46cf5b318.gif)

**Comment by zackzachariah** [comment]
Aha! I didn't know about the `indent_size` preference in sublime, only about the `tab_size` preference. My bad!

Also, what are you using to make these gifs? They're very cool.

**Comment by hoanhtien** [comment]
@zackzachariah Thank you for using the plugin :smiley:

As for the gifs, I am using this tool: https://screentogif.codeplex.com/. Enjoy!
