### ISSUE TITLE
Unable to move sourceMap(.map) files to separate folders in Typescript

### ISSUE THREAD

**Issue by jayapalt** [Microsoft/TypeScript-Sublime-Plugin#351]
Hi,

I've posted my issues in stackoverflow. Below is the link of my issue:

http://stackoverflow.com/questions/32426004/unable-to-move-sourcemap-map-files-to-separate-folders-in-typescript

Please let me know how to move sourceMap files to other folders on run-time.

**Comment by hoanhtien** [comment]
@jayapalt Looking at https://github.com/Microsoft/TypeScript/wiki/Compiler-Options, I think moving .map files to a separate folder is not supported. 

.map files contain the debugging information for .ts files. They are meant to be used by debugger.

If you are not using any TypeScript debugger, I suggest turning them off with the setting `"sourceMap": false`.
