### ISSUE TITLE
Incorrect highlighting using enum values as class member names

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript-Sublime-Plugin#354]
Using the following source (valid in at least TypeScript 1.6):

```ts
enum Hello {
	A,
	B
}

class World {
	normal() {
		let x = 5;
		console.log("hello");
	}

	[Hello.A]() {
		let x = 5;
		console.log("hello");
	}
}
```

This causes very strange highlighting in the body of the method declaration:

![002416](https://cloud.githubusercontent.com/assets/654598/9841442/00c50906-5a5d-11e5-898e-931e3f0b0854.png)

**Comment by zhengbli** [comment]
Closing as tmLanguage issues are now tracked at https://github.com/Microsoft/TypeScript-TmLanguage
