### ISSUE TITLE
All completions show up as 'warning' when using Salsa

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#364]
![image](https://cloud.githubusercontent.com/assets/972891/10056848/e9fef960-61f1-11e5-8eeb-cfe913908256.png)

This is somewhat confusing and not very helpful.

**Comment by hoanhtien** [comment]
I can repro. @billti may have a better idea on why this happens.

**Comment by DanielRosenwasser** [comment]
It's because the plugin just always prints out the script element kind; in this case it's `ScriptElementKind.warning` which is just set to `"warning"`.

In Visual Studio, we probably check for it specifically.

**Comment by zhengbli** [comment]
And also the received completion list from Salsa server needs to be sorted according to importance. Otherwise the list would be sorted alphabetically which makes it appear broken. Making this a bug.

**Comment by zhengbli** [comment]
The latest Salsa bits already fixed this behavior. Closing.
