### ISSUE TITLE
Assigning to a member variable named interface makes syntax highlighting break

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#367]
See picture
![bad highlighting](https://cloud.githubusercontent.com/assets/1931590/10178587/f4719b3c-6700-11e5-8f36-d8a7bbbcf13d.png)

**Comment by hoanhtien** [comment]
Possibly related to https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/353.
