### ISSUE TITLE
TS Config not being loaded.

### ISSUE THREAD

**Issue by bweston92** [Microsoft/TypeScript-Sublime-Plugin#371]
```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "target": "ES6",
    "jsx": "react"
  },
  "exclude": [
    "public",
    "node_modules"
  ]
}
```

Above is the contents of my `tsconfig.json` when I run `tsc my-file.tsx` I get the error below.

```
$ tsc main.tsx
src/ts/main.tsx(5,1): error TS1148: Cannot compile modules unless the '--module' flag is provided.
src/ts/main.tsx(5,9): error TS2305: Module '"react"' has no exported member 'React'.
src/ts/main.tsx(6,24): error TS2497: Module '"react-dom"' resolves to a non-module entity and cannot be imported using t
his construct.
src/ts/main.tsx(10,12): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
src/ts/main.tsx(14,17): error TS2605: JSX element type 'App' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'App'.
src/ts/main.tsx(14,17): error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
```

Information.
```
$ ls
node_modules  package.json  public  main.tsx  tsconfig.json  typings
$ tsc --version
message TS6029: Version 1.7.0-dev.20151006
$ uname -a
CYGWIN_NT-10.0 DESKTOP 2.0.4(0.287/5/3) 2015-06-09 12:22 x86_64 Cygwin
```

**Comment by billti** [comment]
I believe you (currently) cannot target ES6, and also target a different module system. If you are targeting ES6, then it writes our ES6 import/export syntax. Can you try just using one or the other and let us know if that works?

Note: We (TypeScript) realize this is impractical, as lots of engines (such as Node) support ES6 features (such as classes, arrow functions, generators, etc...), but still only support CommonJS module syntax. The next release will allow for targeting ES6 emit while also specifying a different module system.

**Comment by mhegazy** [comment]
> Above is the contents of my `tsconfig.json` when I run `tsc my-file.tsx` I get the error below.

do not pass files to the compiler if you want it to use your tsconfig.json. either run it with no options e.g. `tsc` and it will look up all files in this directory automatically, or using `--project`  e.g `tsc --p <path to folder containing tsconfig.json`.

**Comment by bweston92** [comment]
@mhegazy that is the one, maybe that needs writing up somewhere?

**Comment by mhegazy** [comment]
here you go: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#using-tsconfigjson

**Comment by bweston92** [comment]
@mhegazy thanks!
