### ISSUE TITLE
Grammar needs to support 'async'/'await' keywords

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#374]
This should go out for 1.7

![image](https://cloud.githubusercontent.com/assets/972891/10553851/f5a45ad4-7412-11e5-9fdd-af3ed7a596ed.png)

**Comment by ejsmith** [comment]
Why is this closed?  It doesn't look like the async keyword is recognized and highlighted yet.

**Comment by mhegazy** [comment]
We now have a different repo for the syntax definitions that is used by sublime text, VSCode and atom. the @zhengbli ported the issue to the new repo, and it is now tracked by https://github.com/Microsoft/TypeScript-TmLanguage/issues/9. the issue is still open.
