### ISSUE TITLE
Add Decorator syntax

### ISSUE THREAD

**Issue by joskuijpers** [Microsoft/TypeScript-Sublime-Plugin#377]
Hi,

I want to use decorators, but they mess up the syntax coloring.
Could support for decorators be added? Even if it is only to avoid messing up the rest of the code?

Currently, the decorators look odd, but when a parameter decorator is combined with a pair: `method(@AdapterParam() {req, res}: AdapterData)`, the syntax is lost.

![image](https://cloud.githubusercontent.com/assets/5017040/10605815/b8fb67b6-772e-11e5-96bf-6fc438a50a96.png)

I wish I could send a pull request, but I can't seem to understand how the tmLanguage system works.
A patch for me locally would also be awesome (in case you don't want support for experimental features).

Thanks a lot!

**Comment by zhengbli** [comment]
Hi @joskuijpers 
We definitely are willing to support the decorator syntax. Though a PR is more than welcome! Just in case you are interested, you can find some info about the tmlanguage at:
http://manual.macromates.com/en/language_grammars

We will fix it soon.

**Comment by zhengbli** [comment]
Closing as tmLanguage issues are now tracked at https://github.com/Microsoft/TypeScript-TmLanguage
