### ISSUE TITLE
Sublime double clicking has been broken

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Sublime-Plugin#38]
Sublime supports full word selection upon double clicking. As of today, some change seems to have broken this behavior across all file types.

**Comment by pikilon** [comment]
the problem is back

**Comment by DavisMiculis** [comment]
The same problem appeared for me a few weeks ago on Windows 10 x64, Sublime Text 3 Build 3125 and 3126.

When trying to select multiple items with ctrl + double click, it just deselects everything.
