### ISSUE TITLE
Digit(s) in class method return type breaks highlighting in function body

### ISSUE THREAD

**Issue by mpk** [Microsoft/TypeScript-Sublime-Plugin#380]
Example:

![Screen](https://dl.dropboxusercontent.com/u/841468/external/ts-digit-highlight.png)

Also happens if I use default color scheme. Screenshots are from Sublime Text 2.0.2.

(edit: Same problem occurs in Visual Studio Code)

**Comment by zhengbli** [comment]
Closing as tmLanguage issues are now tracked at https://github.com/Microsoft/TypeScript-TmLanguage
