### ISSUE TITLE
Autoformat when pressing semicolon disregards indent size

### ISSUE THREAD

**Issue by princemaple** [microsoft/TypeScript-Sublime-Plugin#382]
![screenshot_102515_030220_pm](https://cloud.githubusercontent.com/assets/1329716/10714003/63bc3218-7b29-11e5-88b8-cfb87f240d88.jpg)
I have indent size 2 for both `ts` and `tsx`.

Now..
![typescriptsublimebug](https://cloud.githubusercontent.com/assets/1329716/10714015/3eb063b2-7b2a-11e5-97b9-5d7f82c1c35e.gif)

**Comment by alexgorbatchev** [comment]
Try putting `tsfmt.json` file in your project folder with

```json
{
  "TabSize": 2,
  "IndentSize": 2
}
```

**Comment by princemaple** [comment]
@alexandrudima no it doesn't seem to affect anything. Pretty sure that's for the other thing called [typescript-formatter](https://github.com/vvakame/typescript-formatter)?

**Comment by alexgorbatchev** [comment]
I believe this is what typescript uses internally to perform formatting. I'm using TS 1.6 and current release of sublime plugin and formatting is 2 spaces with above configuration.

**Comment by princemaple** [comment]
Just searched through both https://github.com/Microsoft/TypeScript-Sublime-Plugin and https://github.com/Microsoft/TypeScript, no references to `tsfmt` were found.

**Comment by angryzor** [comment]
Didn't try the solution above, but another fix is to go to `Sublime Text 3/Packages/TypeScript/Preferences.sublime-settings` and add the following lines:

```
"tab_size": 3,
"indent_size": 3
```

**Comment by danpantry** [comment]
@angryzor I have done this and I am stil getting this issue. Full settings are below. Using Windows 7.

````
{
	"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
	"default_line_ending": "unix",
	"file_exclude_patterns":
	[
		"*.map"
	],
	"findreplace_small": true,
	"font_face": "Consolas",
	"font_options":
	[
	],
	"font_size": 10,
	"highlight_line": "true",
	"ignored_packages":
	[
		"GitSavvy"
	],
	"open_files_in_new_window": false,
	"quick_panel_small": true,
	"rulers":
	[
		120
	],
	"sidebar_xsmall": true,
	// For typescript
	"indent_size": 2,
	"tab_size": 2,
	"tabs_small": true,
	"theme": "Numix Dark.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"typescript_plugin_tsc_version": "1.7.2",
	"vimbb_classic_tabs": true,
	"vimbb_folder_icons": true,
	"vintage_start_in_command_mode": true,
	"word_wrap": true,
	"wrap_width": 120
}

````

**Comment by mirikle** [comment]
FYI, @angryzor's solution works for me, I patched it in this fork https://github.com/mirikle/TypeScript-Sublime-Plugin
in case you are also annoyed by this bug.

**Comment by angryzor** [comment]
@mirikle:
What @danpantry has done should normally work as well, I tried it on my new install. You only need to add both lines to your user preferences. I misunderstood the way sublime.load_settings works. The key is that both indent_size and tab_size should be defined in your preferences otherwise the TypeScript plugin defaults them to 4 (https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/libs/editor_client.py#L78).

However, note that these settings are read in the initialization phase of the EditorClient singleton. This makes it so you have to restart Sublime Text in order to apply your new settings, contrary to what you usually expect from Sublime Text preferences.

**Comment by mirikle** [comment]
Thanks for letting me know @danpantry. I'll try that later..

**Comment by LiuJi-Jim** [comment]
@angryzor is right.
Currently the plugin reads `indent-size` only from sublime's editor settings (which is merged by user settings and global settings) and only when the editor starts up.
And thus it will ignore runtime settings such as EditorConfig's behaviour.
Hope this to be fixed soon.

**Comment by DanielRosenwasser** [comment]
Everyone, this is contingent on https://github.com/Microsoft/TypeScript/issues/6039.
