### ISSUE TITLE
Integration with SystemJS (jspm)

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript-Sublime-Plugin#385]
I am using the [SystemJS module loader](https://github.com/systemjs/systemjs) (with [this plugin](https://github.com/frankwallis/plugin-typescript)) to load and compile my TypeScript files. This module loader can be configured with custom paths to modules, sort of like aliases. This is useful for setting up aliases to third party libaries, i.e. `immutable` as `my-app/libs/immutable/1/immutable.js`. SystemJS also allows me to use these paths in my references:

```
/// <reference path="immutable/immutable.d.ts" />
```

Where `immutable` resolves to:

```
my-app/libs/immutable/1/
```

However, the Sublime plugin is not configured in the same way, so it barfs.

Perhaps this plugin could enable a configurable filename normalize function, to allow these sort of mappings?

**Comment by billti** [comment]
Sounds like something we'd want configurable within TypeScript / tsconfig.json itself, not specific to the Sublime plugin. I'd suggest you close the issue here and reopen on the https://github.com/Microsoft/TypeScript project.
