### ISSUE TITLE
Incorrect behavior of syntax highlighting (TypeScript)

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#389]
Copied from: https://code.visualstudio.com/Issues/Detail/20245

```typescript
class MyClass {
	public createItems(a: number) {
		return (a<0);
	}
	protected getItem() {
	}
	public setItem() {

	}
}
```

**Comment by zhengbli** [comment]
This is the same as https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/285
Basically we haven't figured out a way to appropriately differentiate less than sign and the generic case. Currently as a workaround it is suggested to put spaces between `a` and `<`.
