### ISSUE TITLE
Regular expression behind `/* comment */` is not highlighted in TypeScript

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript-Sublime-Plugin#391]
```ts
let regex = /**/ /foo/;
```

**Comment by zhengbli** [comment]
A new repo is created to converge the efforts for refining syntax files: https://github.com/Microsoft/TypeScript-TmLanguage. Future issues regarding tmlanguage syntax should be opened there. I'm importing this issue to that repo and closing it here.
