### ISSUE TITLE
Method signatures do not show at all.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript-Sublime-Plugin#394]
I'm running OSX Yosemite and Sublime 3083.

I uninstalled and reinstalled the TypeScript plugin and opened up an empty TypeScript file. Then I typed `window.setInterval(`. No popup displayed. In the debugging console, when I pressed `(` all that was displayed was `insert_snippet`.

Autocompletion works and continues to work even when the signature popup fails to appear.

Any ideas?

**Comment by zhengbli** [comment]
I can't repro on my Mac mini. Does manually pooping up the signature work? The short-cut key is `alt + ,`

**Comment by zhengbli** [comment]
And what is your node version? Which might be related

**Comment by johnfn** [comment]
Node version 4.2.2.

Manually popping up the signature does not work, either. I see the following error on the bottom of the screen: "Supplied parameters do not match any signature of call target."

**Comment by johnfn** [comment]
Interesting. It must have been due to a collision with another Sublime package, because I went on a cleaning spree earlier today and now I'm noticing it's working again. For instance, installing the GoSublime package seems to break everything.

**Comment by zhengbli** [comment]
It could be. Maybe the callback of the other plugin interfered with ours, as we have no control over which plugin gets the event first. Closing this.

**Comment by johnfn** [comment]
Hm. For future reference, I think that SublimeLinter was also causing a problem with the autocomplete. I eventually started disabling packages one by one until stuff started working again.
