### ISSUE TITLE
How to configure tsc command?

### ISSUE THREAD

**Issue by carlosdubus** [Microsoft/TypeScript-Sublime-Plugin#396]
Where can I specify the tsc bin path and add command switches?

**Comment by zhengbli** [comment]
The plugin is shipped with a copy of tsc.js that you can use for building. Though I'm not sure what you mean exactly by "command switches".

**Comment by DanielRosenwasser** [comment]
For setting options, you'll want to look into adding a [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json).

Right now `tsserver.js` is just bundled in the `tsserver` directory. You can always swap in an alternate version by cloning from https://github.com/Microsoft/TypeScript, performing a build, and copying in the appropriate files from TypeScript's `build/local` directory.

**Comment by carlosdubus** [comment]
I see. I just saw ~/.config/sublime-text-3/Packages/TypeScript/tsserver. I was planning to do exactly that @DanielRosenwasser . Thanks!

**Comment by DanielRosenwasser** [comment]
No problem.

Alternatively, you set this repository in "development mode" ([see here](https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Dev-notes)) where your clone is a sibling directory to the TypeScript clone. You can then run `jake update-sublime` from the TypeScript directory.

**Comment by carlosdubus** [comment]
Great, even better. I will try that. Thanks
