### ISSUE TITLE
Disable analyzing and leaving syntax highlighting only

### ISSUE THREAD

**Issue by NekR** [Microsoft/TypeScript-Sublime-Plugin#402]
How I can disable code analyzing but leaving syntax highlighting enabled? I have few quite big projects open at a same, most of the time I do not close tabs and sublime at all. But with TypeScript plugin it burns out my Macbook so its temperature is like I am playing modern game on high quality. Same on Windows and it takes 1GB+ of memory which isn't good when you have only 8 of it.

**Comment by zhengbli** [comment]
Should be fixed by #406
