### ISSUE TITLE
Implement interface shortcut

### ISSUE THREAD

**Issue by daniell0gda** [Microsoft/TypeScript-Sublime-Plugin#408]
Will we ever have it? 
While using 'implements xxx' on class, you always need to double check what fields I need to implement in my class. It would be super convenient to use some shortcut and if necessary change visibility of these fields.

**Comment by DanielRosenwasser** [comment]
Hey @daniell0gda, this is probably not the appropriate repo for these sorts of questions. The https://github.com/Microsoft/TypeScript/ repo itself is better suited.

That said, a discussion on this exists at https://github.com/Microsoft/TypeScript/issues/5468. Take a look at @RyanCavanaugh's answer on http://stackoverflow.com/questions/14583231/why-typescripts-ambient-interface-implementation-must-be-declared/14587529#14587529 for why the behavior exists today.
