### ISSUE TITLE
Display function arguments after autocomplete

### ISSUE THREAD

**Issue by mbraude** [Microsoft/TypeScript-Sublime-Plugin#41]
The auto-complete is fantastic, but the one major thing missing is help filling in arguments. Right now, after I press enter to insert a function name, I immediate go to definition on the function to see its arguments. Then I go back and try to fill them in. And this gets tedious if the argument is a complex type with lots of constructor arguments.

It would be really great if you could display these to the user after they auto-complete a function name.

**Comment by billti** [comment]
I've implemented the signature help popup in the pull request Fiona referenced (if using ST3 build 3070 or later).  There is also an overloads panel (which works on ST2 also) which shows all signature overloads, and if one is selected, will insert the parameters as snippets that can be typed over.  You can trigger this via Command Palette, or type a '?' inside the opening paren of the argument list.  Details in the README.md.
