### ISSUE TITLE
Tab completion causes source misinterpretation

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript-Sublime-Plugin#413]
This is on the latest version of the plugin with TypeScript 1.7.3 on OS X.

When working with completion on long variable names, a strange issue can pop up. If I work from a blank file and type out:

```js
let SomeLongName = "Hello, World";
console.log(SomeL <tab>
```
(where `<tab>` is pressing of the tab key to trigger autocomplete)

I'll end up with:
```js
let SomeLongName = "Hello, World!";
console.log(SomeLongName);
```

But `SomeLongName` will be squiggly-underlined, with the status bar showing an error:
```
Cannot find name 'SomeLongNameongName'., line 2, column 25
```

The error persists until I reopen the buffer or delete and retype the variable name without using completion.

All relevant editor settings in Sublime Text are set as their defaults.

**Comment by fongandrew** [comment]
Also running into this issue with the plugin on Windows. There is no need to start from a blank file. Pretty much any tab-completion has a decent chance of triggering this issue. This problem has been around since at least TS 1.6.

**Comment by jhockett** [comment]
I have the same issue on Ubuntu.

**Comment by LPGhatguy** [comment]
Wow, I wasn't expecting a one character fix, but I'll be looking forward to the fix shipping.

Thanks, @cristiandima!
