### ISSUE TITLE
False red squiggles under import statement

### ISSUE THREAD

**Issue by larsw** [Microsoft/TypeScript-Sublime-Plugin#415]
![image](https://cloud.githubusercontent.com/assets/63235/11587710/8859d2b2-9a7b-11e5-9f09-c9cc92338617.png)

This compiles fine, but it still shows red squiggles under the import statement. I'm using the latest Typescript Sublime Plugin and typescript 1.7.3

**Comment by billti** [comment]
Can you tell us what the error is? And how you are compiling (i.e. from Sublime or the command-line)?

**Comment by larsw** [comment]
Resolved IT with a tsconfig.json file, specifying the module and jfx options.
