### ISSUE TITLE
Refactor move file

### ISSUE THREAD

**Issue by tamascsaba** [Microsoft/TypeScript-Sublime-Plugin#416]
I want to move file to another location but there is no way :(
like: https://www.jetbrains.com/idea/help/move-refactorings.html

**Comment by tamascsaba** [comment]
???

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript#6487

**Comment by mhegazy** [comment]
this looks like a general suggession and not limited to sublime-text. moving to the ts repo.

and to answer @tamascsaba question, this is a feature that is not supported at the moment you will need to manually move the file and fix your references/imports acaccordingly

**Comment by tamascsaba** [comment]
Thanks, for the answer.
