### ISSUE TITLE
How to avoid implicit type definitions

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript-Sublime-Plugin#418]
I have the following code:

``` ts
foo();
```

And the following `tsdconfig.json`:

```
{ "files": ["main.ts"] }
```

In my example I have forgotten to add the reference path for `foo`’s type definitions, so it will not compile. However, Sublime does not show me any errors, because it is implicitly reading the type definition `foo.d.ts`.

Is there a way to avoid this? Ideally Sublime would only read the files from `tsdconfig.js` and trace the dependency graph from those entry points.

**Comment by DanielRosenwasser** [comment]
Hi @OliverJAsh, do you mean `tsconfig.json`? We don't support (nor have we heard of) `tsdconfig.json`.

**Comment by OliverJAsh** [comment]
Yes, sorry!

**Comment by DanielRosenwasser** [comment]
So just to confirm, when changing the file name to `tsconfig.json`, does that fix the issue?

**Comment by OliverJAsh** [comment]
No, that was a typo. Apologies

**Comment by DanielRosenwasser** [comment]
And you don't have any `/// <reference path="..." />` tags? Can you try adding the `noResolve` flag and seeing if that fixes the problem? Basically, use this `tsconfig.json`:

```json
{
    "files": ["main.ts"]
    "compilerOptions": {
         "noResolve": true
    }
}

**Comment by OliverJAsh** [comment]
If I add that, Sublime shows me errors, but that's because it's now ignoring all references, and that also means the program will fail to compile.

**Comment by zhengbli** [comment]
Hi @OliverJAsh, I don't think we implicitly include `foo.d.ts` if it is not included in either `//// <reference/>` or the file list in your tsconfig.json. If you press `F12` on `foo`, does it navigate you to your `foo.d.ts`? Or if you rename your `foo.d.ts` to something else, does it give you error?

**Comment by OliverJAsh** [comment]
Yes, it navigates me to the type definition.

**Comment by DanielRosenwasser** [comment]
Do you have a minimal repro project so we could diagnose what's going wrong?

**Comment by OliverJAsh** [comment]
I can no longer reproduce.
