### ISSUE TITLE
build .ts file with some .js dependency in the project

### ISSUE THREAD

**Issue by HelloWorldCAT** [Microsoft/TypeScript-Sublime-Plugin#419]
how can I build project with .js dependency?
as I migrate project from VS to sublime+typescript Plugin. in VS we have:
```
    <Content Include="Scripts\Home\Configuration\xxx.js" />
```
how can I configure it in typescript sublime plugin?
thank you!
_____

*Edited by @DanielRosenwasser*

**Comment by DanielRosenwasser** [comment]
You can continue to use MSBuild, or use a tool like Grunt or Gulp. [Here's a page on how you can integrate TypeScript into those tools.](https://github.com/Microsoft/TypeScript-Handbook/blob/a4a9c1d992f627ffe1c62fd57cde18ab993d094c/pages/Integrating%20with%20Build%20Tools.md)

As an aside, these types of questions are better asked on venues like [StackOverflow](http://stackoverflow.com/questions/tagged/typescript), or on the TypeScript [Gitter room](https://gitter.im/Microsoft/TypeScript).
