### ISSUE TITLE
Cannot find name 'System'

### ISSUE THREAD

**Issue by CallMeLaNN** [Microsoft/TypeScript-Sublime-Plugin#424]
**Support for `System` within module**

`System` like from SystemJs normally already loaded since the `script` tag within index.html `head`. So it can be use in other JavaScript/TypeScript files. However using `System` within .ts file complain the above error during build and shown in Error List. However the `System` is actually exist during runtime.

I believe we not supposed to `import 'System'` since `import` it-self is using `System` and `System` does not export it-self. AFAIK technically any module can use `System`.

Use case: I want to dynamically and conditionally load an external script once the module is used.

Step to reproduce: 

- create index.html with systemjs script and load a module
- use `System` in the module.
- open it using this plugin and check for error.

Example test.ts:

    export class Test {
        constructor() {
            console.log(System);
        }
    }

**Comment by DanielRosenwasser** [comment]
Can't you simply write `declare var System: any` and work with that?

**Comment by DanielRosenwasser** [comment]
Additionally, these sorts of questions are better fit for [TypeScript repo](https://github.com/Microsoft/TypeScript) itself.

**Comment by billti** [comment]
Per @DanielRosenwasser comment, this is purely a typing issue, not a Sublime Plugin issue. Please open on the TypeScript repo if you think there is an issue with the TypeScript typings provided by default.

I'd also note, the System global was done away with in the final ES6 spec (see https://esdiscuss.org/topic/system-global ), and no major browser (or Node) implements the System global or an ES6 module loader. If using a shim like SystemJS, then you should use the typings for SystemJS.

**Comment by shyamal-jadav** [comment]
> Can't you simply write `declare var System: any;` at the top level and work with that?
> 

This is working with older version of SystemJS.
But when I try to use 6+ version of SystemJS then it is not working.
