### ISSUE TITLE
Excessive log messages; can I change log level somehow?

### ISSUE THREAD

**Issue by taxilian** [Microsoft/TypeScript-Sublime-Plugin#427]
I'm getting log messages so often I can't troubleshoot other plugins with typescript open. I finally had to edit the plugin and disable the log messages.

Those are "debug" level; is there a config option somewhere to change the log level for the plugin?

**Comment by billti** [comment]
The level should be set to WARN by default, per https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/libs/global_vars.py#L47 . You haven't changed any settings and you're seeing DEBUG level by default?

**Comment by taxilian** [comment]
Indeed; I'm still seeing it, in fact, I just commented out the message that was causing me the most issues, but everything else I'm still seeing the debug messages.

**Comment by zhengbli** [comment]
I have seen some other plugins changed the message level for typescript plugin before. What other plugins do you have install? I can try to repro on my machine

**Comment by taxilian** [comment]
Here is my package control list:

"""
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"1337 Color Scheme",
		"Angular Material Snippets",
		"AngularJS",
		"Block Cursor Everywhere",
		"Color Highlighter",
		"ColorPicker",
		"Copy to HipChat",
		"DocBlockr",
		"Emmet",
		"Gist",
		"Git Config",
		"GitGutter-Edge",
		"Gitignore",
		"Jasmine JS",
		"Jira",
		"JSHint Gutter",
		"Less Tabs",
		"MarkdownEditing",
		"Material Theme",
		"Origami",
		"Package Control",
		"Railscasts Extended",
		"Sass",
		"SideBarEnhancements",
		"Theme - SoDaReloaded",
		"ToggleMinimapOnScroll",
		"TypeScript",
		"Vintageous",
		"Vintageous - Region To Selection",
		"VintageousOrigami",
		"VintageousPluginSurround"
	]
}
"""

I have a system at home that I haven't set up sublime text on yet; I'll have to see if I can find some time to install from scratch and see if I can spot when the issue appears.

**Comment by Chyzwar** [comment]
I have same issue. I found where the problem is. 
https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/libs/logger.py

On line 20 you need to change
log.setLevel(logging.DEBUG) to log.setLevel(logging.WARN)

**Comment by binarious** [comment]
Same here. Any news on this?

**Comment by pope** [comment]
+1 on console log spam. Will you accept a patch to make that change the @Chyzwar suggested?

**Comment by pope** [comment]
+1. I too get the console log spam. Is the correct answer here to do what @Chyzwar suggested? Or is there a more preferable way to handle this? Perhaps a setting?

**Comment by Ivanca** [comment]
@pope there is no setting, which is a bug if you ask me, but one way you can do it from an external Python file without having to modify plugin settings is `logging.getLogger('TS').setLevel(logging.WARNING)` inside a custom plugin of yours or something similar.

**Comment by eriktrom** [comment]
I've submitted a PR to fix this issue - as @Ivanca mentioned, setting the level to `WARN` fixes this issue, although the root cause is due to `logger.addHandler` being effected by the level of the TS server. 

This makes the editor usable again. If anyone sees a way to properly prevent the logging handlers from overlapping their levels(without lots of work) feel free to submit a different fix.
