### ISSUE TITLE
Support for JS Doc using `*.d.ts` files ?

### ISSUE THREAD

**Issue by francoismassart** [Microsoft/TypeScript-Sublime-Plugin#431]
Hi there,
I'm using definition files from [Definitely Typed](http://definitelytyped.org/) (you know, the files ending with `.d.ts`) in my project and some of them contains [JS Doc comments](http://usejsdoc.org/index.html).

It would be amazing if the Sublime Plugin could parse these comments and use them like we see it in [this blog post](http://blogs.msdn.com/b/typescript/archive/2013/01/21/announcing-typescript-0-8-2.aspx).

Are you planning to support JS Doc's ?

Thank you for the reply.

**Comment by mhegazy** [comment]
Sublime text plugin already support loading information from JSDoc comments today:

![image](https://cloud.githubusercontent.com/assets/8000722/12591931/06e3b446-c41f-11e5-950a-fa52d1c4f2ed.png)

**Comment by francoismassart** [comment]
@mhegazy I can see that you are using Windows, I'm on Mac OS with Sublime 2, maybe this is not available for Sublime 2 or only on Windows ?
What do you do to see the tooltip ? Just a simple "mouseover" ?
I did try to reproduce your screenshot... Autocompletion works fine but no JS Doc support on my machine...

**Comment by zhengbli** [comment]
@francoismassart I don't think sublime 2 even supports tooltips. And FYI none of ST2 or ST3 supports mouse events, so it is difficult to implement "mouseover".

**Comment by francoismassart** [comment]
OK then it is probably just because I'm sing ST2,

Thank you for your help.
