### ISSUE TITLE
No syntax coloring in IO wrapper

### ISSUE THREAD

**Issue by larskris** [Microsoft/TypeScript-Sublime-Plugin#434]
I'm not able to to get code inside IO wrapper to show syntax coloring. In the README it looks like it should be possible

[Screenshot of the code](http://i.stack.imgur.com/j3pbb.png)
Rows 6 to 11 are yellow and I'd prefer if it had syntax coloring.
Is there a way to get it that way or is that not a feature?

I'm using OS X v10.11.3 and Sublime Text 3 Build 3083

**Comment by larskris** [comment]
Typing my html code in a separate file as a workaround
```
@Component({
    selector: 'app',
    templateUrl: 'dev/template.html'
}) 
```

**Comment by zhengbli** [comment]
This is because decorators are not currently supported in the tmLanguage grammar file. [A bug in the TypeScript-tmLanguage repo](https://github.com/Microsoft/TypeScript-TmLanguage/issues/8) was filed for this.
