### ISSUE TITLE
Shortcuts documentation

### ISSUE THREAD

**Issue by artemsnisarenko** [Microsoft/TypeScript-Sublime-Plugin#439]
Readme missing signature popup navigation shourtucts (`alt+up`, `alt+down`). I've seen similar issue in recent history. Why not remove the duplication and just link to the sublime-keymap file? Thus avoid not documented shortcuts, save time for people who don't know where to look for them.

**Comment by zhengbli** [comment]
Good point. Will update soon.

**Comment by zhengbli** [comment]
Close as the document was updated.
