### ISSUE TITLE
Hindered snippet complition

### ISSUE THREAD

**Issue by artemsnisarenko** [Microsoft/TypeScript-Sublime-Plugin#441]
Typed input `funct<tab>` expands into `function` keyword not function snippet. To get snippet you have to type `func<esc><tab>`.  Precise trigger should have higher priority.

I propose adding 'snippet' as standalone autocompletion category.

**Comment by zhengbli** [comment]
It is more of a matter of preference. IMO it is a bit inconsistent for people who don't use the snippet function to see different results for typing `funct<tab>` and `func<tab>`. You can type `tab` twice to get to the snippet.
