### ISSUE TITLE
tsconfig files to allow directories?

### ISSUE THREAD

**Issue by mattiLeBlanc** [Microsoft/TypeScript-Sublime-Plugin#443]
Hi,
I am using the Error List function in Sublime.
However, I have no files defined because I find it a bit redundant to register a file every time I created a new file in my project.
So I removed the file option which makes it load all files as standard behaviour.

So the Error list worker process is freaking out about some of the definition files (not maintained by me).
I don't want to see those errors but it happens because of all the files are loaded.
It would help me, if I could add directories with a wildcard to the file section in the tsconfig.
That way I can include the whole view section and components, but exclude the typings folder.

**Comment by billti** [comment]
We already allow you to exclude specific directories via the `excludes` property (see https://github.com/Microsoft/TypeScript/wiki/tsconfig.json ). Wildcard support (i.e. *globbing* patterns) are coming in this pull request: https://github.com/Microsoft/TypeScript/pull/5980 .

**Comment by mattiLeBlanc** [comment]
Awesome. Thank you.

**Comment by mattiLeBlanc** [comment]
@billti Actually excluding the typings file drops the whole type checking system in Sublime, so that doesn't work.

I just manually included my top level typing files
```
{
    "filesGlob": [
        "./typings/browser.d.ts",
        "./typings/custom.d.ts",
        "./server/**/*.ts",
        "./client/**/*.ts"
    ],
    "compilerOptions": {
        "module": "commonjs"
    },
    "compileOnSave": false,
    "buildOnSave": false

}
```
but I still get all the duplicate messages in my typing files.
Is there anyway to NOT have the typing messages in the Error List?

**Comment by zhengbli** [comment]
Excluding folders should not turn off type checking system in Sublime. Also, `filesGlob` field is not currently supported by tsconfig.json. All options available in tsconfig.json can be found in this 
[wiki page](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json).

Unfortunately before the wildcard file name pattern was merged, there is no other way to define a project except using either `files` array or `exclude` array.
