### ISSUE TITLE
Exception on signature popup (Sublime 3107)

### ISSUE THREAD

**Issue by jgoz** [Microsoft/TypeScript-Sublime-Plugin#448]
On Sublime 3107, Windows 8 64-bit, plugin version 4a1f6362509:

When using Alt+, to activate the signature popup, the following exception is produced in the console:

```
Traceback (most recent call last):
  File "C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\typescript\libs\work_scheduler.py", line 154, in on_scheduled
    job()
  File "C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\typescript\libs\work_scheduler.py", line 125, in do_work
    worker(work_done)
  File "C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\typescript\libs\popup_manager.py", line 69, in get_signature_data
    self.proxy.async_signature_help(filename, point, '', on_done)
AttributeError: 'NoneType' object has no attribute 'async_signature_help'
```

**Comment by jgoz** [comment]
Note that if I set the file log mode to DEBUG, this issue disappears.

**Comment by zhengbli** [comment]
That is weird. The log mode is not supposed to affect anything. Do you have a code snippet that can repro this exception?

**Comment by jgoz** [comment]
OK, I have a guess as to what's happening.

Here is the console output before the above exception is produced:

```
Packages/TypeScript/popup.html
Path of tsserver.js: C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsserver.js
Path of tsc.js: C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsc.js
Trying to spawn node executable from: node
ref view not found
```

And here it is when I move usage of `get_popup_manager()` inside [`on_text_command`](https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/aef0b925b24be3df2eeaed2bbb5fcd1c8ce9b1e6/typescript/listeners/tooltip.py#L34) to inside the `if` block:

```
Path of tsserver.js: C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsserver.js
Path of tsc.js: C:\Users\johng\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsc.js
Trying to spawn node executable from: node
ref view not found
Packages/TypeScript/popup.html
```

Notice the location of `Packages/TypeScript/popup.html` in the 2nd log output.

What I think is happening is the new Sublime version or one of my plugins is issuing an `on_text_command` event _before_ the typescript server is connected. When this happens, `get_popup_manger` is called, which creates a `PopupManager` instance with `None` for `proxy` because the server proxy hasn't been initialized.

Lazily initializing the `PopupManager` in the `tooltip/on_text_command` function seems to fix this, but I'm not sure if it's the best approach. I can open a PR with that change if you like.

**Comment by zhengbli** [comment]
@jgoz hijacking the event listen could very likely cause the issue. A PR will be very welcomed!
