### ISSUE TITLE
next/previous error

### ISSUE THREAD

**Issue by co-dh** [Microsoft/TypeScript-Sublime-Plugin#451]
Can you please provide the command for next/prev error? I know you can build and get the errors, 
but it's another step, and slow. Also you can open error list, however, click on the lines in error list do nothing.

**Comment by co-dh** [comment]
Ok, I figured it out myself:
,{ "keys": [" ", "p"], "command": "typescript_go_to_error", "context": [{ "key": "setting.command_mode"}]}
The go_to_error is undocumented, and there is no command for it. 
worth a PR.

**Comment by co-dh** [comment]
ok, this typescript_go_to_error command only works when error list is open, and only in the error list panel. It would be better to be able to go to error in the source code view, without even open error list.

**Comment by DanielRosenwasser** [comment]
I think this would be very useful. VS Code has support for this.
