### ISSUE TITLE
Cannot find Typescript package in sublime

### ISSUE THREAD

**Issue by FrancescoMussi** [Microsoft/TypeScript-Sublime-Plugin#456]
Searching for the package 'Typescript' inside Sublime Text 3 (build 3103) nothing appears.
Am I the only one?
Am I doing something wrong?

**Comment by zhengbli** [comment]
@FrancescoMussi It may be that you already have the plugin installed. Can you try "list packages" to see if the plugin is there in your command palette?

**Comment by capcom-r** [comment]
`Ctrl-Shift-P`, type in `Install` and `Enter`
Then search for `TypeScript` and it should be there.

If you don't see it, try the snippet here https://packagecontrol.io/installation
