### ISSUE TITLE
Completion list vanishes when typing $

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript-Sublime-Plugin#457]
Code:
```ts
var x = { $foo: 0 };
x. //<- type $ here
```
![image](https://cloud.githubusercontent.com/assets/6685088/13646307/b728faec-e5e3-11e5-9f5d-893b6ed4e011.png)

Result: When typing `$`, the completion list closes

Expected: Should stay up

**Comment by mhegazy** [comment]
looks like https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/125

**Comment by RyanCavanaugh** [comment]
From the PR referenced in that bug (@zhengbli):

> Although if I start typing after the dollar sign, the completion list is still not right. However that should be a different issue, I'll file it elsewhere.
