### ISSUE TITLE
Documentation of `typescript_tsdk` setting

### ISSUE THREAD

**Issue by garkbit** [Microsoft/TypeScript-Sublime-Plugin#458]
Lack of documentation surrounding the `typescript_tsdk` setting is causing consternation among some users (see #213). I suspect those of us running a different version of TypeScript from that packaged with the plugin, but that may not be the case. Documenting the existence and usage of `typescript_tsdk` would be helpful.

I'm happy to submit a pull request if someone has a recommendation for where it would be most appropriate to document the setting.

**Comment by mhegazy** [comment]
something like https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#sublime-text?

**Comment by NekR** [comment]
Does relative paths work in `typescript_tsdk `? e,g, `"typescript_tsdk": "./node_modules/typescript/lib"` so it will pick up different/local TS version for different projects.

**Comment by garkbit** [comment]
@mhegazy heh, yep, something exactly like that. My bad for not finding it.
