### ISSUE TITLE
After build how to i got minified js

### ISSUE THREAD

**Issue by gsivaprabu** [Microsoft/TypeScript-Sublime-Plugin#459]
Hi,

This is my code

```ts
class Car {
	engine: string;
	constructor(engine: string) {
				this.engine = engine;
	}

	start(argument) {
		alert('Engine Started: ' + this.engine);
	}

	stop(argument) {
		alert('Engine Stopped: ' + this.engine);
	}
}

window.onload = function () {
	var car = new Car('V8');
	car.start();
	car.stop();
}
```

**use build with below parameters**

```cmd
--target es5 --watch
```

How to i got minified js after build completed any settings are parameter need to changed

**Comment by mhegazy** [comment]
The typescript compiler does not support minification. you will need to use a minifier like [uglify](https://www.npmjs.com/package/uglify-js) or [others](http://www.fusioncharts.com/blog/2014/06/5-excellent-javascript-minification-tools-to-improve-your-code-performance/), and pipe the js output of the ts compiler, to it.

e.g.:

```cmd
tsc --soruceMap a.ts --out a.js
uglifyjs --compress --mangle  --in-source-map a.js.map  --output  a.min.js a.js
```

**Comment by gsivaprabu** [comment]
Thanks lot @mhegazy
