### ISSUE TITLE
Cannot paste in unsaved TypeScript file

### ISSUE THREAD

**Issue by poke** [Microsoft/TypeScript-Sublime-Plugin#461]
The TypeScript plugin overwrites the <kbd>Ctrl+V</kbd> keyboard shortcut to call the `typescript_paste_and_format` command instead. However, as per the logic in [base_command.py](https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/commands/base_command.py), these commands can be disabled.

This is usually not a problem when the TypeScript commands all require e.g. a path to resolve dependencies and things, however if the `typescript_paste_and_format` command fails to run, then the user cannot paste content, leading to a very frustrating experience.

So for new and unsaved files, the commands *are* disabled. This is because the [`view_helpers.is_typescript`](https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/libs/view_helpers.py#L99) check goes against the view’s file name. If there is no filename (which is the case when the file is new), then the function returns false, and the command gets disabled.

So this is not really an ideal check. Ideally, the commands should be enabled and do as much as it can that does not require an actual file path. For formatting, one would think that this should work even without a physical file. And even if it was not possible, the command should delegate back to the default paste command in that case.

So there are multiple ways to fix this (which is the reason why this is not a pull request):

- Change the `is_typescript` to return true when the file is a typescript file that was not saved. This could potentially break commands that really depend on a file path.
- Split up the `is_typescript` into `is_typescript` and `has_filepath` or something and change the commands so they only require what they actually require (a paste and format could then only require typescript syntax, while auto completion from imports may require paths). This would be the ideal solution as it makes the command usable as soon as they can, but it could be a bit tedious to implement, especially when there’s an overlap in command’s functionality.
- Just fix the paste and format command, so it overrides the `is_enabled` and properly runs even when the file is unsaved.
- Modify the paste and format command so it can always run but delegates back to the default paste command when the `is_typescript` returns false.

**Comment by caJaeger** [comment]
I have this issue as well but it doesn't matter whether the file is saved or not. I can paste in any other file type, but .ts just wont work, quite annoying.

**Comment by dachibro** [comment]
@caJaeger +1

I'm probably just going to disable the paste and format command, or use a different plugin.  All I really want is something for syntax highlighting.

**Comment by poke** [comment]
Btw. I’m totally open to submitting a pull request that fixes this, if the project owners can decide on which solution to follow through. I just didn’t do it because there is no clear favored way to do it.

**Comment by mhegazy** [comment]
@zhengbli thoughts?

**Comment by zhengbli** [comment]
Auto formatting options are already changed to false in master (though haven't released yet). But I do agree we should detect the unsaved buffer and not intercept the pasting. I'll do it when I've got time, also PRs are welcomed :)

**Comment by poke** [comment]
@zhengbli Do you have any preference as to how this should be solved? Considering the list of options in my original post—of course, also open to other suggestions since I didn’t dig too deep into the plugin at that point, so there might be a better way.

**Comment by zhengbli** [comment]
@poke Thanks for your thoughts. I think changing the `is_typescript` function would lead to unpredictable behavior as it is used in many places. Modifying the `typescript_paste_and_format` command to be always enabled, but redirects to the default paste command if `is_typescript` returns false seems like the cleanest solution to me.

**Comment by poke** [comment]
Alright, I’ll try to find some time to make a PR for that then!
