### ISSUE TITLE
Custom version

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript-Sublime-Plugin#463]
I realise that this plugin bundles TypeScript, which sometimes means the version you are compiling your project to differs from the version in this plugin. Is there any way around that, i.e. allowing the user to configure the version? Or, perhaps, the version could be fetched from npm so it's always up to date?

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#sublime-text

**Comment by mhegazy** [comment]
looks like the second time we got this within a week(https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/458). we should add the documentation to the main page.
