### ISSUE TITLE
Is it possible to specify multiple typings directories ?

### ISSUE THREAD

**Issue by kylezeeuwen** [Microsoft/TypeScript-Sublime-Plugin#465]
Aside from creating a tsconfig.json in my project root, is there a way to specify one or more locations where the sublime3 typescript plugin will look for .d.ts files ?

Thanks

**Comment by DanielRosenwasser** [comment]
You can just include the `main.d.ts` files from several typings directories. Alternatively, if you're using the `excludes` field, the compiler automatically picks any `.d.ts` files in non-excluded subdirectories.

As a heads up, this sort of thing is probably better asked over at a site like StackOverflow.
