### ISSUE TITLE
Please help, cannot setup TypeScript-Sublime-Plugin to work

### ISSUE THREAD

**Issue by jeud** [Microsoft/TypeScript-Sublime-Plugin#468]
I have installed node and typescript.

On the command line I can successfully type `node --version`, `tsc --version` and `typings --version`

I have installed *TypeScript-Sublime-Plugin* on my sublime text 3

This is my screen, no Intellisenses, no errors / warnings

![](http://i.cubeupload.com/6jBnqp.png)

![](http://i.cubeupload.com/G3Gb0Y.png)

> I see the new command Toos -> Build System -> TypeScript was installed with the plugin but pressing `Ctrl` + `B` does nothing, manually click on the build menu also does nothing
>
> I have tried this plugin with my Ubuntu notebook everything works fine out-of-the-box

Please guide me thought how to setup *TypeScript-Sublime-Plugin*, thanks.

**Comment by DanielRosenwasser** [comment]
If you reopen Sublime with that file and open up the Sublime Console (which I believe you can find under the `View` menu), what is the output you see?

**Comment by jeud** [comment]
@DanielRosenwasser 
![](http://i.cubeupload.com/fHcVaH.png)
Is it about `node_path`, if so how to set it up?

**Comment by DanielRosenwasser** [comment]
From [the wiki](https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Tips-and-Known-Issues).

> The plug-in looks for the installed node executable using the PATH environment variable of the Sublime process and also in the directory '/usr/local/bin'. If your node installation placed the node executable elsewhere, then add the 'node_path' setting to your Preferences.sublime-settings file. The value of the 'node_path' setting should be the pathname of the node executable as in '/usr/myinstalldir/node'. You can look for the message 'spawning node module ...' in the Sublime console view (ctrl + ` or View -> Show Console). The line of text after this will indicate whether the plug-in was able to find the node executable.

Let us know if that works.

**Comment by jeud** [comment]
@DanielRosenwasser 
After working around, starting Sublime from menu shortcut works fine without doing anything extra this should be because starting Sublime this way can load `PATH` environment variable

I have had this problem because I usually start Sublime from the command line with `c:\Program Files\Sublime Text 3\sublime_text.exe .` to start Sublime with current working directory

I have tried `node_path` setup with almost every possibilities
```
{
    "node_path": "..."
}
```
-  "c:/Program Files/nodejs"
-  "c:\\Program Files\\nodejs"
-  "c:/Program Files/nodejs/node.exe"
-  "c:\\Program Files\\nodejs\\node.exe"
-  "node.exe"
Neither of them seems working, is the problem about the different the way Sublime being started, please suggest more.

Thanks

**Comment by jeud** [comment]
@DanielRosenwasser  Sorry to tag you again, I believe the problem is not about the `node_path` setup because when I tried to have **wrong** path on purpose e.g. `"node_path": "c:/node.exe"`, I must see

```
Path of node executable is configured as: c:/node.exe
Configured node path is not a valid executable.
```

Because of I already have the `PATH` environment variable on my Windows so I actually don't have to override the `node_path` in the Sublime at all

So the problem **only remains** when starting Sublime from the command line from both `c:\Program Files\Sublime Text 3\subl.exe` and `c:\Program Files\Sublime Text 3\sublime_text.exe` executables, I'm sure that the problem is not about the path because there is no errors as above, it seems to me like starting Sublime from the command line cannot access the **node process** somehow, as error shown below

```
Trying to spawn node executable from: node
2016-04-19 02:24:40,835: 5588: ERROR: can not send request; node process not running
```

> I also tried to open my terminal window using administrator right to start Sublime from the command line, but also having the same error

**Comment by DanielRosenwasser** [comment]
@zhengbli can you take a look at this?

**Comment by zhengbli** [comment]
It is possible that when you start sublime from command line, the `PATH` isn't loaded properly. If you don't set the `node_path`, the plugin will use `node` without any path instead, and will NOT check if it is an executable. So can you try setting the `node_path` to `C:/Program Files/nodejs/node.exe`, and see in your console if you find the `Configured node path is not a valid executable.` error message.

**Comment by jeud** [comment]
@zhengbli 
I only see the error below only when trying to set the wrong path on purpose
```
Path of node executable is configured as: c:/xxx/node.exe
Configured node path is not a valid executable.
```

Therefore I'm quite sure that this issue is not about the path at all, according to my test only starting Sublime from the command line causes me this issue because Sublime is not capable to start the node process (while starting Sublime from Windows menu icon is capable with the same configuration), I really have no ideas why

So I believe this issue is about the different way to execute Sublime on Windows has different capability to access node process

Mine is Windows 7 64 bit

**Comment by jeud** [comment]
This issue has been solved when I'm upgrading to use Windows 10
Thanks
