### ISSUE TITLE
Shortcuts won't work

### ISSUE THREAD

**Issue by scherman** [Microsoft/TypeScript-Sublime-Plugin#475]
I have everything of the plugin working but the shortcuts. For some reason, i cannot, for instance, trigger auto completion through Ctrl+Space, while sublime's default shortcuts work fine(e.g Ctrl+/ to comment).
Just to be clear, the auto completion works wine, the only problem here is that i cannot trigger it through shortcuts

Do you know what is going on?

**Comment by mhegazy** [comment]
@zhengbli any ideas?

**Comment by zhengbli** [comment]
Do you have customized key-maps? The `auto_complete` trigger (`ctrl + space`) is a sublime default one, we didn't add it. You can view the key mapping item in your `Key bindings - Default` menu item:
```
    { "keys": ["ctrl+space"], "command": "auto_complete" },
	{ "keys": ["ctrl+space"], "command": "replace_completion_with_auto_complete", "context":
		[
			{ "key": "last_command", "operator": "equal", "operand": "insert_best_completion" },
			{ "key": "auto_complete_visible", "operator": "equal", "operand": false },
			{ "key": "setting.tab_completion", "operator": "equal", "operand": true }
		]
	},
```

**Comment by zhengbli** [comment]
Close as lack of response. Please reopen if the issue still exists.
