### ISSUE TITLE
Intellisense stopped working, cannot find cause

### ISSUE THREAD

**Issue by juvezxy** [Microsoft/TypeScript-Sublime-Plugin#480]
The plugin worked fine for several days until yesterday, when suddenly all features like syntax-checking, auto-complete and signature popup stopped working. Below is the console output after restarting with a .ts file. Any idea what might have gone wrong?

> startup, version: 3114 osx x64 channel: stable
executable: /Users/andrew/Desktop/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/andrew/Library/Application Support/Sublime Text 3/Packages
state path: /Users/andrew/Library/Application Support/Sublime Text 3/Local
zip path: /Users/andrew/Desktop/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.199215
using gpu buffer for window
startup time: 0.259761
first paint time: 0.276348
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin TypeScript.main
2016-05-26 16:31:40,816: 140735228440576: INFO: Logging configured to log to file: /Users/andrew/Library/Application Support/Sublime Text 3/Packages/TypeScript/typescript/TS.log
2016-05-26 16:31:40,847: 140735228440576: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: /Users/andrew/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/andrew/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/local/bin/node
ref view not found
Package Control: Skipping automatic upgrade, last run at 2016-05-26 16:08:45, next run at 2016-05-26 17:08:45 or after
Packages/TypeScript/popup.html

**Comment by ethanresnick** [comment]
@juvezxy I'm having this same problem. How did you solve it?
