### ISSUE TITLE
See returning value of a function

### ISSUE THREAD

**Issue by nschurmann** [Microsoft/TypeScript-Sublime-Plugin#481]
On visual studio code, if you hover the mouse on a function it will show you the returning value of the function. How can i achieve this behaviour with this plugin?

**Comment by DanielRosenwasser** [comment]
You can use quick info by triggering `Ctrl-T, Ctrl-Q`.

![Quick info](https://raw.githubusercontent.com/Microsoft/TypeScript-Sublime-Plugin/master/screenshots/quickinfo.gif)

See more on our [features list](https://github.com/Microsoft/TypeScript-Sublime-Plugin#features).
