### ISSUE TITLE
Cmd-V does not work with plugin enabled

### ISSUE THREAD

**Issue by mc10** [Microsoft/TypeScript-Sublime-Plugin#485]
This is really strange, but with this plugin enabled and TypeScript/TypeScriptReact selected as the language, Cmd-V (on a Mac) no longer does anything. However, choosing Edit -> Paste from the menu works. Any idea?

**Comment by subhaze** [comment]
I've ran into this as well, but don't have a way to replicate this consistently. It appears to have something to do with `typescript_paste_and_format`

**Comment by poke** [comment]
Likely duplicate of #461.

**Comment by zhengbli** [comment]
This should be fixed in the latest release. @mc10 @subhaze can you confirm? Thanks

**Comment by subhaze** [comment]
I've not noticed this issue anymore, thanks!

**Comment by mc10** [comment]
I haven't run into this bug lately so I'll close for now, thanks!
