### ISSUE TITLE
ExperimentalDecorators error when using unknown compilerOptions key

### ISSUE THREAD

**Issue by ghetolay** [Microsoft/TypeScript-Sublime-Plugin#486]
I'm getting the ExperimentalDecorators error on all my components as soon as I use a compiler option unknown to the plugin.

I'm using the new ```lib``` property, but bug appears for any *invalid* property name.

I tried using ```typescript_tsdk``` but it didn't make any difference (Both typescript.js and tsc.js have ```lib``` defined as a valid option).

The ExperimentalDecorators error may be a side effect of something else but I didn't noticed any other error even in the console.

**Comment by mhegazy** [comment]
the error is caused by the server failing to parse the config file, and considering it invalid. so it assumes it does not exist (this should behave better in the next release). setting `typescript_sdk` should make it work though.. what version of `typescript@next` did you use?

**Comment by ghetolay** [comment]
Well sorry I tried again and setting ```typescript_tsdk``` works. 
I've probably been using the wrong settings file.

I may suggest an update to the readme.md, it does not states which settings file to use (Plugin).

Now the issue was more about the fact that an unknown property makes the server fail but if you say it will behave better in next release this means this issue is already addressed.
