### ISSUE TITLE
update to support typescript@next with baseUrl, paths, rootDirs in tsconfig

### ISSUE THREAD

**Issue by gdi2290** [Microsoft/TypeScript-Sublime-Plugin#488]
(this is more for anyone looking to get this working locally)
for anyone else trying to get this to work. open your sublime packages and replace the files in tssever with the ones in your typescript version lib folder
<img width="823" alt="screen shot 2016-07-01 at 10 55 15 pm" src="https://cloud.githubusercontent.com/assets/1016365/16538628/ef826680-3fde-11e6-900a-b071285b8c9b.png">

**Comment by mhegazy** [comment]
Or you can just set `typescript_tsdk` user setting.

see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Nightly%20Builds.md#sublime-text for more details.
