### ISSUE TITLE
How to show red squiggles on errors?

### ISSUE THREAD

**Issue by farzher** [Microsoft/TypeScript-Sublime-Plugin#489]
I've seen screenshots like this:

![image](https://cloud.githubusercontent.com/assets/1005136/16539399/e054e170-400f-11e6-89c9-e5aeeb850281.png)

I can't figure it out; is that a different plugin? (I tried other plugins but they were buggy, it'd be nice if this plugin could do it)

**Comment by mhegazy** [comment]
What version of ST are you using? i see it working fine on ST3 build: 3114

**Comment by farzher** [comment]
![image](https://cloud.githubusercontent.com/assets/1005136/16549165/e6d48ef0-4169-11e6-87a3-131cda6f9f98.png)

Are you sure it's not from a different plugin? I've reinstalled TypeScript plugin multiple times. Not sure what I could be doing wrong

**Comment by DanielRosenwasser** [comment]
Hey @farzher, have you tried playing around with theme settings to see if that has anything to do with it?

**Comment by farzher** [comment]
It's not my theme's fault because red error lines work when I install ArcticTypescript (but I have other issues with that plugin)

**Comment by farzher** [comment]
@DanielRosenwasser apparently that logic isn't sound, because it is my theme's fault. Other color schemes show the red squiggles. I'll comment again when I figure out how it's my theme's fault, maybe we can add a fix so that it'll work in this case too (apparently ArcticTypescript is able to work fine)

**Comment by farzher** [comment]
This made it invisible:

```
<dict>
	<key>scope</key>
	<string>keyword</string>
	<key>settings</key>
	<dict>
		<key>foreground</key>
		<string>#bB7Dbf</string>
		<key>background</key>
		<string>#9B9FfD10</string>
	</dict>
</dict>
```

(almost completely transparent background on scope `keyword`), maybe the typescript error scope should be changed. I can't figure out how to fix it on my theme without messing up actual keywords.
