### ISSUE TITLE
Set Syntax: Babel isn't allowed

### ISSUE THREAD

**Issue by farzher** [Microsoft/TypeScript-Sublime-Plugin#491]
It looks like I have to use the TypeScript syntax bundled with this plugin, otherwise it doesn't work properly. Is there anyway to use other syntaxes? The babel syntax looks way better for ES6 code

TypeScript:
![image](https://cloud.githubusercontent.com/assets/1005136/16610004/23dbac3a-4326-11e6-821c-301e81b8e674.png)

Babel:
![image](https://cloud.githubusercontent.com/assets/1005136/16610006/25dcd87e-4326-11e6-83ad-0bde8755819c.png)

**Comment by zhengbli** [comment]
The thing is that changing the syntax also changes how the editor "thinks of" this file, and the plugin replies on that to decide should it be handled or not. 

An alternative way is to edit the babel syntax file (*.tmLanguage), change the
```
<key>scopeName</key>
<string>source.ts</string>
```
Part, make sure the scopeName is source.ts or source.tsx, it should work.
