### ISSUE TITLE
Signature tooltip keep showing unnecessarily

### ISSUE THREAD

**Issue by rudyhuynh** [Microsoft/TypeScript-Sublime-Plugin#492]
![](http://i.imgur.com/Nfdk3je.gif)
This is just annoying :(
Is there anyway to turn it off then trigger by shortcut keys?

**Comment by gdi2290** [comment]
+1000

**Comment by DanielRosenwasser** [comment]
Does `Alt`+`,` get rid of it, or does it just re-trigger it?

**Comment by DanielRosenwasser** [comment]
I'll take that as a yes. :smile:

**Comment by gdi2290** [comment]
etc also works but sometimes it doesn't work. the workaround is clicking on js outside of `@Component` and avoiding `()` in the template. We ended up commented it out in the python file

**Comment by kulikalov** [comment]
still have this issue. Is it possible to change tooltip position? Given that most devs use 80-char long lines and have monitors wider than that, I'd say, display tooltip on the right side of the editor window. Can I customize that in package settings?

**Comment by PatrickJS** [comment]
i just moved to vs code like everyone else :/
