### ISSUE TITLE
Typescript 2: *.js imports are not recognized as modules

### ISSUE THREAD

**Issue by Narretz** [Microsoft/TypeScript-Sublime-Plugin#493]
In Typescript 2, we can import *.js files and typescript will look for a corresponding *.d.ts file, too (instead of a *.js.d.ts file):  https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#module-identifiers-allow-for-js-extension

This doesn't currently work for me in Sublime. *.js files are always marked as "cannot find module".
When I run tsc on such a file I get the expected output:

```
File 'moment.ts' does not exist.
File 'moment.tsx' does not exist.
File 'moment.d.ts' exist - use it as a name resolution result.
Resolving real path for 'moment.d.ts', result 'moment.d.ts'
```

Is this expected behavior? I assume Sublime Typescript uses the globally installed Typescript, right? Should this work automatically, then?

edit: Looks like I'll have to set the path to the global typesript instead

**Comment by Narretz** [comment]
Ok, you can set   
`"typescript_tsdk": "C:/Users/Martin/AppData/Roaming/npm"`

In your Preferences.sublime-settings User file

**Comment by gustavotaveira** [comment]
Where i can find Preferences.sublime-settings on windows
