### ISSUE TITLE
Custom settings should be read from Packages/User/Typescript.sublime-settings

### ISSUE THREAD

**Issue by Narretz** [Microsoft/TypeScript-Sublime-Plugin#494]
Currently, you have to set 
`"typescript_tsdk": "C:/Users/Martin/AppData/Roaming/npm"`

in your `Packages/User/Preferences.sublime-settings` which is imo wrong as only core settings should be added to this file.

**Comment by zhengbli** [comment]
> Currently, you have to set 
"typescript_tsdk": "C:/Users/Martin/AppData/Roaming/npm"

Not really, you can set the option in your `Packages/TypeScript/Preferences.sublime-settings` too if you want. It is just that settings in this file will be overwritten by the settings in `User/Preferences.sublime-settings`, so it might be safer to suggest that.
