### ISSUE TITLE
Running into "Cannot find module" errors

### ISSUE THREAD

**Issue by mc10** [Microsoft/TypeScript-Sublime-Plugin#497]
I'm working on a project which is not organized ordinarily; here's the project structure

```
app/
  files/
    src/ <-- files are in here
      bar.ts
      foo.tsx
      ...
  more/
    ...
```

All of my TypeScript files are located in that `src` file, but the Sublime project is at the `app` level. I'm running into "Cannot find module" errors for all my imports (which are ES6-style) in the plugin, but I'm compiling fine via running `tsc` on the command line. I've tried adding a `tsconfig.json` file into the `src` folder, but the plugin doesn't seem to be affected. Any ideas?

**Comment by mhegazy** [comment]
what version of the compiler are you using? the plugin? and can you share your tsconfig?

**Comment by mc10** [comment]
I'm currently using the plugin, but I run the node.js-installed version of `tsc` on the command line.
My .tsconfig is in `src/` and is very simple:
```json
{
  "compilerOptions": {
    "jsx": "Preserve",
    "target": "es5"
  }
}
```

**Comment by mhegazy** [comment]
can you share the project?

**Comment by mc10** [comment]
Going to close since I haven't used this plugin in ages.
