### ISSUE TITLE
Popup styling

### ISSUE THREAD

**Issue by oivva** [Microsoft/TypeScript-Sublime-Plugin#498]
How can I customize popup styles in the color scheme? If I can't please add ability to customize.
Now, plugin overrides default popup colors (defined in the color scheme).

Thanks :wink:

**Comment by nathggns** [comment]
+1

**Comment by zhengbli** [comment]
You can just directly edit the https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/popup.html

**Comment by oivva** [comment]
@zhengbli Yes, I find this solution. But we need ability to change popup colors depending on the active color scheme.
