### ISSUE TITLE
Use globally installed typescript by default

### ISSUE THREAD

**Issue by Igonato** [microsoft/TypeScript-Sublime-Plugin#499]
Right now the plugin checks for `typescript_tsdk` value in the sublime settings, and, if it isn't present, it uses `tsserver.js` from the plugin directory. 

I believe it should check if there is a tsserver available on PATH and use that (if `typescript_tsdk` isn't set obviously). I can't think of a scenario where a developer has typescript globally installed and wants to use one that is shipped with an editor plugin.
Also It would be cool to check if there is a locally installed typescript in a project folder and use it for that specific project.

If you guys are cool with this proposal, I will be happy to work on a PR for this.

Cheers!

**Comment by mhegazy** [comment]
Why is not `typescript_tsdk` sufficient? you can point it to your global npm install of TypeScript.

**Comment by Igonato** [comment]
It is sufficient when you know about it. Personally I learned that is exists while trying to figure out why does the plugin give me errors when command line compiler works fine. So expected behavior was that it should use installed typescript, am I wrong?

**Comment by Igonato** [comment]
Also many other sublime plugins use installed cli tools, SublimeLinter family for example.

**Comment by mhegazy** [comment]
> Personally I learned that is exists while trying to figure out why does the plugin give me errors when the command line compiler works fine.

not every one uses globally installed tools, others use locally installed versions of typescript. this would be confusing in this scenario, if you happen to have a globally installed version of TS that does not match the one you use.

**Comment by DanielRosenwasser** [comment]
Sounds to me more like this is a problem of searchability. Currently if you look up "use a different version of typescript sublime" in Google, you'll get nothing.

**Comment by zhengbli** [comment]
I actually agree with this change. If the user has a globally available typescript version, very likely that's what he/she wants to use for other things by default, then why not sublime. Then the user can "opt-in" the plugin built-in version of tsserver by specifying that setting.

**Comment by rafaelbiten** [comment]
Wouldn't it make more sense to first look for a local version of TypeScript, (installed per project via  `npm i -D typescript`) to avoid problems with legacy projects using older versions of TS, then check for a global and only then fallback to whatever we currently have?

**Comment by lubieowoce** [comment]
> Wouldn't it make more sense to first look for a local version of TypeScript, (installed per project via npm i -D typescript) to avoid problems with legacy projects using older versions of TS, then check for a global and only then fallback to whatever we currently have?

sorry to dig up an old issue, but does anyone know a way to use a local typescript version (`$current_project/node_modules/typescript`)? i just spent a long while trying to figure out [an issue with jsx that required tsc>=4.1](https://stackoverflow.com/a/64969461) and updated every damn `tsc` i could find only to realize the plugin bundles its own (`3.9.1`, since updated). i'd love to avoid problems like this in the future!
