### ISSUE TITLE
Multiple tsconfig.json files in project

### ISSUE THREAD

**Issue by iDev0urer** [Microsoft/TypeScript-Sublime-Plugin#506]
My project has multiple `tsconfig.json` files, one for my gulpfiles and one for my actual project files. It seems as though neither of the files are recognized, however. I get the "Experimental decorators" error unless the `tsconfig.json` file is put in the project root.

**Comment by zhengbli** [comment]
If you have multiple tsconfig.json in the same folder, only one will be picked up, at a unpredictable order, therefore it is not recommended. Plus tsconfig.json files only covers files in the current folder and its children folder, therefore what you see is the expected behavior.
