### ISSUE TITLE
Cannot double click to select word in any language after recent update

### ISSUE THREAD

**Issue by gurutech-thomasr** [Microsoft/TypeScript-Sublime-Plugin#514]
Recent commit globally disables basic text editing feature in Sublime Text 3 across all languages.  New `Default.sublime-mousemap` is culprit, binding’s `context` is suspect:

```
Revision: 4582a1542dda4848805398713cde9505be5d01c3
Author: zhengbli <zhengbli@microsoft.com>
Date: 2016-09-02 17:13:07
Message:
Add mouse click support for go to ref


----
Added: Default.sublime-mousemap
```
```json
[
    {
        "button": "button1",
        "count": 2,
        "command": "typescript_go_to_ref",
        "press_command": "drag_select",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "text.find-refs" }
        ]
    }
]
```

Steps to reproduce:

1. Open `Packages\TypeScript\Default.sublime-mousemap`.
2. Open any other text file.
3. Double click on a word does not select the word as expected.
4. Truncate `Default.sublime-mousemap` and save.
5. Double click on word now selects the word as expected.

Workaround:  Delete `Default.sublime-mousemap` or provide user-specific alternative.

**Comment by charleylla** [comment]
it works! thank you very much!
