### ISSUE TITLE
Not recognizing typescript 2.0.3 ?

### ISSUE THREAD

**Issue by thunderkid** [Microsoft/TypeScript-Sublime-Plugin#531]
I'm trying to get the typescript-sublime-plugin working with typescript 2.0.3.
I've upgraded typescript using npm. I next removed and reinstalled the typescript-sublime-plugin package, version 0.1.16. I change the package's user settings to `"typescript_plugin_tsc_version": "2.0.3"`.
Then to test whether it's really using typescript 2. I add a `readonly` modifier to a class member. But the syntax highlighter shows it as an error, and selecting `Build With: Typescript` also gives it as an error. So apparently it's not using typescript 2. Is there some step I'm missing or does typescript-sublime-plugin not work with ts2?

**Comment by thunderkid** [comment]
Seems if I also use `"typescript_tsdk": "full/path/of/typescript"` then it does recognize `readonly` so presumably must be using typescript 2. Docs seemed to indicate that this was just required for custom or nightly builds, not the latest major release. If it's indeed required then it's not clear to me what `"typescript_plugin_tsc_version"` does.

**Comment by lgarron** [comment]
I'm also having trouble using this with TypeScript 2.

I don't have the time to figure out how to set up custom SDK paths 'n stuff, since I"m only testing TypeScript for a side project, but it would be nice if I could start learning TypeScript 2 correctly from the get-go.

**Comment by zhengbli** [comment]
We are releasing a new version with 2.0.3 soon, now I'm just testing the new tmLanguage with sublime so that hopefully they can be bundled in the same release. 

`typescript_plugin_tsc_version` is just for book keeping so we can notify you if the version you are using with Sublime doesn't match the tsc version you have globally. It doesn't change the tsdk. 

Though we do have a section regarding using different versions of typescript:
https://github.com/Microsoft/TypeScript-Sublime-Plugin#using-different-versions-of-typescript
Maybe I should put it on the top of the readme file given how many times this issue was brought up.

**Comment by thunderkid** [comment]
Thanks, that clarifies things. Looking forward to the new version.
Yes, I think you're right about more prominence in readme. When I saw it I assumed it was just for custom or nightly-build people.

**Comment by lgarron** [comment]
> Though we do have a section regarding using different versions of typescript:

That didn't work for me. :-/

However, I did replace my `Package Control` with a `git` checkout, which will work for me in the meantime.

> Maybe I should put it on the top of the readme file given how many times this issue was brought up.

Yeah, a temporary quick answer to "Are you trying to use Typescript 2? Try this." would be useful.

**Comment by aventurella** [comment]
The `User - Settings` in that note could use some clarification as there are potentially 2 places:

1. `Preferences > Package Settings > TypeScript > TypeScript Settings - User`
2. `Preferences > Settings`

It seems the `typescript_tsdk` needs to be set in `Preferences > Package Settings > TypeScript > TypeScript Settings - User`.

**Comment by ovitrif** [comment]
@aventurella I managed to add the settings in Preferences > Settings and it works with TS 2.0.3

**Comment by zhengbli** [comment]
@ovitrif  @aventurella both places should work. It is just sublime would give higher priority if you set it in `Preferences > Settings`, but as long as you only set it in one place, either one should work.
