### ISSUE TITLE
Completion window flashing on/off when typing "." after local identifier

### ISSUE THREAD

**Issue by paul-go** [Microsoft/TypeScript-Sublime-Plugin#534]
The completion window is flashing on an off rapidly on local identifiers. There are errors being generating in the output. Non-local identifiers don't have this issue. Escape does not work while the window is flashing. Using the latest version of this plugin, as well as the latest version of Sublime Text. Please see the video:

https://s3.amazonaws.com/ztube/flashing.mp4

**Comment by zhengbli** [comment]
Are you using vim or other plugin? As the "includes a dot but not req mem" log message doesn't seem to come from TS plugin.

**Comment by paul-go** [comment]
Check line 125 of https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/typescript/listeners/completion.py

**Comment by zhengbli** [comment]
Oops, sorry for that. Investigating.

**Comment by paul-go** [comment]
Upon further investigation, it looks as though there was a second copy of the TypeScript plugin hanging around in my /Packages folder. I deleted it, and the problem went away. So in a way I guess you were right all along. I guess you can close the issue, but maybe a better error message would be helpful?

**Comment by zhengbli** [comment]
Yeah I wasn't able to repro the issue after some attempts. I don't think there are much to do for this particular case regarding error messages though, because essentially you have two plugins racing for events, and one plugin doesn't really know much about other plugins.
