### ISSUE TITLE
Typescript-Sublime-Plugin should allow per-project specification of typescript_tsdk

### ISSUE THREAD

**Issue by akdor1154** [microsoft/TypeScript-Sublime-Plugin#538]
Different projects can use different typescript versions, and it can be irritating to have to change Sublime's global config to change `typescript_tsdk`. Two things could alleviate this:
- Allow specification of `typescript_tsdk` in Sublime's project settings.
- Automatically check if `node_modules/typescript/lib` exists in a project, and if so, use it.
  The second option would quiet almost all of the 'how do I use a different version of typescript?' questions ever asked, as the project's build version would then be used by default in almost all cases.

**Comment by elsimir** [comment]
Additionally, allow setting the "typescript_tsdk" using relative paths as the .sublime-project can be shared across machines so "typescript_tsdk": "./node_modules/typescript/lib" is likely to be the most widely used path.

**Comment by fiznool** [comment]
`"typescript_tsdk": "./node_modules/typescript/lib"` works for me in my user settings, to enable per-project specification. I'm on Ubuntu 16.10.

**Comment by amir-arad** [comment]
any updates on this one? It's a real blocker for me

**Comment by jussikinnula** [comment]
I'm also interested on getting multiple TypeScript versions to be used in projects. I have some legacy projects which work with the bundled 2.2.x version, but for newer projects which use TypeScript 2.4.x especially async/await and string Enums give headache. I manually updated latest TypeScript to TypeScript-Sublime-Plugin to overcome the issue, but it would be nice if there would be a configuration option to at least override the bundled version with something newer globally.

**Comment by olivererxleben** [comment]
want to ping this topic! Really blocks usage with st3

**Comment by faergeek** [comment]
Is there any update on this? This is a must have feature for me.

**Comment by raineorshine** [comment]
I see the task is closed but I'm not quite clear on the outcome. From my testing, it seems that it supports a global user setting for `typescript_tsdk` which references a project-relative path (i.e. `"node_modules/typescript/lib"`), but does not support a project-specific `typescript_tsdk` in `.sublime-project`. Can you confirm? 

I was wondering why `.sublime-project` is not supported, but maybe it's not so important since a project-relative path can be specified in the global setting. I tend to prefer project-specific settings.

**Comment by StabbarN** [comment]
I'm also having problem setting `typescript_tsdk` in `.sublime-project`. Setting `typescript_tsdk` only works as a global user setting.
