### ISSUE TITLE
Annoying error bars after build in code

### ISSUE THREAD

**Issue by jobe451** [Microsoft/TypeScript-Sublime-Plugin#544]
After every build, I get some annyoing error bars in the source, which I have to manually close by clicking the [x]:
![auswahl_018](https://cloud.githubusercontent.com/assets/910027/19217235/f8ec7810-8dd5-11e6-932e-bf51645de3a2.png)

I can't figure out how to disable them.

**Comment by zhengbli** [comment]
This is a new Sublime feature, see https://www.sublimetext.com/blog/articles/sublime-text-3-build-3124

> Inline build errors can be disabled via the show_errors_inline setting.

**Comment by p-mcgowan** [comment]
If you are coming here after trying to get rid of inline errors not in the build menu (which is solved by the comment above), check https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/556#issuecomment-260439591 for a solution.
