### ISSUE TITLE
[Microsoft/inlineError] Extremely annoying, option to disable?

### ISSUE THREAD

**Issue by roblav96** [Microsoft/TypeScript-Sublime-Plugin#552]
I find the recent updates
https://github.com/Microsoft/TypeScript-Sublime-Plugin/commit/c95049533365acc4f00d7ced07745411b9607299
to be terribly annoying. I'm typing out a constructor function and immediately a gigantic red thing pops up. I'm typing an if statement, a gigantic red thing pops up.

Can we have an option to disable this completely or maybe add a couple seconds delay?

**Comment by zhengbli** [comment]
Yes it is a good idea to add some delay. I'll send a PR to add these soon, also with the option to disable that.

**Comment by roblav96** [comment]
@zhengbli Sweet, sounds good

**Comment by lorem--ipsum** [comment]
(same as of https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/556)

**Comment by kyleholzinger** [comment]
@zhengbli just wondering, has that option to disable the large red boxes gone live yet?

**Comment by Narretz** [comment]
@zhengbli When is the next release planned? Recently, some good improvements have been merged!

**Comment by bf0** [comment]
I can't wait to be able to type without big red errors and information boxes that obscure the document popping up every 500 ms.

**Comment by zhengbli** [comment]
The new version is release with a fix for this problem. Please try it out. Thanks!
