### ISSUE TITLE
[OS X/ST 3126] Build fails, attempting to access /dev/null

### ISSUE THREAD

**Issue by jotapeh** [Microsoft/TypeScript-Sublime-Plugin#553]
Something appears to have broken builds on OS X, building any .ts (even a one-line test file) results in the following:

`error TS5058: The specified path does not exist: '/dev/null'
[Finished in 0.1s with exit code 1]
[cmd: ['/usr/local/bin/node', '/Users/jotapeh/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js', '-p', '/dev/null']]
[dir: /Users/jotapeh/Documents/NODE/Test/]
[path: /usr/bin:/bin:/usr/sbin:/sbin]`

Worked fine with a simple test 48 hours ago; can still compile fine with tsc from the command line. I am new to TypeScript and the ST plugin, so if this is something obvious I apologize.

**Comment by zhengbli** [comment]
Hi, thanks for the feedback. A new version of the plugin (2.0.1) was drafted and will be updated in a couple of hours, please try that and let me know if it fixes it.

**Comment by kyledhebert** [comment]
I opened a new issue #557 about this, since this was closed, but the issue still persists with version 2.0.1.
