### ISSUE TITLE
Signature popup not working

### ISSUE THREAD

**Issue by bjnsn** [Microsoft/TypeScript-Sublime-Plugin#558]
I'm having issues with the signature popup not working, although code completion is working:

This works:
![screen shot 2016-10-31 at 3 20 09 pm](https://cloud.githubusercontent.com/assets/791610/19873751/0c16f726-9f7e-11e6-9bb1-77c0eb2f1245.png)

But this does not:
![screen shot 2016-10-31 at 3 22 22 pm](https://cloud.githubusercontent.com/assets/791610/19873765/1ae2ad4a-9f7e-11e6-8eee-8fd6e6aa15f0.png)

Sublime version is 3126
Plugin is freshly installed from Package Control.

Not sure if this is related, but I noticed 'ref view not found' in the sublime console:
![screen shot 2016-10-31 at 3 26 37 pm](https://cloud.githubusercontent.com/assets/791610/19873836/79b32ae8-9f7e-11e6-8a17-3176c44e1d26.png)

**Comment by bjnsn** [comment]
Note that this is fixed if I revert installed typescript-sublime plugin to tagged version 0.1.16.

**Comment by aqumus** [comment]
Even I am facing the same issue as @bjnsn is facing, Any fix for this?

**Comment by bjnsn** [comment]
This is working for me as of Typescript plugin version 2.1.0
