### ISSUE TITLE
Package installation breaks down multi selection

### ISSUE THREAD

**Issue by sajera** [Microsoft/TypeScript-Sublime-Plugin#568]
ctrl+left mouse double click

After installing the package I noticed what does not work, one of the most popular features.
After removing the packages again earned.

**Comment by abenhamdine** [comment]
it works perfectly for me on ST3 build 3126, windows 10 64 bits, with current repo.

**Comment by alexburner** [comment]
@sajera please search first, this was discussed in issue #518 and patched in PR #567

**Comment by sajera** [comment]
thanks alexburner - it really help to me.
"windows 10" "ST 2"
