### ISSUE TITLE
Update TS to 2.1

### ISSUE THREAD

**Issue by maxhoffmann** [Microsoft/TypeScript-Sublime-Plugin#577]
Hey there,

I’d love to have this updated to TS `2.1` so that I can use Object spread and other new features without getting errors in Sublime. Even better would be if the plugin picks up the version from `node_modules` or have a settings file to set the path of the TS server.

Cheers!

**Comment by zhengbli** [comment]
I just drafted a new release. Though the setting to use a customized TS version is already available:
https://github.com/Microsoft/TypeScript-Sublime-Plugin#note-using-different-versions-of-typescript
