### ISSUE TITLE
TypesScript plugin causes find result highlight not working properly

### ISSUE THREAD

**Issue by liuxinhu** [Microsoft/TypeScript-Sublime-Plugin#590]
I am running Sublime Text 3 on Windows with TypeScript package installed.

When I use "Find" to find something in a file, the result highlight does not work properly after setting the file type as TypeScript. Normally the found term is highlighted with yellow background. But in this case the yellow background shows only about 2 seconds and then disappears.

**Comment by 1-9** [comment]
I have the same issue, appreciate if this can be fixed.

**Comment by jbrecht** [comment]
I have the same issue in OS X.

**Comment by zhengbli** [comment]
You can set `typescript_highlight_occurrences` to false in your sublime settings and disable that feature.
