### ISSUE TITLE
Is there a way to ignore keywords?

### ISSUE THREAD

**Issue by wmpay** [Microsoft/TypeScript-Sublime-Plugin#595]
I'm using webpack, typescript and angular in my project. Since webpack does all the dirty work of bundling files, there are references to `angular` and `require` that throw the "Cannot find name" error, since they are not explicitly defined in the file. Is there a way to tell the plugin to ignore certain keywords?

**Comment by zhengbli** [comment]
No there are no ways to do that currently. You might have to declare them as ambient variables like `declare var angular: any;`.

The alternative way is that you can choose to disable the language service entirely by setting `enable_typescript_language_service` to false in your sublime settings.
