### ISSUE TITLE
fetch() definitions not loaded correctly

### ISSUE THREAD

**Issue by rc-davis** [Microsoft/TypeScript-Sublime-Plugin#596]
The fetch definitions, recently added to the default lib.d.ts, are not being loaded by this plugin. 

Put a call to "fetch()" in any ts file, and it should be highlighted as an error ("Cannot find name 'fetch'), but compiling with the latest tsc should produce no errors. 

Here's my setup:

Sublime Text 3 build 3126
TypeScript plug-in 2.1.0
TypeScript 2.2.2
Mac OS 10.12.3

tsconfig.json:
{
  "compilerOptions": {
    "sourceMap": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "module": "commonjs",
    "target": "es6",
    "jsx": "preserve",
    "allowJs": false,
    "pretty": true,
    "experimentalDecorators": true
    }
}

**Comment by zhengbli** [comment]
The TS version shipped with Sublime Plugin is kinda outdated, the new versions will be shipped next time with this plugin. Meanwhile you can choose to use a custom TS version with [these instructions](https://github.com/Microsoft/TypeScript-Sublime-Plugin#note-using-different-versions-of-typescript)

**Comment by rc-davis** [comment]
Thanks. Sorry for the confusion.
