### ISSUE TITLE
Typescript string autocompletion suggestions from file

### ISSUE THREAD

**Issue by it6** [Microsoft/TypeScript-Sublime-Plugin#600]
Is there a way to get autocomplete inside typescript strings? I need the suggestions from existing file contents nothing fancy, I tried copying and pasting the scope in auto_complete_selector but that didn't work.

In Typescript

<img width="338" alt="screen shot 2017-04-11 at 6 58 45 pm" src="https://cloud.githubusercontent.com/assets/5510191/24934503/e6442d48-1ee9-11e7-8f5a-a9a9d2f86c2a.png">

Here is what I get in a JavaScript file, can I achieve the same in typescript?

<img width="547" alt="screen shot 2017-04-11 at 6 58 17 pm" src="https://cloud.githubusercontent.com/assets/5510191/24934504/e83641f4-1ee9-11e7-89c2-97b286ef1c4b.png">

**Comment by it6** [comment]
FYI: By default typescript disables autocomplete for keywords within the file. So only autocompletion available is when typescript server sends suggestions for autocomplete.

If you want autocomplete from both `tsserver` and file local keywords.

1) Open `Library/Application Support/Sublime Text/Packages/TypeScript/typescript/listeners/completion.py` 
2) Change return value of `on_query_completions` method, approximately line `109` 
`return completions, sublime.INHIBIT_EXPLICIT_COMPLETIONS`

<img width="832" alt="screen shot 2018-02-03 at 6 16 18 pm" src="https://user-images.githubusercontent.com/5510191/35772512-5fa13334-090e-11e8-8bca-6a36ba3611c4.png">

**Comment by martinRenou** [comment]
That is a really good catch, thanks a lot! I do think this should be fixed though. Would you mind opening a PR for that?

**Comment by it6** [comment]
Please feel free to open a `PR` . The last `PR` I made (https://github.com/microsoft/TypeScript-Sublime-Plugin/pull/661) is sitting there for more than an year :( also I don't actively using this plugin anymore.
