### ISSUE TITLE
Add support for Template Strings syntax highlighting

### ISSUE THREAD

**Issue by cedeber** [Microsoft/TypeScript-Sublime-Plugin#603]
HI. Looks like the Template Strings syntax highlighting doesn't work well. On Sublime 3131 (currently dev) it's already implemented for the JavaScript language. One improvement I see is that we could highlight the holders `${..}` differently so that they are more visible.

If I can help in any manner, please tell me.

Thanks

**Comment by billti** [comment]
Our grammar is worked on in the repo at https://github.com/Microsoft/TypeScript-TmLanguage . There's been quite a few fixes in there lately. If you could see if problems persist there, and if so either a) submit a fix, or b) log a more detailed bug on that repo - that would be helpful. Thanks!

**Comment by cedeber** [comment]
ok, thanks for the infos.
