### ISSUE TITLE
Exclude test files from compilation but include for plugin processing

### ISSUE THREAD

**Issue by ernieturner** [Microsoft/TypeScript-Sublime-Plugin#605]
My tsconfig file currently looks like this

```
{
    "compilerOptions": {
        "alwaysStrict": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "noUnusedParameters": true,
        "noEmitOnError": true,
        "noUnusedLocals": true,
        "declaration": false,
        "target": "es2015",
        "baseUrl": ".",
        "paths": {
            "*": [
                "src/*"
            ]
        },
        "moduleResolution": "node",
        "lib": ["es6", "dom"]
    },
    "exclude": [
        "node_modules",
        "dist",
        "**/tests/*.test.ts",
        "src/tests"
    ]
}
```

And my code is setup where my unit test files are located in a `tests` directory as a sibling of the source file, e.g.

```
/lib
   /tests
      Utils.test.ts
  Utils.ts
```

When I compile my code the current setup works find and ignores all unit test files during compilation. However, when I open the unit test files in Sublime with this configuration it can't find any of the global types that it should find from jasmine/karma/etc.

![screen shot 2017-05-04 at 3 31 09 pm](https://cloud.githubusercontent.com/assets/11216295/25725797/bd591f72-30de-11e7-9966-3dd6b0eef2fd.png)

If I remove the unit test file from the `exclude` list in tsconfig, then it all starts working again.

Is there a way to exclude files from TS compilation but still have the plugin process them correctly?

**Comment by billti** [comment]
You will need a separate tsconfig.json that includes your test files along with the necessary compiler options and files to build the appropriate context. They are excluded in the above project, so TypeScript will effectively treat them as standalone files when opened.

**Comment by fossecode** [comment]
It the problem only applies for jest, you can add this to your jest config:
```
"jest": {
    "testPathIgnorePatterns": [
      "<rootDir>/build/",
      "<rootDir>/node_modules/"
    ]
}
```

**Comment by AverageHelper** [comment]
For more info on working with multiple tsconfig.json files, see [this StackOverflow answer](https://stackoverflow.com/a/58461810/3799856). Basically you'd make use of the `"extends"` field so as to not duplicate your compiler options overmuch.

You may need to change how you run `tsc` just a tad:
```shell
tsc --project tsconfig.production.json # or whatever you call your other tsconfig
```

**Comment by sebastienbarre** [comment]
> You will need a separate tsconfig.json that includes your test files along with the necessary compiler options and files to build the appropriate context. They are excluded in the above project, so TypeScript will effectively treat them as standalone files when opened.

OK this is super old, but still going on in 2025. When you say "TypeScript will treat them as standalone files when opened.", then exactly *which* `tsconfig.json` is being used here? Which settings are used to validate the file?
