### ISSUE TITLE
Ctrl+V does not work

### ISSUE THREAD

**Issue by richardhuaaa** [Microsoft/TypeScript-Sublime-Plugin#61]
I'm using Sublime 2 x64.
1. Create a new *.ts file (or use any existing one)
2. Type some text, highlight it, press 'Ctrl+C'.
3. Press 'Ctrl+V'.

Nothing will be pasted. You can paste anywhere else though, and in non-ts sublime files. You can also use the mouse to right click and paste, it seems only the keyboard shortcut 'Ctrl+V' is busted.

**Comment by antoinerousseau** [comment]
I'm still having this issue under ST3. Using v0.1.3 of this plugin.
