### ISSUE TITLE
[typescript@^2.4.0] Broken autocomplete for types

### ISSUE THREAD

**Issue by roblav96** [Microsoft/TypeScript-Sublime-Plugin#612]
If you have `typescript@^2.4.0` installed globally and use the setting `typescript_tsdk`, autocomplete for types does not even work.

```typescript
let idk = null as number
```
When typing `n` after `as`, autocomplete should show for available types, but it does not.

@zhengbli I really hope this gets fixed cause it's a major feature of this plugin :X

**Comment by DanielRosenwasser** [comment]
Can you try using `typescript@2.4.2` or `typescript@next` and seeing if that works?

**Comment by roblav96** [comment]
@DanielRosenwasser Upgrading to `2.4.2` resolves this issue =]
