### ISSUE TITLE
does not recognize 'abstract' keyword

### ISSUE THREAD

**Issue by jpaulin** [Microsoft/TypeScript-Sublime-Plugin#613]
Within Sublime 3, when building a .tsx file, the tsc compiler used does not recognize an 'abstract' keyword.

Gives TS1005 error. 

Workaround was dropping in a newer tsc version for the package: 

cp ./.nvm/versions/node/v7.10.0/lib/node_modules/typescript/lib/tsc.js /home/johndoe/.config/sublime-text-3/Packages/TypeScript/tsserver/tsc.js

By copying a newer tsc on top of (ie. replacing) the 'tsc' supplied with the current Sublime package,
this error faded away. Compile was ok again, 'abstract' got recognized. 
My working tsc is
```
$ tsc --version
```

2.3.3

Seems to be just an issue of newer vs. older?

**Comment by DanielRosenwasser** [comment]
Should be fixed now - we just published TypeScript 2.6, and the plugin should be published within the next 2 hours.
