### ISSUE TITLE
Class with type parameter defaults

### ISSUE THREAD

**Issue by Losmoges** [Microsoft/TypeScript-Sublime-Plugin#619]
Typescript plugin is erroneously reporting an error on the following line.

export class Foo<T, K = any>

--
Type parameter name cannot be 'any'
(type parameter) any in Foo<T, K, any>
--

It seems that the typescript plugin is wrongly interpreting the K = any default assignment?
The code does compile and run just fine. Intellij does not report an error on this line.

**Comment by DanielRosenwasser** [comment]
The package should now come with TypeScript 2.5.3, so give that a shot.

**Comment by Losmoges** [comment]
It works! Many thanks.
