### ISSUE TITLE
Plugin not working at all

### ISSUE THREAD

**Issue by ashok-sc** [Microsoft/TypeScript-Sublime-Plugin#628]
Hi there, I've just installed this plugin on a new install of Sublime Text 3. Nothing is being autocompleted though. Basically doesn't seem like the TS server is running. Is there something else I need to do?

**Comment by DanielRosenwasser** [comment]
You should just be able to get it running on any `.ts` file. Check out the [Tips and Known Issues](https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Tips-and-Known-Issues) section in the wiki.

**Comment by DanielRosenwasser** [comment]
@ashok-sc did you end up getting it working?

**Comment by ashok-sc** [comment]
I haven't tried again. Spent a bit of time and have now since moved onto VS Code hehe. Sorry I didn't give it another shot. I'm sure it was something wrong with my setup. You can probably close this.
