### ISSUE TITLE
Request to add auto import

### ISSUE THREAD

**Issue by it6** [microsoft/TypeScript-Sublime-Plugin#630]
Can you please add ability to auto import.
Ideally a `keyboard shortcut/menu item` which works on the `class` where the cursor is located.

**Comment by DanielRosenwasser** [comment]
What exactly do you mean by auto-import?

**Comment by longitude** [comment]
For example, I can write a class and then press a key to import the class at the top of the file.
![sublime-text-import](https://user-images.githubusercontent.com/5510191/32373438-a0185cb8-c06f-11e7-8136-d9f0d935c138.gif)

**Comment by tim545** [comment]
+1 would be great to have this feature working, a good explanation of the feature is also on a Sublime Text forum post:

https://forum.sublimetext.com/t/typescript-auto-import-plugin/18453/1
