### ISSUE TITLE
Error TS2339

### ISSUE THREAD

**Issue by tpck** [Microsoft/TypeScript-Sublime-Plugin#631]
I am getting the error _TS2339: Property 'endsWith' does not exist on type [insert a string variable here]_ when I build a TypeScript file using the below example:

`console.log( "myString".endsWith("g") );`

The TypeScript autocomplete also does not list ES6 methods (such as the above _endsWith_). 

This error does not happen in VS Code (and the autocomplete also works correctly with ES6 methods in VS Code).

**Comment by mhegazy** [comment]
make sure your configuration either have `--target ES6` or `--lib es6, dom`
