### ISSUE TITLE
Syntax highlighting for object properties

### ISSUE THREAD

**Issue by evenfrost** [Microsoft/TypeScript-Sublime-Plugin#632]
Would be great if we had syntax highlighting for object properties. Right now it looks like this:
![object](https://user-images.githubusercontent.com/3055750/33234838-116262ee-d23e-11e7-8a30-92a42186add4.png)
And this is how `babel-sublime` handles this:
![object-2](https://user-images.githubusercontent.com/3055750/33234844-2e1ab8dc-d23e-11e7-9692-f723b34f00b1.png)
Quoted properties here are just as an example of what it looks like to be a proper syntax highlighting for such case.

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#547
