### ISSUE TITLE
Renaming token does not work between file types (.ts, .js)

### ISSUE THREAD

**Issue by adrian-moisa** [Microsoft/TypeScript-Sublime-Plugin#636]
In VScode I was used to press `F2` to rename a token and this behavior works even between file types. Say between `foo-bar.ts` and `foo-bar.spec.js`. It looks like typescript sublime package is able to rename in all files but only in `.ts`. The `Ctrl + T, Ctrl + M` hotkey does not work between ts and js. It can be a bit daunting when you have lots of tests written in js. On the long run I want to setup a full .ts environment but right now setting up the tests in .ts + es6 seems more chalenging than expected.

**Comment by DanielRosenwasser** [comment]
Seems related to #278.

**Comment by DanielRosenwasser** [comment]
Should be fixed by #620 in the next release.
