### ISSUE TITLE
All TS sublime keyboard commands no longer work, as the first ctrl+t now transposes letters.

### ISSUE THREAD

**Issue by fionafung** [Microsoft/TypeScript-Sublime-Plugin#64]
I'm sunk to tip as of 02/27, 9am.  ctrl+T, ctrl+D no longer goes to def, ctrl+t now seems to transpose letters based around the character.

**Comment by kalloc** [comment]
@steveluc  Sorry, but I confirm this bug on ST3/Mac, plugin from master.

^T called transpose plugin, not typescript-sublime-plugin
