### ISSUE TITLE
autocomplete, errors highlights, and code formatting don't work on Linux

### ISSUE THREAD

**Issue by lidebug** [Microsoft/TypeScript-Sublime-Plugin#640]
I've just migrated from windows on Linux ubuntu 16.04 and faced the issue.
Ctrl+F+T has no result ( as command **typescript_format_document** )
Sublime doesn't show errors and autocomplete.

But Typescript package is installed and code highlights works well.

**Comment by DanielRosenwasser** [comment]
Have you checked over the [Tips and Known Issues](https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Tips-and-Known-Issues) page?

**Comment by lidebug** [comment]
I just did. There is no solution for the issue.
I want to mark that everything work just fine on Windows, but the issue comes when I open ts file on linux.

I tested that on several computer - same result.

**Comment by lidebug** [comment]
Problem fixed.
I didn't have typescript globally installed.
