### ISSUE TITLE
What is this print("ref view not found") going out to console when I start Sublime Text?

### ISSUE THREAD

**Issue by evandrocoan** [microsoft/TypeScript-Sublime-Plugin#647]

**Comment by acheronfail** [comment]
Want to open a PR with your fork: https://github.com/evandroforks/TypeScript/commit/2a584ee662e4ecddb5f67207f3e0dad45e1b8a66 ?

**Comment by aklef** [comment]
Bump. @evandrocoan Please submit a PR with your changes~!!

**Comment by evandrocoan** [comment]
Done!
