### ISSUE TITLE
Color numbers using ES Numeric Separators the same as other numbers

### ISSUE THREAD

**Issue by IceCreamYou** [Microsoft/TypeScript-Sublime-Plugin#649]
[As of TS 2.7](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#numeric-separators), TypeScript supports [ES Numeric Separators](https://github.com/tc39/proposal-numeric-separator), like this:

```ts
const milion = 1_000_000;
```

Although this syntax correctly doesn't get interpreted as an error, it isn't syntax-highlighted as a number:

![image](https://user-images.githubusercontent.com/203177/37380344-7cd48a50-26f5-11e8-8314-1fa98f9b71c6.png)

![image](https://user-images.githubusercontent.com/203177/37380361-90992c80-26f5-11e8-9b25-174b9cc4ab42.png)

It'd be nice if those two examples had the same color.

(If this is not the right place for this issue, let me know. I searched and didn't find any other issues about this topic.)

**Comment by DanielRosenwasser** [comment]
Should be fixed with the new release on PackageControl.
