### ISSUE TITLE
Broken type highlighting inside of angle brackets

### ISSUE THREAD

**Issue by rvinzent** [Microsoft/TypeScript-Sublime-Plugin#652]
Hello,

The latest update broke the type declarations after function names but before the parentheses. It only occurs when the type is an array denoted by brackets. It seems to work fine in all other cases. 

Broken:
![broken syntax highlighting](https://user-images.githubusercontent.com/34038882/38041840-a8f3c33a-3267-11e8-86d2-f79fd18a6902.JPG)

Expected:
![correct syntax highlighting](https://user-images.githubusercontent.com/34038882/38041850-b01534e6-3267-11e8-9bdc-08dfed2b9795.JPG)

Thanks!

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#593
