### ISSUE TITLE
Support for Vue single-file-components?

### ISSUE THREAD

**Issue by pearofducks** [Microsoft/TypeScript-Sublime-Plugin#655]
Is there planned support for single-file-components in Vue? Or a way to enable TS support for them?

Example - `Hello.vue` in [the official example repo](https://github.com/Microsoft/TypeScript-Vue-Starter)

**Comment by DanielRosenwasser** [comment]
I think this would be out of scope for us, but more in the mission of Vue and vue-language-server, which still leverages TypeScript. Check out https://github.com/vuejs/vetur/issues/284.

**Comment by pearofducks** [comment]
Makes sense, thanks!
