### ISSUE TITLE
Syntax highlighting error, when comments before 'if' line

### ISSUE THREAD

**Issue by wlchn** [Microsoft/TypeScript-Sublime-Plugin#672]
Syntax highlighting error, when comments before 'if' line and previous line without semicolon.
eg.
no comments no error:
![image](https://user-images.githubusercontent.com/4652410/44563917-04f50e00-a793-11e8-89fa-f14150bc7bb4.png)
with semicolon no error:
![image](https://user-images.githubusercontent.com/4652410/44564151-1b4f9980-a794-11e8-8c9e-6df19a711bb1.png)
without semicolon cause highlighting error in "if" line:
![image](https://user-images.githubusercontent.com/4652410/44846909-67af4380-ac84-11e8-86c9-c32b0fe4a9dc.png)

**Comment by DanielRosenwasser** [comment]
Here's the repro:

```ts
let a = "a" //blah
if (a) {
    console.log(a);
}
```

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#669
