### ISSUE TITLE
Incorrect type check in sublime

### ISSUE THREAD

**Issue by foisonocean** [microsoft/TypeScript-Sublime-Plugin#675]
I have write my own d.ts file to extend the request object with property `cookies`:

```typescript
import * as fastify from 'fastify';

declare module 'fastify' {
  interface FastifyRequest<HttpRequest> {
    cookies: {
      [cookieName: string]: string | undefined;
    };
  }
}
```

And I can also build successful using command `tsc`, but in the sublime editor, I got this error:

![image](https://user-images.githubusercontent.com/15059605/45334431-5c75e500-b5ad-11e8-80b8-a2cb6b8ae710.png)

And VS Code can handle this correctly:

![image](https://user-images.githubusercontent.com/15059605/45334580-f342a180-b5ad-11e8-8c51-5bb38648855b.png)

**Comment by DanielRosenwasser** [comment]
I'm not able to see this behavior. Try out with the latest version and provide a self-contained repro of the issue

**Comment by foisonocean** [comment]
@DanielRosenwasser 

I fixed this problem by npm install TypeScript globally.

Actually I would like to know which TypeScript instance is used by sublime typescript plugin? The one installed in current project? The one bundled with Sublime plugin? Or the one installed globally?
