### ISSUE TITLE
Linting Gone Astray?

### ISSUE THREAD

**Issue by wbond** [Microsoft/TypeScript-Sublime-Plugin#703]
We've started seeing a number of posts on the forum that seem to be caused by this plugin.

 - https://forum.sublimetext.com/t/remove-syntax-highlight-red-wavy-underlines-everywhere/41663
 - https://forum.sublimetext.com/t/how-to-disable-the-spell-syntax-error-checker-red-underlines/41703

I figured I'd give you a heads up.

**Comment by wbond** [comment]
Here is another case: https://forum.sublimetext.com/t/unwanted-underlines-in-vue-components/41801

**Comment by l2aelba** [comment]
I tho it was only me. 

Have not any problem like this before.
- MacOS Mojave 10.14.3
- Does not happen when opened, it shows like this after do some action and sometimes.

![screenshot 2019-02-14 at 11 54 22](https://user-images.githubusercontent.com/983458/52782418-4afaa280-304f-11e9-8b7f-98e9555cf354.png)

**Comment by Patabugen** [comment]
For me disabling the "TypeScript" plugin (as suggested here: https://forum.sublimetext.com/t/remove-syntax-highlight-red-wavy-underlines-everywhere/41663/10 ) has solved this issue.

**Comment by khatrinitesh** [comment]
Hi

**Comment by khatrinitesh** [comment]
I need some help.

**Comment by DanielRosenwasser** [comment]
Sorry about this everyone - I think I have the fix. I'll try to put it out tomorrow.

**Comment by khatrinitesh** [comment]
Hi,

Okay, no problem.

**Comment by DanielRosenwasser** [comment]
Fix is out at #705.
