### ISSUE TITLE
[BUG] One line that hangs up the plugin

### ISSUE THREAD

**Issue by Fxlr8** [microsoft/TypeScript-Sublime-Plugin#713]
somehow this line of styled-components syntax explodes everything
```
const Wrapper = styled.div``
```
after saving a file with this line I immediately see a node process with 100+% CPU usage and code hints stop working

Sublime 3: build 3200
Typescript plugin: v3.4.1 
MacOS Mojave

**Comment by Fxlr8** [comment]
I rolled back to 3.3.3333 release and I don't have this problem. Looks like something is wrong with the latest release.

**Comment by DanielRosenwasser** [comment]
We're currently tracking this at https://github.com/Microsoft/TypeScript/issues/30819. Alternatively, you can

- updating to a new version of styled-components which avoids this regression so long as you have no interpolations.
- Update to TypeScript's 3.5 nightly versions, which contains a workaround.
