### ISSUE TITLE
Error list support

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-Sublime-Plugin#72]
Since sublime only shows errors for the current file, I find myself looking for all errors in my project; and for these i need to build the project. it would be helpful to have an error list support a la find all references window, that i can use to see all errors and navigate to them.

**Comment by johnfn** [comment]
Progress on this @hinzo or others? This is one feature I would really like to have.

**Comment by zhengbli** [comment]
@johnfn I'm working on it, should be sending out a PR for discussion soon.

**Comment by johnfn** [comment]
@zhanbos awesome, can't wait! :D

**Comment by zhengbli** [comment]
@johnfn FYI pr #243 is up, any comments about the design is welcome!

**Comment by zhengbli** [comment]
The feature is added in release 0.1.7
