### ISSUE TITLE
Can't see errors

### ISSUE THREAD

**Issue by stweedie** [microsoft/TypeScript-Sublime-Plugin#731]
As of a recent patch [(presumably this one)](https://github.com/microsoft/TypeScript-Sublime-Plugin/commit/eea3d8a9d7f3c9839c11f8c39c4c7a247f5c5a2c#diff-ce9686643aed3ba1d9887d0a45edf126R165), the plugin will not show ANY error diagnostics in the file if you do not provide a color in your preferences

preferences
```json
{
  "error_icon": "circle"
}
```
![image](https://user-images.githubusercontent.com/10199133/68325207-91d17200-008e-11ea-838f-ff8b8b763435.png)

with override
```json
{
  "error_color": "region.redish",
  "error_icon": "circle"
}
```
![image](https://user-images.githubusercontent.com/10199133/68325257-a7469c00-008e-11ea-8352-c6555ad0a4b7.png)

It appears that the 'default' value is being ignored, which causes there to be no error indicator at all.

**Comment by rlugge** [comment]
THANK you @stweedie , this was crippling my ability to develop.  Typescript without IDE type checking is just... ugh.  Not getting an error report

**Comment by stweedie** [comment]
yeah as a workaround, [follow these instructions](https://github.com/microsoft/TypeScript-Sublime-Plugin#other-settings) and add the above json snippet (or a different color if you want)

**Comment by lorem--ipsum** [comment]
Oh my gosh THANK YOU.

**Comment by orta** [comment]
Anyone know if there is a change we can apply to this plugin to fix this for everyone?

/cc @bertilnilsson

**Comment by telmaco** [comment]
I spent the whole day trying to fix this.
una lastima! :/

Thank you @stweedie!!!

**Comment by gas0324** [comment]
In order to solve this problem, I reinstall many times...
Thank you very much, found the problem
Thank you @stweedie!!!

**Comment by patrickfatrick** [comment]
I just noticed this the other day and assumed I messed up a config. Thank you so much for the workaround, @stweedie

**Comment by DanielRosenwasser** [comment]
https://github.com/microsoft/TypeScript-Sublime-Plugin/pull/735 has a fix available, should be out soon. Very sorry for the confusion here.
