### ISSUE TITLE
Typescript 4 version not pushed to Package Control

### ISSUE THREAD

**Issue by StoneCypher** [microsoft/TypeScript-Sublime-Plugin#756]
would love to use labelled tuples but my editor is getting confused at the moment

**Comment by jgburet** [comment]
Any way we could get this out?
Can't use any of the `||=` operators :'(

**Comment by orta** [comment]
This was blocked by #765

**Comment by jgburet** [comment]
Hey @orta , glad this is finally moving forward :)
Is there anything left to do to have 4.0-tag pushed, so PackageControl receives the new version? Or is there any ETA defined yet?

**Comment by orta** [comment]
Nope, we're probably going to release with the usual process for 4.2
