### ISSUE TITLE
There is NOT the 'TypeScript' plugin on 'Package Control: Install Package.'

### ISSUE THREAD

**Issue by patineboot** [microsoft/TypeScript-Sublime-Plugin#787]
**Reproduce:**
Using [Package Control](https://packagecontrol.io/) for Sublime Text
1. Push Command + Shift + P key.
1. Enter 'Package Control: Install Package,' and select 'Package Control: Install Package.' 
1. Enter 'TypeScript' on 'Package Control: Install Package.'

**Actual Behavior:**
There is **NOT** the 'TypeScript' plugin on  'Package Control: Install Package.'
I found the _TypescriptCompletion_ and _ArcticTypescript_ package but **not 'TypeScript'**.

**Expected Behavior:**
I will find the 'TypeScript' plugin on 'Package Control: Install Package.'

**Environment:**  
- macOS Monterey version 12.4
- Sublime Text Stable Channel, Build 4126

**Comment by rchl** [comment]
This package is not maintained and works poorly in ST4. Look at #786.

**Comment by patineboot** [comment]
@rchl, thanks again.
I use now and in future [LSP-typescript](https://packagecontrol.io/packages/LSP-typescript).

Bullshit Microsoft.

**Comment by rchl** [comment]
You can close this issue.
